### ISSUE TITLE
dev-util/jd-gui-bin missing dependency on 32bit gtk+2

### ISSUE THREAD

**Issue by tecknicaltom** [pentoo/pentoo-overlay#10]
dev-util/jd-gui-bin needs a runtime dependency on x11-libs/gtk+:2[abi_x86_32]

Running the program without a 32bit gtk+2 produces the following error immediately:
```
jd-gui: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

It may have other dependencies, but this is the one that it's currently stopping at for me.

**Comment by blshkv** [comment]
ok, fixed in commit 2fe99a534e6b3c09997d951cc18b9e912ba08b45. The tools has been released as open source as well. I will have a look and bump version 4. Cheers.
