### ISSUE TITLE
net-analyzer/crackmapexec-3.1 fails to emerge with "TypeError: find_packages() got an unexpected keyword argument 'include'"

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#104]
>>> Emerging (1 of 1) net-analyzer/crackmapexec-3.1::pentoo
 * crackmapexec-3.1.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...          [ ok ]
>>> Unpacking source...
>>> Unpacking crackmapexec-3.1.tar.gz to /mnt/disk-image4/portage/net-analyzer/crackmapexec-3.1/work
>>> Source unpacked in /mnt/disk-image4/portage/net-analyzer/crackmapexec-3.1/work
>>> Preparing source in /mnt/disk-image4/portage/net-analyzer/crackmapexec-3.1/work/CrackMapExec-3.1 ...
 * Applying crackmapexec-3.1-leftovers.patch ...                         [ ok ]
>>> Source prepared.
>>> Configuring source in /mnt/disk-image4/portage/net-analyzer/crackmapexec-3.1/work/CrackMapExec-3.1 ...
>>> Source configured.
>>> Compiling source in /mnt/disk-image4/portage/net-analyzer/crackmapexec-3.1/work/CrackMapExec-3.1 ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    "cme", "cme.*"
TypeError: find_packages() got an unexpected keyword argument 'include'

I also tried from source pulled from github directly, with the same error. I tried with python27 and python34, with different but just as disappointing results.
I tried duplicating the error on another Pentoo build, but was not able to do so.
I tried upgrading dev-python/setuptools and dev-python/pip, based on some notes I saw about similar error messages, but that did nothing for me.

[files.zip](https://github.com/pentoo/pentoo-overlay/files/342651/files.zip)

**Comment by blshkv** [comment]
can't reproduce. It looks like your python env is broken. See http://stackoverflow.com/questions/29477456/find-package-errors-during-installing-package-via-pip
remove all pip and make sure that setuptools are uptodate

**Comment by blshkv** [comment]
can't reproduce. It looks like your python env is broken. Do not run as root or/and make sure that there are no outdated packages left somewhere like /root/.pip. dev-python/pip should NOT be installed.
