### ISSUE TITLE
cpuinfo2cpuflags issue

### ISSUE THREAD

**Issue by ostree** [pentoo/pentoo-overlay#105]
Hello,

this bit from pentoo/pentoo-system/pentoo-system-2016.2-r2.ebuild caused a problem:

	!arm? ( app-portage/cpuinfo2cpuflags )

I manually edited this to:

	!arm? ( app-portage/cpuid2cpuflags )

Is it correct or I just overlooked something?

Kind Regards

**Comment by ostree** [comment]
#106

**Comment by blshkv** [comment]
That's right, the package has been renamed
