### ISSUE TITLE
net-wireless/sdrtrunk-0.4.0-r1 fails to compile: > Could not find method compile() for arguments [org.openjfx:javafx-base:13:win] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler 

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1055]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: net-wireless/sdrtrunk-0.4.0-r1 fails to compile.
Discovered on: amd64 (internal ref: pentoo_tinderbox)

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/2920431c427f6e16526d62e5273073f1

**Comment by blshkv** [comment]
you need select jdk:15 manually for now:
```eselect java-vm set system-vm openjdk-bin-15```

**Comment by ZeroChaos-** [comment]
We can do that in the ebuild, the java eclass handles it based on deps.

**Comment by blshkv** [comment]
except 15 is not supported

**Comment by blshkv** [comment]
should be fixed by 031ae7866aa78debdc49aeb8b2ff7d717433d4d4
