### ISSUE TITLE
net-dialup/freeradius-3.0.21-r3 installs shared libraries that lack a SONAME

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1063]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: net-dialup/freeradius-3.0.21-r3 installs shared libraries that lack a SONAME.
Discovered on: amd64 (internal ref: pentoo_tinderbox)

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/541df01f958da8bc3198acf55ce26815

**Comment by blshkv** [comment]
https://github.com/FreeRADIUS/freeradius-server/issues/1774
https://bugs.gentoo.org/721040

**Comment by asarubbo** [comment]
> [FreeRADIUS/freeradius-server#1774](https://github.com/FreeRADIUS/freeradius-server/issues/1774) https://bugs.gentoo.org/721040

My personal thought is that since it was reported downstream, the ticket should stay open until the bug is resolved in this repo. Otherwise tinderbox and other users will report again this issue.
