### ISSUE TITLE
pentoo/pentoo-system - switch from sys-fs/exfat-utils to sys-fs/exfatprogs

### ISSUE THREAD

**Issue by Bogdan107** [pentoo/pentoo-overlay#1082]
Last release of [exfat-utils](https://github.com/relan/exfat): v1.3.0 - on 15 Sep 2018
Last release of [exfatprogs](https://github.com/exfatprogs/exfatprogs): v1.1.3 - 24 days ago (11 Dec 2021)
[Page](https://forum.manjaro.org/t/exfat-utils-or-exfatprogs/46915) says, that `exfatprogs` - is new replacement for `exfat-utils` package.

Please, update `pentoo/pentoo-system` ebuild to use `exfatprogs` package.

**Comment by Bogdan107** [comment]
May be a compromise, like this:
`||? ( sys-fs/exfat-utils sys-fs/exfatprogs )`

**Comment by ZeroChaos-** [comment]
I don't know much about exfatprogs, @blshkv ?  Based on very quick reading I'm thinking :
```
|| ( sys-fs/exfatprogs sys-fs/exfat-utils  )
```
What do you think?

**Comment by ZeroChaos-** [comment]
@blshkv got any opinion here?

**Comment by blshkv** [comment]
From what is on the surface, exfat-utils is a  FUSE module vs exfatprogs which is official userspace utilities for a kernel driver. We can add an option via || (and there is also sys-fs/fuse-exfat), but I would just go with sys-fs/exfatprogs.

**Comment by ZeroChaos-** [comment]
fixed by 3badee674ea5cd19d362e32b8cef336e7ffa6a94

thanks for the report
