### ISSUE TITLE
add sys-process/iotop-c as an alternative for sys-process/iotop

### ISSUE THREAD

**Issue by Bogdan107** [pentoo/pentoo-overlay#1083]
Gentoo overaly has `sys-process/iotop` and `sys-process/iotop-c` packages.

This packages requires `sys-process/iotop`:
- pentoo-system/pentoo-system
- rfctf-client/rfctf-client
- zero-system/zero-system

But I like `sys-process/iotop-c`.

Please, modify ebuilds to use alternatives, like this:
`||? ( sys-process/iotop sys-process/iotop-c )`

**Comment by ZeroChaos-** [comment]
No.  Two of these packages are basically my personal metapackages, and the package in question is small enough that I honestly have to wonder if opening this bug took longer than updating it.

**Comment by Bogdan107** [comment]
At now, `pentoo-system/pentoo-system` package requires me to install `sys-process/iotop` package.
But `sys-process/iotop` conflicts with `sys-process/iotop-c`.
So I need to make choise: use `pentoo-system` with `iotop`, or use `iotop-c` and install eash of `pentoo-system` sub-packages manually.

Modifying `pentoo-system` ebuild from:
`sys-process/iotop`
to
`||? ( sys-process/iotop sys-process/iotop-c )`
allows to install `pentoo-system` package with `iotop-c` without conflict.

**Comment by ZeroChaos-** [comment]
looking at the activity of iotop vs iotop-c upstream, not only will I grant this, I'll default to iotop-c.  Thanks for your persistence.
