### ISSUE TITLE
pentoo/pentoo-desktop - add ungoogled-chromium as an alternative

### ISSUE THREAD

**Issue by Bogdan107** [pentoo/pentoo-overlay#1084]
`pf4public` overlay has `www-client/ungoogled-chromium` and `www-client/ungoogled-chromium-bin` packages, which conflicts with `www-client/chromium` and `www-client/chromium-bin` packages.

Please, add `www-client/ungoogled-chromium` and `www-client/ungoogled-chromium-bin` as an alternatives to the ebuild file.

**Comment by ZeroChaos-** [comment]
If these packages were in gentoo I'd add this in a second, but since they aren't, I think package.provided should do what you want.  I'm not adding alternatives from random overlays.
