### ISSUE TITLE
pentoo/pentoo-opencl - add dev-libs/pocl as an alternative for AMD CPU

### ISSUE THREAD

**Issue by Bogdan107** [pentoo/pentoo-overlay#1085]
For Intel CPU this package install `dev-util/intel-ocl-sdk`.
I have AMD CPU.
Package `dev-libs/pocl` provide support of OpneCL for the AMD CPU.

Please, modify ebuild to add `dev-libs/pocl` package.
For example, like this:
`|| ( dev-util/intel-ocl-sdk dev-libs/pocl )`

**Comment by ZeroChaos-** [comment]
Interestingly enough, I'm told that the intel-ocl-sdk is faster on AMD than pocl is.  If you want this change, please provide a benchmark showing otherwise.

**Comment by ZeroChaos-** [comment]
I did some testing and this seems safe.  Thanks for the testing

200b7a6e19ce6815b82985e806ede9c17cbf3c35
