### ISSUE TITLE
pentoo/pentoo-system: add pcmcia use flag

### ISSUE THREAD

**Issue by Bogdan107** [pentoo/pentoo-overlay#1086]
Gentoo portage system has predefined system-wide use flag **pcmcia** for users, which have physical _pcmcia-_ devices.

I have no `pcmcia` port in my laptop.
So I forced to have a troubles with install/remove `sys-apps/pcmciautils` package on each system update.

Please:
1) Add `pcmcia` word to the IUSE variable.
2) Modify `pentoo/pentoo-system` ebuild to use this flag.
From `sys-apps/pcmciautils` to `pcmcia? ( sys-apps/pcmciautils )`.

Those modifications allows to use system dependent options in the decision of package installing.

**Comment by Bogdan107** [comment]
/The same situation with system-wide use flag **subversion** and package `dev-vcs/subversion`.

**Comment by Bogdan107** [comment]
The same situation with system-wide use flag **radius** and package _net-dialup/freeradius_.

**Comment by blshkv** [comment]
done, fixed

**Comment by Bogdan107** [comment]
1. **pcmcia** use flag - is global use flag.
2. There are many lots in the stores of used goods (ThinkPad's with Core2Duo/i3/i5) in my land.
3. My friends still use 10+ years old high-end notebook with this port.

**Comment by ZeroChaos-** [comment]
I didn't remove the ability to set the use flag, I just don't force it on.  It makes sense to offer the option, it doesn't make sense to force it on.

**Comment by Bogdan107** [comment]
The same situation with `ieee1394` global use flag and `app-forensics/inception` package in `pentoo/pentoo-forensics` ebuild.

**Comment by Bogdan107** [comment]
`pentoo/pentoo-radio` requires `net-wireless/tempestsdr` and `net-wireless/uhd` packages.
`net-wireless/tempestsdr` requires `net-wireless/uhd` package.

Package `net-wireless/uhd` has 400+ Mb disk space.
A lot of pckages use **uhd** use flag in the same applying - for install `net-wireless/uhd` package.

Please, add **uhd** use flag into `pentoo/pentoo-radio` ebuild (for `net-wireless/tempestsdr` and `net-wireless/uhd` packages).

**Comment by ZeroChaos-** [comment]
please stop necromancing the same bug and open more so we can track things properly
