### ISSUE TITLE
pentoo/pentoo-radio: exactly-one-of ( bladerf hackrf ) for net-wireless/btle-sniffer

### ISSUE THREAD

**Issue by Bogdan107** [pentoo/pentoo-overlay#1087]
I set `USE="-bladerf -hackrf bluetooth"` globally.
System update prcess fails with an error:
```
!!! The ebuild selected to satisfy "net-wireless/btle-sniffer" has unmet requirements.
- net-wireless/btle-sniffer-0.2_p20200129::pentoo USE="-bladerf -hackrf"

  The following REQUIRED_USE flag constraints are unsatisfied:
    exactly-one-of ( bladerf hackrf )

(dependency required by "pentoo/pentoo-radio-2021.2::pentoo[bluetooth]" [ebuild])
(dependency required by "pentoo/pentoo-2015.1::pentoo[radio]" [ebuild])
(dependency required by "@local-aircrack" [set])
(dependency required by "@selected" [set])
(dependency required by "@world" [argument])
```
I have _bluetooth_ devices, but I do not have _hackrf_ or _bladerf_ device. So I have problem with `pentoo-radio` package...

Please, update ebuilds:
1) for `net-wireless/btle-sniffer`:
change DESCRIPTION variable to "Bluetooth radio packet sniffer/scanner and sender based on SDR";
2) for `pentoo/pentoo-radio`:
change PDEPEND variable from:
`bluetooth? ( net-wireless/btle-sniffer )`
to something like this:
```
bluetooth? (
        bladerf? ( net-wireless/btle-sniffer )
        hackrf? ( net-wireless/btle-sniffer )
        )
```

**Comment by ZeroChaos-** [comment]
fixed by ca86dfd03787de9e38cc98bd386ae1cdcc047681

thanks for the report
