### ISSUE TITLE
pentoo/pentoo-misc: switch off atm use flag

### ISSUE THREAD

**Issue by Bogdan107** [pentoo/pentoo-overlay#1088]
ATM - [Asynchronous Transfer Mode](http://linux-atm.sourceforge.net/) - is highly specialized technology.
ATM devices are very rare in general purpose usage.

Portage system has global `atm` use flag for that environment.
`pentoo/pentoo-misc` has switched on **+atm** use flag by default.

Please, change ebuild to switch off this flag by default.
Then, `pentoo-misc` package will use global settings about `atm` use flag.

**Comment by ZeroChaos-** [comment]
agreed

**Comment by Bogdan107** [comment]
The same situation with **+accessibility**.
Global use flag `accessibility` contoll this behaviour.
So, this use flag must be switched off by default.

**Comment by ZeroChaos-** [comment]
negative.  the accessibility use flag is on by default to help those who need it.  it's easy enough to disable for those who wish to.

**Comment by Bogdan107** [comment]
I think, that people, who really need accessibility in his PC - have this use flag switched on by default already BEFORE FIRST USAGE of PC. Another users may switch it on, if it is needs.

**Comment by ZeroChaos-** [comment]
I can switch it on from the pentoo profile is that suites you better?

**Comment by Bogdan107** [comment]
My goal is to get rid of unnecessary programs that are installed with FF package at the next system update.
I do not use pentoo profile - so this is not matter for me.

**Comment by ZeroChaos-** [comment]
done b1649eaea543e55604fa4f1883495eb888ae6263
