### ISSUE TITLE
net-analyzer/termshark-2.3.0: cannot find package "golang.org/x/tools/go/buildutil"

### ISSUE THREAD

**Issue by Bogdan107** [pentoo/pentoo-overlay#1092]
I have `net-analyzer/termshark-2.3.0` installed from `::pentoo` overlay.
But I can not to rebuild it due to the error:
```
src/golang.org/x/text/cmd/gotext/main.go:29:2: cannot find package "golang.org/x/tools/go/buildutil" in any of:
        /usr/lib/go/src/golang.org/x/tools/go/buildutil (from $GOROOT)
        /tmp/portage/dev-go/go-text-0.3.0/work/go-text-0.3.0/src/golang.org/x/tools/go/buildutil (from $GOPATH)
        /tmp/portage/dev-go/go-text-0.3.0/temp/golibdir/src/golang.org/x/tools/go/buildutil
src/golang.org/x/text/message/pipeline/extract.go:22:2: cannot find package "golang.org/x/tools/go/loader" in any of:
        /usr/lib/go/src/golang.org/x/tools/go/loader (from $GOROOT)
        /tmp/portage/dev-go/go-text-0.3.0/work/go-text-0.3.0/src/golang.org/x/tools/go/loader (from $GOPATH)
        /tmp/portage/dev-go/go-text-0.3.0/temp/golibdir/src/golang.org/x/tools/go/loader
```
If I have `termshark` installed, then `dev-go/go-text-0.3.0` package was compiled in my environment in the past.

At now, `dev-go/go-text-0.3.0` is masked in `::gentoo` overlay. For more info see [details](https://packages.gentoo.org/packages/dev-go/go-text).
This mask is because `go-text` package compilation fails inside the many installations.

Therefore, I can not to rebuild `termshark` from the source by ebuild from `::pentoo` overlay.

`dev-go/go-text` package required only for `termshark`. So no problem to remove it.

I rebuild `termshark` with this patch:
```
--- a/termshark-2.3.0.ebuild	2021-12-17 06:31:45.524944113 +0200
+++ b/termshark-2.3.0.ebuild	2021-12-20 01:13:48.790181542 +0200
@@ -63,6 +63,7 @@
 	"nhooyr.io/websocket v1.8.7 github.com/nhooyr/websocket"
 	"salsa.debian.org/vasudev/gospake2 adcc69dd31d5 salsa.debian.org/vasudev/gospake2/-/"
 	"salsa.debian.org/vasudev/ed25519group 3aff6cc605d469a7d618240e4a5cee3e1a861b43 salsa.debian.org/vasudev/ed25519group/-/"
+	"github.com/golang/text v0.3.0"
 )
 
 inherit golang-vcs-snapshot
@@ -79,7 +80,6 @@
 SLOT="0"
 
 RDEPEND="
-	dev-go/go-text:=
 	dev-go/go-tools:=
 	net-analyzer/wireshark[dumpcap,pcap,tshark]"
```

I do not use hash of library in the `github.com/golang/text v0.3.0` string, but I think, that this hash is strictly required for public ebuild.

Please, update ebuild.

**Comment by Bogdan107** [comment]
Compilation success with latest go-text version `v0.3.7`.

**Comment by blshkv** [comment]
Can you please try that commit? It seems like go-text is not required

**Comment by Bogdan107** [comment]
Compilation finished success. Binary file works fine.
