### ISSUE TITLE
encfs-cracker

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#110]
https://github.com/kholia/encfs-cracker
password cracker for encfs.

**Comment by blshkv** [comment]
The project is dead, and there is no stable release

**Comment by necrose99** [comment]
nuts nevermind ... 
found a few others , might be more of use ... 
but if doing an audit crappy encfs passwords might be good to find and smack the user square over the head. 
, https://git.adrian.kousz.ch/adrian/encfs-bruteforce/src/master/src/ch/kousz/adrian this is more recent 
trys to guess or bruteforce passwords. 
https://seafile.adrian.kousz.ch/d/0ab0eb513e/files/?p=/encfs-bruteforce.jar 
https://gist.github.com/Finkregh/4864521a29a3fa204dc9

**Comment by blshkv** [comment]
grab encfs6.xml, convert to jtr format using https://fossies.org/dox/john-1.8.0-jumbo-1/encfs2john_8py_source.html and crack it. There is no need in an additional tool
