### ISSUE TITLE
net-wireless/cowpatty : capture file read error

### ISSUE THREAD

**Issue by RockyBukake** [pentoo/pentoo-overlay#1102]
The current version of coWPAtty does not work, it displays `End of pcap capture file, incomplete four-way handshake exchange.  Try using a different capture` for valid files, kimocoder's [fork](https://github.com/kimocoder/cowpatty) seems to fix this issue.

**Comment by blshkv** [comment]
Sounds like an upstream bug

**Comment by blshkv** [comment]
There are 3 commits in that fork (https://github.com/kimocoder/cowpatty/commits/master):
https://github.com/kimocoder/cowpatty/commit/8eedd1f056832af2a30f5f56fd7f3603a4b88517
https://github.com/kimocoder/cowpatty/commit/e539f17985b053cea874bbd14e6b1fe4e449704b
https://github.com/kimocoder/cowpatty/commit/a7f565124e7f4bec74d3b30a6da96fbbe39cb88a

Each seems "cosmetic" change. Can you test and let me know which one fixes your issue?

**Comment by RockyBukake** [comment]
Hi, did a bit of testing, it appears that this commit https://github.com/joswr1ght/cowpatty/commit/0b8548b5cedfbf5625b49923d08b66685a30bc8d fixed that issue

**Comment by ZeroChaos-** [comment]
Thanks, I will make an updated snapshot release from the original repo

**Comment by blshkv** [comment]
the 4.8 release was on 4th July 2018, the patch was merged two days later.
No wonder we don't have that patch.

The highlighted fork seems dead, so we can just use to the latest commit.
