### ISSUE TITLE
gcc-arm-none-eabi-11.2_p202202-r1 broken?

### ISSUE THREAD

**Issue by ZeroChaos-** [pentoo/pentoo-overlay#1104]
11.2 installs like this:
```
zero@theprophet gcc-arm-none-eabi % ls /opt/gcc-arm-none-eabi/bin                                                                                            (git)-[master] 
aarch64-none-linux-gnu-addr2line*  aarch64-none-linux-gnu-gcc*         aarch64-none-linux-gnu-gdb-add-index*  aarch64-none-linux-gnu-objdump*
aarch64-none-linux-gnu-ar*         aarch64-none-linux-gnu-gcc-11.2.1*  aarch64-none-linux-gnu-gfortran*       aarch64-none-linux-gnu-ranlib*
aarch64-none-linux-gnu-as*         aarch64-none-linux-gnu-gcc-ar*      aarch64-none-linux-gnu-gprof*          aarch64-none-linux-gnu-readelf*
aarch64-none-linux-gnu-c++*        aarch64-none-linux-gnu-gcc-nm*      aarch64-none-linux-gnu-ld*             aarch64-none-linux-gnu-size*
aarch64-none-linux-gnu-c++filt*    aarch64-none-linux-gnu-gcc-ranlib*  aarch64-none-linux-gnu-ld.bfd*         aarch64-none-linux-gnu-strings*
aarch64-none-linux-gnu-cpp*        aarch64-none-linux-gnu-gcov*        aarch64-none-linux-gnu-ld.gold*        aarch64-none-linux-gnu-strip*
aarch64-none-linux-gnu-dwp*        aarch64-none-linux-gnu-gcov-dump*   aarch64-none-linux-gnu-lto-dump*
aarch64-none-linux-gnu-elfedit*    aarch64-none-linux-gnu-gcov-tool*   aarch64-none-linux-gnu-nm*
aarch64-none-linux-gnu-g++*        aarch64-none-linux-gnu-gdb*         aarch64-none-linux-gnu-objcopy*
```
but 10.3 installs like this:
```
zero@theprophet gcc-arm-none-eabi % ls /opt/gcc-arm-none-eabi/bin                                                                                            (git)-[master] 
arm-none-eabi-addr2line*  arm-none-eabi-elfedit*     arm-none-eabi-gcc-ranlib*     arm-none-eabi-gdb-add-index-py*  arm-none-eabi-objcopy*  arm-none-eabi-strip*
arm-none-eabi-ar*         arm-none-eabi-g++*         arm-none-eabi-gcov*           arm-none-eabi-gprof*             arm-none-eabi-objdump*
arm-none-eabi-as*         arm-none-eabi-gcc*         arm-none-eabi-gcov-dump*      arm-none-eabi-ld*                arm-none-eabi-ranlib*
arm-none-eabi-c++*        arm-none-eabi-gcc-10.3.1*  arm-none-eabi-gcov-tool*      arm-none-eabi-ld.bfd*            arm-none-eabi-readelf*
arm-none-eabi-c++filt*    arm-none-eabi-gcc-ar*      arm-none-eabi-gdb*            arm-none-eabi-lto-dump*          arm-none-eabi-size*
arm-none-eabi-cpp*        arm-none-eabi-gcc-nm*      arm-none-eabi-gdb-add-index*  arm-none-eabi-nm*                arm-none-eabi-strings*
```

These are completely different compilers, one is for arm and one is for aarch64?

**Comment by blshkv** [comment]
Does it work?
They come out with new names and multiple new options which I don't understand completely

**Comment by ZeroChaos-** [comment]
this package is called gcc-arm-none-eabi, it's meant to install a compiler for gcc-arm-none-eabi but your new version installs a compiler for gcc-aarch64-none-eabi.  it's the wrong compiler.

**Comment by blshkv** [comment]
Feel free to test if it works and change to the correct one

**Comment by ZeroChaos-** [comment]
It sure would be nice if you tested it before committing.  I have already fixed the ebuild failure due to use flag not in iuse, and the revdep-rebuild issue.  Need me to wipe too?

**Comment by blshkv** [comment]
I copied previous ebuild. If you fixed something  , it must have been there forever .
You are welcome to fix anything else too

**Comment by ZeroChaos-** [comment]
You changed the use python2 to use pythons without adjusting iuse.  Since you are so anxious to avoid any responsibility for your own actions I will take care of this for you.

**Comment by blshkv** [comment]
yeap, my bad. 
The new name of all binaries is "aarch64-xxx" even under amd64, but it works fine. Dont look at me ;-)
Open the bug report if it doesn't work.

**Comment by ZeroChaos-** [comment]
I did open a bug, you closed it with no testing

**Comment by blshkv** [comment]
you need to learn how to file a bug report. Provide logs and an error.
The bug is invalid

**Comment by ZeroChaos-** [comment]
You see how on your computer you have '/usr/bin/x86_64-pc-linux-gnu-g++-11.2.1' installed?  that's the g++ compiler for the x86_64 target.

I showed in the first comment how you are installing the aarch64 compiler instead of the arm compiler.

**Comment by blshkv** [comment]
You will be surprised if you visit arm.com,
They called gcc-arm-11.2-2022.02-x86_64-aarch64-none-linux-gnu binary for amd64, and it works.
I showed it earlier too.

**Comment by ZeroChaos-** [comment]
And the right one was called "AArch32 bare-metal target (arm-none-eabi)"

**Comment by blshkv** [comment]
thanks! You might also want to get arm64 binary back (a correct binary)

**Comment by ZeroChaos-** [comment]
can't aarch64 already compile for arm?  that seems like something we shouldn't need....

**Comment by blshkv** [comment]
Hm.. have no idea, but it was there before.

**Comment by blshkv** [comment]
btw, if you follow the same logic, "aarch64-none-linux-gnu" binary (which you did not like) should work too ;-)
