### ISSUE TITLE
dev-util/lief-0.12.1 fails to compile: hangs 

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1133]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-util/lief-0.12.1 fails to compile.
Discovered on: amd64 (internal ref: pentoo_tinderbox)

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/a151051b7773c6125fe1d4888b4656e9

**Comment by blshkv** [comment]
I guess this is a false positive. You managed to compile and reported other issues:
https://github.com/pentoo/pentoo-overlay/issues/1006
https://github.com/pentoo/pentoo-overlay/issues/1007
