### ISSUE TITLE
net-analyzer/xplico-1.2.2 fails to compile: tcp_garbage.c:128:17: error: too many arguments to function ndpi_detection_process_packet 

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1136]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: net-analyzer/xplico-1.2.2 fails to compile.
Discovered on: amd64 (internal ref: pentoo_tinderbox)

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/ee4cb2952f87bf901cfedda87247300d

**Comment by blshkv** [comment]
b0df2bb05a7b8cec91741bec80bdfbcb2e31099d
