### ISSUE TITLE
net-analyzer/pwncat-0.1.2 fails to compile: error: Multiple top-level packages discovered in a flat-layout: [pse, man, art, share] 

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1141]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: net-analyzer/pwncat-0.1.2 fails to compile.
Discovered on: amd64 (internal ref: pentoo_tinderbox)

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/2d9cf595c6747c8f6b077d79cea373d8

**Comment by blshkv** [comment]
https://github.com/cytopia/pwncat/issues/113
