### ISSUE TITLE
2016-08-11-grub2_multislot_default vs. pentoo/pentoo-system-2016.3-r4

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#116]
I tried uninstalling grub and using only grub2, but it seems both are required by this dependency clause (pentoo-system-2016.3-r4.ebuild)?

        !arm? ( !livecd-stage1? ( sys-kernel/genkernel
                || ( sys-boot/grub:0 sys-boot/grub-static )
                sys-boot/grub:2 ) )

$ emerge -uDN world
...
Total: 19 packages (14 upgrades, 2 new, 1 in new slot, 2 reinstalls), Size of do
wnloads: 0 KiB
Conflict: 1 block (1 unsatisfied)

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (sys-boot/grub-0.97-r16:0/0::gentoo, ebuild scheduled for merge) pulled in by
    sys-boot/grub:0 required by (pentoo/pentoo-system-2016.3-r4:0/0::pentoo, ins
talled)

  (sys-boot/grub-2.02_beta2-r9:2/2.02_beta2-r9::gentoo, ebuild scheduled for mer
ge) pulled in by
    sys-boot/grub required by @selected
    sys-boot/grub:2 required by (pentoo/pentoo-system-2016.3-r4:0/0::pentoo, ins
talled)

**Comment by blshkv** [comment]
you might have sys-boot/grub in the world file (/var/lib/portage/world)
