### ISSUE TITLE
net-dialup/freeradius-3.0.21-r3 installs shared libraries that lack a SONAME

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1161]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: net-dialup/freeradius-3.0.21-r3 installs shared libraries that lack a SONAME.
Discovered on: amd64 (internal ref: pentoo_tinderbox)

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/0b0765b0d2cb9a4d275581019d37a6dc

**Comment by blshkv** [comment]
seems fixed in 3.2.0. Cheers
