### ISSUE TITLE
Add stable keywords for arm64

### ISSUE THREAD

**Issue by GavinDarkglider** [pentoo/pentoo-overlay#1164]
I am trying to add pentoo packages, using pentoo metapackages to my gentoo build, on my nintendo switch, and for some reason, none of the meta pacakages, and half of the other packages are missing stable arm64 keywords, so it is quite a pain in the ass to install things using pentoo meta-packages, without having to make a ton of modifications to both packages in the repo, and to my switch profile's package.accept_keywords. This should be mitigated though out the tree, by adding stable arm64 keywords to packages in the pentoo tree.

**Comment by ZeroChaos-** [comment]
This would require testing, testing which I presently lack the ability to do.  I can't just "add stable keywords", keywords mean something.

**Comment by GavinDarkglider** [comment]
I understand keywords mean something...... Been running gentoo, with your packages backing it for years..... Thank you by the way...... It is just annoying as gentoo changed the way keywords were used about 2 years ago, and they havnt even finished fixing their own repo..... lol. I digress though, I will work out the needed changes, and send you a PR. Even unstable arm64 keywords are better than no arm64 keywords at all.... and any 9999 package with KEYWORDS="" in it causes problems since they made that change to portage upstream.
