### ISSUE TITLE
app-admin/opensnitch needs more kernel configs

### ISSUE THREAD

**Issue by emdee-is** [pentoo/pentoo-overlay#1169]
I think you need these to build the debugfs to use ebpf
https://github.com/evilsocket/opensnitch/tree/master/ebpf_prog

CONFIG_KPROBES=y                                                                
CONFIG_KPROBE_EVENTS=y                                                          

Or are these better as a debugfs kernel use flag?                       
If debugfs is used elsewhere then maybe that's a good idea...

**Comment by blshkv** [comment]
opensnitch is a bit of mess. By right, it should be 3 separate packages: a kernel module, daemon and UI.
It's hard to implement all that in one ebuild.
I'll open a bug report requesting to split it.

**Comment by emdee-is** [comment]
I think you need more according to the (out of date) ebpf_prog page:

CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_EVENTS=y

I couldn't get them to update their documentation:
https://github.com/evilsocket/opensnitch/issues/716
