### ISSUE TITLE
dev-ruby/parseconfig No Rakefile

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#12]
Hi ppl, well here a little isuue compiling with doc flag:

 * Package:    dev-ruby/parseconfig-1.0.2
 * Repository: pentoo
 * USE:        abi_x86_64 amd64 doc elibc_glibc kernel_linux pie ruby_targets_ruby19 ssp userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Running unpack phase for all ...
 * Unpacking .gem file... ...
 [ ok ]
 * Uncompressing metadata ...
 [ ok ]
 * Unpacking data.tar.gz ...
 [ ok ]
>>> Source unpacked in /var/tmp/portage/dev-ruby/parseconfig-1.0.2/work
>>> Preparing source in /var/tmp/portage/dev-ruby/parseconfig-1.0.2/work ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby19 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-ruby/parseconfig-1.0.2/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-ruby/parseconfig-1.0.2/work ...
 * Running compile phase for all ...
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

**Comment by blshkv** [comment]
fixed in the commit 812817d11d9577bfcf1f8276412867cd74fe4d7b
thanks
