### ISSUE TITLE
dev-util/unicorn fails to merge with fatal error: uc_priv.h: No such file or directory

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#120]
build.log, emerge --info, emerge -pqv, and environment info are attached as files.zip

Error seen:
...
make[1]: Entering directory '/mnt/disk-image4/portage/dev-util/unicorn-0.9_p20160901/work/unicorn-0.9_p20160901'
cc -O2 -pipe -g -g   -c -o uc.o uc.c
uc.c:19:21: fatal error: uc_priv.h: No such file or directory
[files.zip](https://github.com/pentoo/pentoo-overlay/files/447498/files.zip)

 #include "uc_priv.h"
...
cc -O2 -pipe -g -g   -c -o list.o list.c
list.c:3:18: fatal error: list.h: No such file or directory
 #include "list.h"
                  ^
compilation terminated.
<builtin>: recipe for target 'list.o' failed
make[1]: *** [list.o] Error 1
make[1]: *** Waiting for unfinished jobs....
uc.c:19:21: fatal error: uc_priv.h: No such file or directory
 #include "uc_priv.h"
                     ^
compilation terminated.
<builtin>: recipe for target 'uc.o' failed
make[1]: *** [uc.o] Error 1
make[1]: Leaving directory '/mnt/disk-image4/portage/dev-util/unicorn-0.9_p20160901/work/unicorn-0.9_p20160901'
Makefile:238: recipe for target 'compile_lib' failed
make: *** [compile_lib] Error 2
 * ERROR: dev-util/unicorn-0.9_p20160901::pentoo failed (install phase):
 *   emake failed

**Comment by blshkv** [comment]
You have to specify at least one target in UNICORN_TARGETS. The ebuild should check for it

**Comment by blshkv** [comment]
I tried to force it but made a typo. It's all fixed now. Thanks!
