### ISSUE TITLE
Package files are amd64-keyword specific

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#123]
Believe it or not, I'm still building (occasionally) some Pentoo things on an x86 system.  I just happened to notice these amd64 specific keywords. I haven't had a problem (that I know of), but it may be worth making more generic?  In the case of firmware, I suppose it's intentional...

/var/lib/layman/pentoo/profiles/pentoo/base/package.accept_keywords/dev-ruby:~dev-ruby/loofah-2.0.3 ~amd64
/var/lib/layman/pentoo/profiles/pentoo/base/package.accept_keywords/dev-util:dev-util/jenkins-bin ~amd64
/var/lib/layman/pentoo/profiles/pentoo/base/package.accept_keywords/net-wireles :~net-wireless/mfoc-0.10.7 ~amd64
/var/lib/layman/pentoo/profiles/pentoo/base/package.accept_keywords/net-wireles :net-wireless/acx-firmware amd64

**Comment by ZeroChaos-** [comment]
it's all intentional

**Comment by blshkv** [comment]
I've looked at the list, some packages such as loofah or mfoc have 1 version only. That means that you should see them either blocked or not installed on x86.

Please report if any problem, we will review it.
