### ISSUE TITLE
new tool: usbguard

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-overlay#124]
https://dkopecek.github.io/usbguard/

**Comment by lramage94** [comment]
# Installation

> Gentoo
> For Gentoo you can use the stuge overlay via layman:

> $ layman -a stuge-overlay
> $ emerge -av usbguard

https://usbguard.github.io/documentation/compilation

## Gentoo Bugzilla

Currently open bugs

- [sys-apps/usbguard-0.7.0::das-labor with systemd: usbguard.service does not exist](https://bugs.gentoo.org/622132)

**Comment by blshkv** [comment]
@lramage94 thanks but your data is outdated probably.  stuge-overlay is **not** in laman xml list (https://api.gentoo.org/overlays/repositories.xml) and the usbguard is **not** in that overlay (https://github.com/zaolin/stuge-overlay).

However, the ebuild can be found in other overlay, see http://gpo.zugaina.org/sys-apps/usbguard

**Comment by lramage94** [comment]
Oh there it is!

https://github.com/das-labor/overlay/tree/master/sys-apps/usbguard

The usbguard documentation is out of date.

**Comment by blshkv** [comment]
yeah, I took that ebuild and .. re-wrote it because it was badly written.
