### ISSUE TITLE
I may have a clue about why edb-0.9.20_p20160928.ebuild failes, but not the live, git-cloned version.

### ISSUE THREAD

**Issue by Petross404** [pentoo/pentoo-overlay#125]
@ZeroChaos-  I downloaded the .zip of the repo at this last* commit. Guess what. CMake failed.
*(2a9d49f79ce225e7bb487e22315af192480d7130)

I cloned the repo (at the very same commit) with 
`git clone **--recursive** git@github.com:eteran/edb-debugger.git` 
and noticed this line in the output:
`...**Submodule path 'src/qjson4': checked out '29137534177babc1706e0735a09a2bf8e733bea2'**`

CMake failed like : 
`CMake Error at src/CMakeLists.txt:197 (add_executable):
  Cannot find source file:
    qjson4/QJsonArray.h`

Evan warned : When cloning the repo, please use git's --recursive flag to _ensure that the sub-modules will be properly cloned_ and updated to the correct versions. So when we download the ${number_of_commit}.zip we are clearly missing something big here. Didn't you wondered, why the very same sources compile fine when cloned with git as live (9999) package? 

I might be wrong, but this fact got me in to thinking. Should we use git-r3 and the commit number in the snapshot ebuild? Is it possible to have a non-live ebuild, clone sources with git at a specific commit?

**Comment by blshkv** [comment]
Please post the ebuild with an initial  command and the error

**Comment by blshkv** [comment]
we dont provide edb-0.9.20_p20160928 ebuild. So it looks like you either copied it from another overlay or trying to create it yourself. This is not our bug.

**Comment by Petross404** [comment]
https://github.com/pentoo/pentoo-overlay/blob/master/dev-util/edb/edb-0.9.20_p20160928.ebuild

Here you are. The actual cmake error is shown above, but for the moment I haven't access to the full build.log as I am on a different pc. Should I post it as soon as I log in to my pc?

**Comment by Petross404** [comment]
Never mind. EDB-0.9.21 is released and containes every submodule needed for proper compilation.

**Comment by blshkv** [comment]
My fault I did not expect a bug report in an hour after ZC submitted a broken ebuild :]
I'll bump to the latest

**Comment by blshkv** [comment]
FYI, I've compared the latest and 20160928 directories. There are number of differences. One of relevant change might be an src.pro file which includes qjson4 path. So you might be just bumped a broken commit.

**Comment by Petross404** [comment]
Actually I don't think it's the ebuilds fault. I guess the .zip file didn't include all the necessary submodules. ZC did good with the ebuild.

As I already wrote, there is a new proper release which fixes that. I know there are differences, I 've already checked that. :-)

**Comment by blshkv** [comment]
ebuild is pulling a broken commit. ZC didn't test it :] There are no missing submodules and it has nothing to do with recursive pulling

**Comment by Petross404** [comment]
Weird. The same commit compiled without problem when git was used. Either manually, either within the (live) ebuild.

The devil is in the details, they say. Who knows why the very same commit (should be **exactly** the same files) didn't compile in one case. Correct me if I am wrong. :-)

**Comment by blshkv** [comment]
Some follow up in https://github.com/eteran/edb-debugger/issues/450 , feel free to monitor.

**Comment by Petross404** [comment]
EDB now is built against Qt5, not 4. Could you fix the dependencies?

**Comment by blshkv** [comment]
ok, but it looks like it supports both, so it's better not to remove 4

**Comment by Petross404** [comment]
Could we use a slot or something? I mean the user must have the choise to either build it with qt4 or qt5.

This has to be done with cmake options?

**Comment by blshkv** [comment]
ZC said "Nah" and overwrote it with -DQT_VERSION=Qt5 cmake option. qt5 is stable, let's move on.
