### ISSUE TITLE
net-analyzer/metasploit-6.0.50 requires unsupported version of Ruby

### ISSUE THREAD

**Issue by Thymelizabeth** [pentoo/pentoo-overlay#1257]
When trying to install Metasploit-6.0.50, it requires the USE flag RUBY_TARGETS_RUBY26. Ruby 2.6 has been masked in the Gentoo repository, and will be removed on 2022-08-15. None of the other versions of Metasploit available in the Pentoo repository have keywords for ~amd64.

**Comment by alsotoes** [comment]
Hey @ZeroChaos- 
This Issue can be closed as of commit 5f42e2cda9f652c56150e37040072492680e625e fixed this.

https://github.com/pentoo/pentoo-overlay/commit/5f42e2cda9f652c56150e37040072492680e625e
