### ISSUE TITLE
sys-kernel/pentoo-sources bestkern is not in Available versions:

### ISSUE THREAD

**Issue by emdee-is** [pentoo/pentoo-overlay#1262]
latest sys-kernel/pentoo-sources that is bestkern in scripts/pentoo-updater.sh is not in Available versions:

[U?] sys-kernel/pentoo-sources [1]
     Available versions:  
     (5.15.44) 5.15.44^bs
     (5.18.13) 5.18.13^bs
       {build experimental +lts pax-kernel symlink}

Am I missing something here?

Is bestkern always a USE=lts version? I think that would be nice.

**Comment by ZeroChaos-** [comment]
With no output from pentoo-updater I can't say much here except that bestkern is best available kernel, as in the one we want to update to. eselect only shows installed kernels.

**Comment by emdee-is** [comment]
Why not look in pentoo-updater.sh - #L226 instead of  just closing issues without looking?

```
update_kernel() {
  #bigger updates can fail, so make sure at least all this stuff is up to date          
  emerge --update virtual/linux-sources sys-kernel/genkernel sys-kernel/linux-firmware \
sys-firmware/intel-microcode --oneshot || safe_exit
  bestkern="$(qlist $(portageq best_version / pentoo-sources 2> /dev/null) | grep 'dist\
ro/Kconfig' | awk -F'/' '{print $4}' | cut -d'-' -f 2-)"
  bestkern_pv="$(portageq best_version / pentoo-sources | cut -d'-' -f 4-)"
 ```

pentoo-updater.sh wants 5.15.26, which is not in the list of available versions. @blshkv won't that break pentoo-updater.sh update_kernel()?

Please reopen and let someone deal with the issue.

**Comment by ZeroChaos-** [comment]
Still no useful bug report, but at least you added rudeness

**Comment by blshkv** [comment]
@emdee-is I tested that code and it works fine. As ZC said, run ```eselect kernel list``` and you will see your 5.15.26, probably.
So something must be gone wrong before that. Try to investigate and provide a solution. Or provide logs/ outputs so it would be possible to understand and reproduce the problem.
