### ISSUE TITLE
app-forensics/inception - PYTHON_COMPAT

### ISSUE THREAD

**Issue by ostree** [pentoo/pentoo-overlay#128]
Hello,
there seams to be something missing:

ERROR: app-forensics/inception-0.4.0::pentoo failed (depend phase):
 *   No supported implementation in PYTHON_COMPAT

I have updated all inception ebuilds in my local overlay to:
PYTHON_COMPAT=( python3_{2,3,4} )

is this sufficient step?

regards

**Comment by blshkv** [comment]
yeap, done. Thanks!
