### ISSUE TITLE
new tool: powershell empire

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-overlay#129]
https://github.com/adaptivethreat/Empire

**Comment by gkroon** [comment]
I drafted some ebuilds for empire and its dependencies over at my [ebuild-factory](https://github.com/gkroon/ebuild-factory). At the moment I'm still stuck at getting [dropbox-sdk](https://github.com/gkroon/ebuild-factory/tree/master/dev-python/dropbox-sdk) to install properly. I left a [README.md](https://github.com/gkroon/ebuild-factory/blob/master/dev-python/dropbox-sdk/README.md) file in its directory with some more details as to why it fails, but I don't know how to resolve it yet.

Help is also welcome, of course.

**Comment by gkroon** [comment]
I drafted some ebuilds for empire and its dependencies over at my [fork/empire](https://github.com/gkroon/pentoo-overlay) branch. At the moment I'm still stuck at getting dropbox-sdk to install properly. I left a [README.md](https://github.com/gkroon/pentoo-overlay/blob/empire/dev-python/dropbox-sdk/README.md) file in its directory with some more details as to why it fails, but I don't know how to resolve it yet.

Help is also welcome, of course.
