### ISSUE TITLE
app-crypt/johntheripper fails to emerge with error: 'is_sha512' undeclared

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#130]
From build.log:
truecrypt_fmt_plug.c:313:7: error: 'is_sha512' undeclared (first use in this function)

[files.zip](https://github.com/pentoo/pentoo-overlay/files/573177/files.zip)

**Comment by bill-e-ghote** [comment]
This is on ~x86 not ~amd64, by the way.  JtR builds just fine on ~amd64.

**Comment by blshkv** [comment]
Can you try to apply the upstream patch?
https://github.com/magnumripper/JohnTheRipper/commit/480e95b0e449863be3e1a5b0bc634a67df28b618

**Comment by blshkv** [comment]
feel free to re-open if it does not fix the issue
