### ISSUE TITLE
app-crypt/johntheripper-1.8.0-r1 fails to build under sys-devel/gcc-5

### ISSUE THREAD

**Issue by ikelos** [pentoo/pentoo-overlay#136]
Hi there,

Johntheripper-1.8.0-r1 with gcc-5 fails to build with the following messages:

`/var/tmp/portage/app-crypt/johntheripper-1.8.0-r1/work/john-1.8.0-jumbo-1/src/dynamic_fmt.c:4989: undefined reference to `MD5_body_for_thread'
dynamic_fmt.o: In function `DynamicFunc__crypt_md5':
/var/tmp/portage/app-crypt/johntheripper-1.8.0-r1/work/john-1.8.0-jumbo-1/src/dynamic_fmt.c:4425: undefined reference to `MD5_body_for_thread'
dynamic_fmt.o: In function `DynamicFunc__crypt_md5_in1_to_out2':
/var/tmp/portage/app-crypt/johntheripper-1.8.0-r1/work/john-1.8.0-jumbo-1/src/dynamic_fmt.c:4732: undefined reference to `MD5_body_for_thread'
dynamic_fmt.o: In function `DynamicFunc__crypt_md5_to_input_raw':
/var/tmp/portage/app-crypt/johntheripper-1.8.0-r1/work/john-1.8.0-jumbo-1/src/dynamic_fmt.c:4903: undefined reference to `MD5_body_for_thread'
dynamic_fmt.o: In function `DynamicFunc__crypt_md5_to_input_raw_Overwrite_NoLen_but_setlen_in_SSE':
/var/tmp/portage/app-crypt/johntheripper-1.8.0-r1/work/john-1.8.0-jumbo-1/src/dynamic_fmt.c:4946: undefined reference to `MD5_body_for_thread'
dynamic_fmt.o:/var/tmp/portage/app-crypt/johntheripper-1.8.0-r1/work/john-1.8.0-jumbo-1/src/dynamic_fmt.c:4817: more undefined references to `MD5_body_for_thread' follow
`

This can be fixed by applying [e2e868db](https://github.com/magnumripper/JohnTheRipper/commit/e2e868db3e153b3f959e119a51703d4afb99c624) from Johntheripper's upstream.  Unfortunately, johntheripper's ebuild EAPI is less than 6 and it doesn't apply user_patches explicitly, so it would be good if this could be fixed at the same time...

**Comment by blshkv** [comment]
fixed, thank you
