### ISSUE TITLE
app-crypt/johntheripper-1.8.0-r1 dies in src_install due to failed pax-mark

### ISSUE THREAD

**Issue by ikelos** [pentoo/pentoo-overlay#137]
Johntheripper's src_install forces die after a failed pax-mark call:

`pax-mark -mr "${ED}usr/sbin/john" || die`

This means that anyone building portage packages on mainline kernels (that don't include the gentoo-sources patch to allow xattrs on tmpfs) under a tmpfs, will die and prevent the ebuild installing, even though the mainline kernels do not support PAX.  The package can be rebuilt on a normal filesystem, but the error messages provide no indication that this is necessary.

The best discussion I could find about on this matter is [here](http://www.gossamer-threads.com/lists/gentoo/dev/307423).  The conclusion seems to be that the error messages can be ignored, so calling die incorrectly prevents this package from building on any such systems.

**Comment by blshkv** [comment]
See also https://bugs.gentoo.org/show_bug.cgi?id=564328

I'll have a look at ebuild tomorrow

**Comment by blshkv** [comment]
no idea why I didn't fix it before. So I have just removed it. pax-mark should die on its own if necessary. The proper fix should be done in the bug 564328
