### ISSUE TITLE
arachni is dated

### ISSUE THREAD

**Issue by ZeroChaos-** [pentoo/pentoo-overlay#138]
https://github.com/Arachni/arachni/issues/809

This is preventing livecd build so for now I'm dropping it from pentoo-scanner.

If you can remove all the deps from your machine and install arachni then please re-add it to pentoo-scanner but the deps appear to be more than a little broken right now.

**Comment by blshkv** [comment]
Provide more info

**Comment by blshkv** [comment]
fixed in 231e50d3d586b9d92e4d2809ef9ac8aebe8f013a

**Comment by blshkv** [comment]
As discussed, I have fixed one dep and unable magically find what's broken for you. Please provide more details

**Comment by blshkv** [comment]
https://github.com/Arachni/arachni/releases
Arachni Framework v1.5.1 & WebUI v0.5.12
@Zapotek Zapotek released this on Mar 29

**Comment by blshkv** [comment]
Closing since no news from the reporter
