### ISSUE TITLE
dev-java/jetty-server-11.0.9 fails to compile (CLANG-STRICTER-SYSTEM): !!! ERROR: Package jakarta-servlet-api was not found! 

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1387]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-java/jetty-server-11.0.9 fails to compile (CLANG-STRICTER-SYSTEM).
Discovered on: amd64 (internal ref: pentoo_tinderbox)

NOTE:
(CLANG-STRICTER-SYSTEM) in the summary means that the bug was found on a machine that runs clang with stricter mode

This machine uses clang with CFLAGS/CXXFLAGS=-Werror=implicit-function-declaration -Werror=implicit-int -Werror=incompatible-function-pointer-types

See also:
https://archives.gentoo.org/gentoo-dev/message/dd9f2d3082b8b6f8dfbccb0639e6e240
https://wiki.gentoo.org/wiki/Modern_C_porting

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/af1fcbf7846e9c15b212982fd6bead48

**Comment by blshkv** [comment]
seems fine now
