### ISSUE TITLE
dev-ruby/ansi No Rakefile

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#14]
Hi here other with doc use.

>>> Source unpacked in /var/tmp/portage/dev-ruby/ansi-1.4.3/work
>>> Preparing source in /var/tmp/portage/dev-ruby/ansi-1.4.3/work ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby19 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-ruby/ansi-1.4.3/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-ruby/ansi-1.4.3/work ...
 * Running compile phase for all ...
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

**Comment by blshkv** [comment]
Fixed in the commit 371f417cdc1cece71f372c0e4419370e4c739fe6. There is a better version in the main tree.
