### ISSUE TITLE
dev-util/jd-gui-bin-1.6.6 installs .desktop files that do not pass validation

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1409]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-util/jd-gui-bin-1.6.6 installs .desktop files that do not pass validation.
Discovered on: amd64 (internal ref: pentoo_tinderbox)

NOTE:
(CLANG-STRICTER-SYSTEM) in the summary means that the bug was found on a machine that runs clang with stricter mode

This machine uses clang with CFLAGS/CXXFLAGS=-Werror=implicit-function-declaration -Werror=implicit-int -Werror=incompatible-function-pointer-types

See also:
https://archives.gentoo.org/gentoo-dev/message/dd9f2d3082b8b6f8dfbccb0639e6e240
https://wiki.gentoo.org/wiki/Modern_C_porting

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/ff2838ee53b4e9bb33874452f05f56f9

**Comment by blshkv** [comment]
can you double check please? I'm unable to reproduce. Also, the following command does not report any issues:
```desktop-file-validate jd-gui.desktop```
