### ISSUE TITLE
missed jeweler in dev-ruby/dm-timestamps and dev-ruby/dm-validations with doc use

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#141]
Hi all, well basically is missed this dpends in this two packages.

```
>>> Configuring source in /var/tmp/portage/dev-ruby/dm-validations-1.2.0/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-ruby/dm-validations-1.2.0/work ...
 * Running compile phase for all ...
Jeweler (or a dependency) not available. Install it with: gem install jeweler -v 1.6.4
```

i get this message in the two packages.

Thx. Cya.

**Comment by latot** [comment]
same dev-ruby/dm-migrations

**Comment by blshkv** [comment]
This is basically the bug https://github.com/pentoo/pentoo-overlay/issues/37 :nerd_face:

**Comment by blshkv** [comment]
According to https://rubygems.org/gems/dm-timestamps/versions/1.2.0, jeweler is a development dependency. However, there are no gentoo packages which would require it. See rb-inotify for example:
```
# Avoid unneeded dependency on jeweler
```
So it looks like that you want to patch Rakefile and remove this dep.

Feel free to test it and create a pull request if you have time.

**Comment by latot** [comment]
Okidokis, Thx!
