### ISSUE TITLE
net-wireless/broadcom-firmware-downloader-0.2 sandbox violation

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1413]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: net-wireless/broadcom-firmware-downloader-0.2 sandbox violation.
Discovered on: amd64 (internal ref: pentoo_tinderbox)

NOTE:
(CLANG-STRICTER-SYSTEM) in the summary means that the bug was found on a machine that runs clang with stricter mode

This machine uses clang with CFLAGS/CXXFLAGS=-Werror=implicit-function-declaration -Werror=implicit-int -Werror=incompatible-function-pointer-types

See also:
https://archives.gentoo.org/gentoo-dev/message/dd9f2d3082b8b6f8dfbccb0639e6e240
https://wiki.gentoo.org/wiki/Modern_C_porting

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/cd198affb39b6ca063f5b289b3b24468
Context of error(s): https://gist.github.com/62538c36cabae3658d1de6d4cbdbc6cf
1-sandbox.log: https://gist.github.com/6aab985a701d4d7a6da08baa41aabf4f

**Comment by ZeroChaos-** [comment]
this ebuild was old trash, removed.  thanks for the report
