### ISSUE TITLE
bump wireshark-sap-plugin to v0.4.1

### ISSUE THREAD

**Issue by martingalloar** [pentoo/pentoo-overlay#143]
The latest [v0.4.1 release](https://github.com/CoreSecurity/SAP-Dissection-plug-in-for-Wireshark/releases/tag/v0.4.1) of the [Wireshark SAP plugin](https://github.com/CoreSecurity/SAP-Dissection-plug-in-for-Wireshark) now works with the Wireshark 2.2 branch, it should be safe now to use that tag and point [live](https://github.com/pentoo/pentoo-overlay/blob/master/net-misc/wireshark-sap-plugin/wireshark-sap-plugin-9999.ebuild) to [master](https://github.com/CoreSecurity/SAP-Dissection-plug-in-for-Wireshark/tree/master).

Thanks!

**Comment by blshkv** [comment]
well done, thank you
