### ISSUE TITLE
dev-python/pyperclip-1.5.27 fails with "cannot connect to X server localhost:10.0"

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#144]
build.log and other files attached.
[files.zip](https://github.com/pentoo/pentoo-overlay/files/696030/files.zip)

**Comment by blshkv** [comment]
The ebuild was copied from the dev-zero overla, please join bug report:
https://bugs.gentoo.org/show_bug.cgi?id=605256

**Comment by blshkv** [comment]
please make sure that your X env is not broken. You have multiple font warnings etc.

I can not reproduce the bug using different env including a clean server (no X)

**Comment by blshkv** [comment]
I'm closing this bug for now. Please provide more details so that I could reproduce it.

**Comment by bill-e-ghote** [comment]
Maybe this helps?

Is it a strict requirement to be running within a local X login for this package to build?

I hope not, as that would be just silly...

wdawson@pentoo $ ssh -Y 192.168.2.147
wdawson@bghote2 ~ $ sudo -s
bghote2 wdawson # cd
bghote2 ~ # eix dev-python/pyperclip
* dev-python/pyperclip [1]
     Available versions:  (~)1.5.27^t {test PYTHON_TARGETS="python2_7 python3_4 python3_5"}
     Homepage:            https://github.com/asweigart/pyperclip https://pypi.python.org/pypi/pyperclip
     Description:         Cross-platform clipboard module

[1] "pentoo" /var/lib/layman/pentoo
bghote2 ~ # emerge dev-python/pyperclip
Calculating dependencies... done!

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) dev-python/pyperclip-1.5.27::pentoo
>>> Downloading 'http://distfiles.gentoo.org/distfiles/pyperclip-1.5.27.zip'
--2017-01-22 09:50:44--  http://distfiles.gentoo.org/distfiles/pyperclip-1.5.27.zip
Resolving distfiles.gentoo.org... 64.50.233.100, 156.56.247.195, 64.50.236.52, ...
Connecting to distfiles.gentoo.org|64.50.233.100|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-01-22 09:50:45 ERROR 404: Not Found.

>>> Downloading 'https://files.pythonhosted.org/packages/source/p/pyperclip/pyperclip-1.5.27.zip'
--2017-01-22 09:50:45--  https://files.pythonhosted.org/packages/source/p/pyperclip/pyperclip-1.5.27.zip
Resolving files.pythonhosted.org... 151.101.193.63, 151.101.129.63, 151.101.65.63, ...
Connecting to files.pythonhosted.org|151.101.193.63|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://pypi.python.org/packages/7b/a5/48eaa1f2d77f900679e9759d2c9ab44895e66e9612f7f6b5333273b68f29/pyperclip-1.5.27.zip [following]
--2017-01-22 09:50:45--  https://pypi.python.org/packages/7b/a5/48eaa1f2d77f900679e9759d2c9ab44895e66e9612f7f6b5333273b68f29/pyperclip-1.5.27.zip
Resolving pypi.python.org... 151.101.192.223, 151.101.128.223, 151.101.64.223, ...
Connecting to pypi.python.org|151.101.192.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16938 (17K) [application/octet-stream]
Saving to: ‘/mnt/disk-image2/distfiles/pyperclip-1.5.27.zip’

/mnt/disk-image2/di 100%[===================>]  16.54K  --.-KB/s    in 0.02s   

2017-01-22 09:50:45 (807 KB/s) - ‘/mnt/disk-image2/distfiles/pyperclip-1.5.27.zip’ saved [16938/16938]

 * pyperclip-1.5.27.zip SHA256 SHA512 WHIRLPOOL size ;-) ...             [ ok ]
>>> Unpacking source...
>>> Unpacking pyperclip-1.5.27.zip to /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work
>>> Source unpacked in /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work
>>> Preparing source in /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27 ...
>>> Source prepared.
>>> Configuring source in /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27 ...
>>> Source configured.
>>> Compiling source in /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27 ...
 * python2_7: running distutils-r1_run_phase python_compile
/usr/bin/python2.7 setup.py build
running build
running build_py
creating /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/lib/pyperclip
copying pyperclip/exceptions.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/lib/pyperclip
copying pyperclip/windows.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/lib/pyperclip
copying pyperclip/__init__.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/lib/pyperclip
copying pyperclip/clipboards.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/lib/pyperclip
warning: build_py: byte-compiling is disabled, skipping.

 * python3_4: running distutils-r1_run_phase python_compile
/usr/bin/python3.4 setup.py build
running build
running build_py
creating /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python3_4/lib/pyperclip
copying pyperclip/exceptions.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python3_4/lib/pyperclip
copying pyperclip/windows.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python3_4/lib/pyperclip
copying pyperclip/__init__.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python3_4/lib/pyperclip
copying pyperclip/clipboards.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python3_4/lib/pyperclip
warning: build_py: byte-compiling is disabled, skipping.

>>> Source compiled.
 * Skipping make test/check due to ebuild restriction.
>>> Test phase [disabled because of RESTRICT=test]: dev-python/pyperclip-1.5.27

>>> Install pyperclip-1.5.27 into /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/ category dev-python
 * python2_7: running distutils-r1_run_phase distutils-r1_python_install
/usr/bin/python2.7 setup.py install --root=/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7
X11 connection rejected because of wrong authentication.
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
running install
running build
running build_py
running install_lib
creating /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7
creating /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr
creating /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64
creating /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7
creating /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7/site-packages
creating /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7/site-packages/pyperclip
copying /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/lib/pyperclip/exceptions.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7/site-packages/pyperclip
copying /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/lib/pyperclip/windows.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7/site-packages/pyperclip
copying /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/lib/pyperclip/__init__.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7/site-packages/pyperclip
copying /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/lib/pyperclip/clipboards.py -> /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7/site-packages/pyperclip
byte-compiling /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7/site-packages/pyperclip/exceptions.py to exceptions.pyc
byte-compiling /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7/site-packages/pyperclip/windows.py to windows.pyc
byte-compiling /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7/site-packages/pyperclip/__init__.py to __init__.pyc
byte-compiling /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7/site-packages/pyperclip/clipboards.py to clipboards.pyc
writing byte-compilation script '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/temp/tmp0n4sdZ.py'
/usr/bin/python2.7 -OO /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/temp/tmp0n4sdZ.py
removing /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/temp/tmp0n4sdZ.py
running install_egg_info
running egg_info
writing /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/pyperclip.egg-info/PKG-INFO
writing top-level names to /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/pyperclip.egg-info/top_level.txt
writing dependency_links to /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/pyperclip.egg-info/dependency_links.txt
reading manifest file '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/pyperclip.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/pyperclip.egg-info/SOURCES.txt'
Copying /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27-python2_7/pyperclip.egg-info to /mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python2.7/usr/lib64/python2.7/site-packages/pyperclip-1.5.27-py2.7.egg-info
running install_scripts
 * python3_4: running distutils-r1_run_phase distutils-r1_python_install
/usr/bin/python3.4 setup.py install --root=/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python3.4
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 14: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 14: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 14: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 14: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 14: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 14: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 14: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 26: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 26: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 26: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 26: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 26: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 26: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 26: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 38: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 38: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 38: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 38: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 38: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 38: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 38: Having multiple <family> in <alias> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 92: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 106: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/69-odofonts.conf", line 125: Having multiple values in <test> isn't supported and may not work as expected
X11 connection rejected because of wrong authentication.
: cannot connect to X server localhost:10.0
 * ERROR: dev-python/pyperclip-1.5.27::pentoo failed (install phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_install
 *   environment, line 2683:  Called distutils-r1_src_install
 *   environment, line  836:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_install'
 *   environment, line  363:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 2210:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 1513:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 1511:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line  563:  Called distutils-r1_run_phase 'distutils-r1_python_install'
 *   environment, line  804:  Called distutils-r1_python_install
 *   environment, line  720:  Called esetup.py 'install' '--root=/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python3.4'
 *   environment, line 1058:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/pyperclip-1.5.27::pentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/pyperclip-1.5.27::pentoo'`.
 * The complete build log is located at '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/temp/build.log'.
 * The ebuild environment file is located at '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/temp/environment'.
 * Working directory: '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27'
 * S: '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27'

>>> Failed to emerge dev-python/pyperclip-1.5.27, Log file:

>>>  '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/temp/build.log'

 * Messages for package dev-python/pyperclip-1.5.27:

 * ERROR: dev-python/pyperclip-1.5.27::pentoo failed (install phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_install
 *   environment, line 2683:  Called distutils-r1_src_install
 *   environment, line  836:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_install'
 *   environment, line  363:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 2210:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 1513:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line 1511:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_install'
 *   environment, line  563:  Called distutils-r1_run_phase 'distutils-r1_python_install'
 *   environment, line  804:  Called distutils-r1_python_install
 *   environment, line  720:  Called esetup.py 'install' '--root=/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/image/_python3.4'
 *   environment, line 1058:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/pyperclip-1.5.27::pentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/pyperclip-1.5.27::pentoo'`.
 * The complete build log is located at '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/temp/build.log'.
 * The ebuild environment file is located at '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/temp/environment'.
 * Working directory: '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27'
 * S: '/mnt/disk-image3/portage/dev-python/pyperclip-1.5.27/work/pyperclip-1.5.27'
bghote2 ~ #

**Comment by blshkv** [comment]
Well,  I tried to compile it on a remote box with no X,  did not hit this problem.  There is something special in your env..

**Comment by bill-e-ghote** [comment]
I would have thought ssh with -Y option to be the same as -X option for this, but it isn't. So, definitely not an ebuild bug, but an "interesting" implementation difference in SSH command line options. That is, I was able to get this to work by logging in to my remote system using -X, but not with -Y.

**Comment by gh2k** [comment]
Sorry to necro, but for people landing here from Google like I did:

Given the comment above that it seemed to work with untrusted X forwarding, I worked around this problem by adding `ForwardX11Trusted no` to `~/.ssh/config` temporarily (don't forget to remove this) and then running `ssh -X localhost emerge -1 dev-python/pyperclip`.

**Comment by blshkv** [comment]
@gh2k ```ssh -Y``` is a better option

**Comment by gh2k** [comment]
@blshkv according to the comments above, `-Y` doesn't work. See the comment immediately preceding mine.

**Comment by blshkv** [comment]
ok, I haven't used X forwarding for a long time and it seems like -X is more "secure".

However, I was using "localhost" forwarding:
```
X11Forwarding yes
X11DisplayOffset 10 
X11UseLocalhost yes
```
Could you also try this setup with -Y to see if it works?
