### ISSUE TITLE
PyQt4 assistant USE removed in gentoo

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#146]
Hi all, the actual package dff requieres this USE from PyQt4 but is removed from gentoo (the USE not the package):

```
app-forensics/dff/dff-1.3.0-r3.ebuild:	doc? ( >=dev-python/PyQt4-4.4.0[help,webkit,assistant,${PYTHON_USEDEP}] )
```

so now i can't update this..., i don't know if this is right but searching i found this package in gentoo ```dev-qt/assistant``` maybe should request this instead?, or remove the required USE?

Thx. Cya.

**Comment by blshkv** [comment]
dff does not install help.* files in 1.3 version so there is no need in qtassistant anymore. 
Removed, thanks

**Comment by latot** [comment]
Thx!
