### ISSUE TITLE
app-admin/opensnitch-1.5.3 fails to compile

### ISSUE THREAD

**Issue by mahdi1234** [pentoo/pentoo-overlay#1486]
Both 1.5.3 and 1.5.2 fail to compile on ryzen laptop while both do compile on old i7 (not sure this is relevant)

Attached is build log and emerge --info output.

[emerge.info.txt](https://github.com/pentoo/pentoo-overlay/files/10530052/emerge.info.txt)
[build.log](https://github.com/pentoo/pentoo-overlay/files/10530053/build.log)

**Comment by anders-larsson** [comment]
I'm also experiencing this. Same error on a Ryzen 1800X CPU. Any suggestion would be helpful.

**Comment by kcning** [comment]
I had the same problem and solved it by rolling dev-lang/go back to version 1.18.10. Both 1.5.2 and 1.5.3 then build correctly. My understanding is that this might be an upstream issue.

**Comment by anders-larsson** [comment]
Looks like the earliest version of dev-lang/go in portage is 1.19.14 (I'm on 1.20 myself). Did you re-add the old dev-lang/go ebuild to a custom repository to build it?

**Comment by Bogdan107** [comment]
app-admin/opensnitch-1.5.3::pentoo - build fails with gcc-12.
Build success with gcc-11.

I use gcc-switcher script to change the choise of the gcc version to build the opensnitch package.
I think, that more universal way - to select gcc version in the ebuild (maybe, by use function from the some eclass).

### Change gcc version per package by gcc-switcher script:
#### See default gcc version:
```
# eselect gcc list
 [1] x86_64-pc-linux-gnu-10
 [2] x86_64-pc-linux-gnu-11
 [3] x86_64-pc-linux-gnu-12 *
```
#### Change gcc version for selected package:
```
# grep opensnitch /etc/portage/package.compilers
app-admin/opensnitch 11
```
#### Apply gcc version selection by additional app-portage/gcc-switcher script:
```
# equery b /etc/portage/package.compilers
 * Searching for /etc/portage/package.compilers ... 
app-portage/gcc-switcher-1.4.1 (/etc/portage/package.compilers)
```
