### ISSUE TITLE
dev-util/radare2 :: problem with v5.8.2

### ISSUE THREAD

**Issue by richardredditch** [pentoo/pentoo-overlay#1488]
looks like there is a problem with this version atm which may impact builds if included. So far only working version for me is v5.8.0 from https://github.com/hamarituc/gentoo-overlay/tree/master/dev-util/radare2. Should this be reported upstream?

**Comment by ZeroChaos-** [comment]
It would help if you said what the problem was ...

**Comment by richardredditch** [comment]
this is for v5.8.2 from gentoo: https://bpa.st/WNIH4

**Comment by ZeroChaos-** [comment]
github recently messed up their file checksums on purpose, and then reverted the change.  That's a gentoo bug and should be reported to gentoo
