### ISSUE TITLE
dev-ruby/data_objects -- doc use

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#15]
Hi, here other problem with doc use:

 * Package:    dev-ruby/data_objects-0.10.13
 * Repository: pentoo
 * USE:        abi_x86_64 amd64 doc elibc_glibc kernel_linux pie ruby_targets_ruby19 ssp userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Running unpack phase for all ...
 * Unpacking .gem file... ...
 [ ok ]
 * Uncompressing metadata ...
 [ ok ]
 * Unpacking data.tar.gz ...
 [ ok ]
>>> Source unpacked in /var/tmp/portage/dev-ruby/data_objects-0.10.13/work
>>> Preparing source in /var/tmp/portage/dev-ruby/data_objects-0.10.13/work ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby19 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-ruby/data_objects-0.10.13/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-ruby/data_objects-0.10.13/work ...
 * Running compile phase for all ...
rake aborted!
LoadError: cannot load such file -- bundler
/var/tmp/portage/dev-ruby/data_objects-0.10.13/work/all/data_objects-0.10.13/Rakefile:3:in `<top (required)>'

Thx.

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/37
