### ISSUE TITLE
app-fuzz/fuzzdb-1.09_p20170117::pentoo failed (depend phase): git-r3: EAPI 5 not supported

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#1500]
Calculating dependencies   * ERROR: app-fuzz/fuzzdb-1.09_p20170117::pentoo failed (depend phase):
 *   git-r3: EAPI 5 not supported
 *
 * Call stack:
 *                      ebuild.sh, line 628:  Called source '/var/lib/layman/pentoo/app-fuzz/fuzzdb/fuzzdb-1.09_p20170117.ebuild'
 *   fuzzdb-1.09_p20170117.ebuild, line   7:  Called inherit 'git-r3'
 *                      ebuild.sh, line 308:  Called __qa_source '/var/db/repos/gentoo/eclass/git-r3.eclass'
 *                      ebuild.sh, line 123:  Called source '/var/db/repos/gentoo/eclass/git-r3.eclass'
 *                  git-r3.eclass, line  15:  Called die
 * The specific snippet of code:
 *      *) die "${ECLASS}: EAPI ${EAPI:-0} not supported" ;;
 *
 * If you need support, post the output of `emerge --info '=app-fuzz/fuzzdb-1.09_p20170117::pentoo'`,
 * the complete build log and the output of `emerge -pqv '=app-fuzz/fuzzdb-1.09_p20170117::pentoo'`.
 * Working directory: '/usr/lib/python3.10/site-packages'
 * S: '/var/tmp/portage/app-fuzz/fuzzdb-1.09_p20170117/work/fuzzdb-1.09_p20170117'

Searching /var/lib/layman/pentoo for .ebuild files with EAPI=5:

/var/lib/layman/pentoo/app-fuzz/fuzzdb/fuzzdb-1.09_p20170117.ebuild
/var/lib/layman/pentoo/net-wireless/gps-sdr-sim/gps-sdr-sim-9999.ebuild
/var/lib/layman/pentoo/www-misc/firefox-bookmarks/firefox-bookmarks-0.3-r1.ebuild
/var/lib/layman/pentoo/net-analyzer/hyenae/hyenae-0.36.1.ebuild
/var/lib/layman/pentoo/sys-apps/magic-pax/magic-pax-0.0.1.ebuild
/var/lib/layman/pentoo/net-proxy/proxenet-plugins/proxenet-plugins-9999.ebuild
/var/lib/layman/pentoo/net-proxy/pbounce/pbounce-0.1.ebuild

**Comment by ZeroChaos-** [comment]
https://github.com/pentoo/pentoo-overlay/commit/de1953eecadf8294bd4a0e7208a0fd60d73a9313
