### ISSUE TITLE
unable to upload /tmp/pentoo-updater log file using suggested wgetpaste -s bpaste command #67

### ISSUE THREAD

**Issue by sysfu** [pentoo/pentoo-overlay#1501]
Last run of pentoo-updater script had some errors and when I used the suggested command to upload via bpaste it failed with
ERROR 413: Request Entity Too Large

IIRC this log file had a thousand or so lines, smaller logs upload without issue.

Maybe there is another pastebin service that could be suggested in the wgetpaste command that won't choke on the larger log files generated by the script?

Looks like the current size limit of bpaste.net [is set to 256K](https://github.com/search?q=repo%3Asupakeen%2Fpinnwand%20PASTE_SIZE&type=code)

**Comment by ZeroChaos-** [comment]
try `wgetpaste --help` and other services.  If none work, feel free to find any pastebin service you like and put the log there.  of note, I just update the installer a little, so once a daily newer than March 17th is available you may just try that and see if I fixed your issue
