### ISSUE TITLE
available sdrpp-9999 by Hamari .

### ISSUE THREAD

**Issue by Brumi-2021** [pentoo/pentoo-overlay#1502]
Hello ,

FYI , 

 thanks to  [hamarituc](https://github.com/hamarituc) with this commit https://github.com/hamarituc/gentoo-overlay/commit/024b22c329f9e6bf774f1c0356e61d213b9f75b6
he updated his previous broken sdrpp-9999.ebuild and now it is working again . 

I already emerged  it and now , all seems working well , and we do not need to keep using sdrpp-1.0.4 , more than 1,5 year old.
that is many commits behind current nightly , 

Cheers.

**Comment by ZeroChaos-** [comment]
package removed from pentoo
