### ISSUE TITLE
pentoo-updater error 'Could not import 'smartliverebuild.sets.SmartLiveRebuildSet'

### ISSUE THREAD

**Issue by sysfu** [pentoo/pentoo-overlay#1507]
Keep getting this error in red text everytime pentoo-updater is run.

`'Error during set creation: Could not import 'smartliverebuild.sets.SmartLiveRebuildSet' for section 'smart-live-rebuild''`

**Comment by ZeroChaos-** [comment]
This is normal output mid-way through a python update.  Nothing to worry about
