### ISSUE TITLE
pentoo-updater error:  All ebuilds that could satisfy ">=dev-libs/libffi-3.4.4-r1:=" have been masked.          

### ISSUE THREAD

**Issue by sysfu** [pentoo/pentoo-overlay#1508]
This error breaks about two dozen dependencies.

```
!!! All ebuilds that could satisfy ">=dev-libs/libffi-3.4.4-r1:=" have been masked.            
!!! One of the following masked packages is required to complete your request:
- dev-libs/libffi-3.4.4-r1::gentoo (masked by: ~amd64 keyword)

```

As a temporary workaround, should I create /etc/portage/package.accept_keywords/libffi.conf? Or wait until it's fixed?

**Comment by ZeroChaos-** [comment]
With no context this bug isn't actionable.  Please provide a useful level of output, preferably all of the output and whatever command you are running.

**Comment by sysfu** [comment]
Command was simply `sudo pentoo-updater`

Log file attached
[pentoo-updater.log](https://github.com/pentoo/pentoo-overlay/files/11202865/pentoo-updater.log)

**Comment by sysfu** [comment]
Is it possible to re-open this issue? Or should I make a new one? Didn't want to create a duplicate unless necessary.
