### ISSUE TITLE
Pentoo LiveUSB crashing while loading nVidia gpu driver

### ISSUE THREAD

**Issue by Night-slayeR** [pentoo/pentoo-overlay#1514]
This behavior was observed in 27.04.2023. image as well as the one before it. 
After selecting Pentoo Linux Live (verify) loading procedure starts, and it crashes after coming to a step for loading nvidia gpu drivers.
The following steps are on the final screen before crash:

* Caching service dependencies ...
* Setting up broadcom firmware if needed ...
* Setting up GPU drivers requested by user, this may take a few minutes ...
* Detected: nvidia gpu, please stand by ...
* (FAIL) NVIDIA binary driver requested but doesn't support this hardware, trying nouveau ...

After this step, boot procedure crashes and PC is restarted. Important thing to mention is that PC has the same hardware and Pentoo image from October works properly on it.

**Comment by Night-slayeR** [comment]
Yes and no. During boot screen, press E while the first option is selected and add nomodeset flag at the end of line. It disables video drivers and you can boot Pentoo. But that is not a good solution

**Comment by ZeroChaos-** [comment]
Point of fact, the "Pentoo Linux Live (no binary drivers)" menu entry disables binary drivers, "nomodeset" disables mode setting which is the basic linux standard way to change resolutions, etc.

If "nomodeset" fixes a problem for you, please share the output of `uname -a` and `lspci`

Also, and I can't stress this enough, if you are using a computer from the last ten years you should be using the amd64 iso not the x86 iso.
