### ISSUE TITLE
 app-misc/mat2 requires python xml USE flag that does not exist 

### ISSUE THREAD

**Issue by RayOfLight1** [pentoo/pentoo-overlay#1515]
emerge: there are no ebuilds built with USE flags to satisfy ">=dev-lang/python-3.11.1-r1:3.11[xml]".
!!! One of the following packages is required to complete your request:
- dev-lang/python-3.11.3::gentoo (Missing IUSE: xml)
- dev-lang/python-3.11.3::gentoo (Missing IUSE: xml)
(dependency required by "app-misc/mat2-0.13.3::pentoo[-test,python_targets_python3_11]" [ebuild])
(dependency required by "@selected" [set])

**Comment by blshkv** [comment]
yeap, thanks!
