### ISSUE TITLE
opensnitch/opensnitch-1.6.0.ebuild doesn't build ebpf_prog

### ISSUE THREAD

**Issue by fraschm1998** [pentoo/pentoo-overlay#1526]
opensnitch.o needs to built as per: https://github.com/evilsocket/opensnitch/tree/master/ebpf_prog

Seems to have been removed after opensnitch-1.5.3.ebuild

**Comment by blshkv** [comment]
@kcning  please have a look and fix it. Your commit https://github.com/pentoo/pentoo-overlay/pull/1525 is here

**Comment by fraschm1998** [comment]
> @kcning please have a look and fix it. Your commit #1525 is here

My mistake, got it fixed by adding the ebf USE flag.

@kcning please add Kernel checks if using nftables as per: https://github.com/evilsocket/opensnitch/issues/976

**Comment by kcning** [comment]
Sure, I'll check with upstream about the required config options then submit a PR.

**Comment by blshkv** [comment]
@kcning great work, thanks!
