### ISSUE TITLE
feature request: pentoo-updater script option for disabling sync

### ISSUE THREAD

**Issue by sysfu** [pentoo/pentoo-overlay#1533]
I often find myself in situations where I have to re-run the pentoo-updater script while troubleshooting failures.

It would be nice to a have a command line option that disables rsync.gentoo.org network sync on a per run basis so I don't run afoul of the following script warning:

```
Please note: common gentoo-netiquette says you should not sync more
than once a day.  Users who abuse the rsync.gentoo.org rotation
may be added to a temporary ban list.
```

**Comment by ZeroChaos-** [comment]
NO_SYNC=true pentoo-updater
