### ISSUE TITLE
Burp browser not working (x permission not set)

### ISSUE THREAD

**Issue by DaniD3v** [pentoo/pentoo-overlay#1536]
![image](https://github.com/pentoo/pentoo-overlay/assets/124387056/1117a9f8-f347-426b-bda6-5fe3fd3c5f9f)
![image](https://github.com/pentoo/pentoo-overlay/assets/124387056/45b516ad-238a-4d40-a78e-2e90d504b1c4)

**Comment by DaniD3v** [comment]
![image](https://github.com/pentoo/pentoo-overlay/assets/124387056/70107945-e3d8-48c5-a3ee-54045f966395)
oh and it also has a segfault great

![image](https://github.com/pentoo/pentoo-overlay/assets/124387056/37b85ff5-f451-402c-ac3a-43c381ec82d4)

**Comment by blshkv** [comment]
Hm... We modify jar file to remove some non Linux related binaries. I'll have a look. Thanks!

**Comment by blshkv** [comment]
so I'm unable to reproduce. Please share arch, and burp/burppro with version

**Comment by DaniD3v** [comment]
The update fixed it
