### ISSUE TITLE
dev-python/aiopg-1.4.0-r2 fails to compile: TypeError: Python directive method get_signature_prefix() must return a list of nodes Return value was coroutine async-with  

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1582]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-python/aiopg-1.4.0-r2 fails to compile.
Discovered on: amd64 (internal ref: pentoo_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0002

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/bac3fbc28fee280d58634651b01409e3
1-sphinx-err-gzjazknp.log: https://gist.github.com/asarubbo/773b6df9f1b900b8520f1fc07e37be16

**Comment by blshkv** [comment]
removed
