### ISSUE TITLE
EAPI=3 not supported in portage 2.3.3

### ISSUE THREAD

**Issue by robertu94** [pentoo/pentoo-overlay#163]
In Portage 2.3.3, EAPI 3 is not supported.  This causes portage and eix to throw errors when syncing this overlay.

The following ebuilds are affected:

dev-python/pymills/pymills-3.4-r2.ebuild
app-forensics/streams/streams-0.1.0.ebuild
app-forensics/libforensic1394/libforensic1394-9999.ebuild
app-forensics/libforensic1394/libforensic1394-0.2.ebuild
app-forensics/libpff/libpff-0.0.20120802_alpha.ebuild
app-forensics/libpff/libpff-0.0.20120513_alpha.ebuild
app-forensics/libpff/libpff-0.0.20110413_alpha.ebuild
app-forensics/libpff/libpff-0.0.20120611_alpha.ebuild
net-libs/nfqueue-bindings/nfqueue-bindings-0.4.ebuild
dev-libs/libhijack/libhijack-0.6.ebuild
dev-libs/libhijack/libhijack-0.5.2.ebuild
net-wireless/nfcd/nfcd-9999.ebuild
net-wireless/libfreefare/libfreefare-0.3.2.ebuild
net-analyzer/hyenae/hyenae-0.36_p1.ebuild
net-analyzer/sslstrip/sslstrip-0.9-r1.ebuild
net-analyzer/padbuster/padbuster-20110928.ebuild
net-analyzer/netmap/netmap-0.1.3.ebuild
net-analyzer/davtest/davtest-1.0-r1.ebuild
app-fuzz/fuzzdb/fuzzdb-1.09.ebuild
app-crypt/cpyrit_calpp/cpyrit_calpp-9999.ebuild
app-crypt/cpyrit_calpp/cpyrit_calpp-0.4.0.ebuild
net-proxy/webscarab/webscarab-20110329.ebuild
net-proxy/sshttp/sshttp-0.25.ebuild
dev-ruby/jsmin/jsmin-1.0.1.ebuild

**Comment by ZeroChaos-** [comment]
how kind of upstream to drop support for a random EAPI in the middle of the pack.  Remind me to flame dolsen later.

Thanks for the bug, I'll take care of it, probably mostly by removing the out of date garbage.

**Comment by blshkv** [comment]
It's just a number change in majority of ebuild so not a big deal. We set min v4 for a year at least.   However I used this aportunity today and fixed python migration as well.  Dont forget to sync (layman - S at least) before reporting!

**Comment by ZeroChaos-** [comment]
I took care of a bunch of these. bumping and cleanup up where I could, removing where it was unfetchable and missing upstream.

these still remain to do:

net-analyzer/hyenae/hyenae-0.36_p1.ebuild
net-analyzer/sslstrip/sslstrip-0.9-r1.ebuild
net-analyzer/padbuster/padbuster-20110928.ebuild
net-analyzer/netmap/netmap-0.1.3.ebuild
net-analyzer/davtest/davtest-1.0-r1.ebuild
app-fuzz/fuzzdb/fuzzdb-1.09.ebuild
app-crypt/cpyrit_calpp/cpyrit_calpp-9999.ebuild
app-crypt/cpyrit_calpp/cpyrit_calpp-0.4.0.ebuild
net-proxy/webscarab/webscarab-20110329.ebuild
net-proxy/sshttp/sshttp-0.25.ebuild
dev-ruby/jsmin/jsmin-1.0.1.ebuild

**Comment by blshkv** [comment]
Well done! Cheers
