### ISSUE TITLE
new tool: sparta

### ISSUE THREAD

**Issue by ghost** [pentoo/pentoo-overlay#168]
SPARTA - Network Infrastructure Penetration Testing Tool
https://github.com/SECFORCE/sparta
http://sparta.secforce.com/

**Comment by blshkv** [comment]
I have seen a recent announcement and it looked really great until I started to check details.
Apparently, it were no commits for the last 2 years. So I'm not sure if the tool is still even alive.

I'm not going to waste my time for now.

**Comment by blshkv** [comment]
SPARTA requires unsupported cutycapt which has been replaced by phantomjs which, in turn, has been replaced by headless mode in >=www-client/chromium-5, see the following for more details:
https://bugs.gentoo.org/374943

We are NOT going backwards and will not be able to add SPARTA until they migrate to a more recent tools.

Feel free to re-open this issue when the upstream will fix that.
