### ISSUE TITLE
dev-python/pyFFTW-0.13.1 fails to compile: fftw_plan_dft.c:2:17: error: implicit declaration of function fftw_plan_dft [-Wimplicit-function-declaration] 

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1750]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-python/pyFFTW-0.13.1 fails to compile.
Discovered on: amd64 (internal ref: pentoo_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0002

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/4de425e82ba1779f9059cec42be38927
Context of error(s): https://gist.github.com/asarubbo/4ed9fa3cbf6347c4e857849efa92ae28

**Comment by blshkv** [comment]
Try the latest: 0.13.1_p20240117
