### ISSUE TITLE
net-misc/iaxclient-2.1_beta3-r5 fails to build

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#178]
net-misc/iaxclient-2.1_beta3-r5 fails with codec_ffmpeg.c:701:20: error: array type has incomplete element type

Attaching the usual file set.
[files.zip](https://github.com/pentoo/pentoo-overlay/files/867737/files.zip)

**Comment by bill-e-ghote** [comment]
This is from an x86 system, BTW...

**Comment by blshkv** [comment]
it fails on adm64 too. This is an old an unsupported software with the last release dated back in 2008.
It was in use by warvox v1.x but it's not required by the latest 9999 (switched to ruby).

You should not have it in your system, feel free to run "emerge -C iaxclient".

**Comment by bill-e-ghote** [comment]
Too easy. Thanks!
