### ISSUE TITLE
dev-python/pyvoronoi-1.0.7_p20231113 <stabilize-allarches/> found on package installing ELF files

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1789]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-python/pyvoronoi-1.0.7_p20231113 <stabilize-allarches/> found on package installing ELF files.
Discovered on: amd64 (internal ref: pentoo_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#QA0042

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/f0ccaa70954a42214c21b24c57e1744d

**Comment by blshkv** [comment]
removed
