### ISSUE TITLE
dev-python/websocket-client-0.57.0 fails tests: AttributeError: CookieJarTest object has no attribute assertEquals 

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1794]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-python/websocket-client-0.57.0 fails tests.
Discovered on: amd64 (internal ref: pentoo_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0015

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/af0434672a5273a77b3689ee1cf086b8
Context of error(s): https://gist.github.com/asarubbo/4409464a37d93c5f010fe13e7a90367e

**Comment by blshkv** [comment]
moved to Gentoo
