### ISSUE TITLE
dev-ruby/terminal-table -- doc use

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#18]
Hi, here log:

 * Package:    dev-ruby/terminal-table-1.4.5
 * Repository: pentoo
 * USE:        abi_x86_64 amd64 doc elibc_glibc kernel_linux pie ruby_targets_ruby19 ssp userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Running unpack phase for all ...
 * Unpacking .gem file... ...
 [ ok ]
 * Uncompressing metadata ...
 [ ok ]
 * Unpacking data.tar.gz ...
 [ ok ]
>>> Source unpacked in /var/tmp/portage/dev-ruby/terminal-table-1.4.5/work
>>> Preparing source in /var/tmp/portage/dev-ruby/terminal-table-1.4.5/work ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby19 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-ruby/terminal-table-1.4.5/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-ruby/terminal-table-1.4.5/work ...
 * Running compile phase for all ...
rake aborted!
LoadError: cannot load such file -- echoe
/var/tmp/portage/dev-ruby/terminal-table-1.4.5/work/all/terminal-table-1.4.5/Rakefile:4:in `<top (required)>'

Thx.

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/37

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/37
