### ISSUE TITLE
sslyze missing dependencies

### ISSUE THREAD

**Issue by black2754** [pentoo/pentoo-overlay#180]
`net-analyzer/sslyze` is missing (at least) the following runtime dependencies:
* `dev-python/enum34`
* `dev-python/typing`
sslyze does not start without these packages.
I did not check if there are any other missing that I already happened to have installed.

**Comment by blshkv** [comment]
they were missing indeed. Thanks!

**Comment by blshkv** [comment]
Btw, the official requirement list is here https://github.com/nabla-c0d3/sslyze/blob/master/requirements.txt  and there were no additional deps introduced in this version
