### ISSUE TITLE
dev-ruby/ruby-oci8-2.2.10 fails to compile: ocihandle.c:220:16: error: implicit declaration of function rb_tainted_str_new 

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1810]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-ruby/ruby-oci8-2.2.10 fails to compile.
Discovered on: amd64 (internal ref: pentoo_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0014

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/3bd165f0f36248586d7b9b5d1a1f37a2

**Comment by blshkv** [comment]
no longer in the tree
