### ISSUE TITLE
dev-util/ghidra-11.0.1 fails to compile: expCloneExec.c:22:45: error: implicit declaration of function getpid [-Wimplicit-function-declaration] 

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1811]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: dev-util/ghidra-11.0.1 fails to compile.
Discovered on: amd64 (internal ref: pentoo_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0002

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/93c345df1627020ce921c4d67f4e5027
Context of error(s): https://gist.github.com/asarubbo/08a874064247172dae05c53a8e7527cb

**Comment by blshkv** [comment]
ghidra-11.1.1.ebuild please try the latest
