### ISSUE TITLE
net-analyzer/medusa-2.3_pre fails to compile: rdp.c:38:10: fatal error: freerdp.h: No such file or directory 

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1816]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: net-analyzer/medusa-2.3_pre fails to compile.
Discovered on: amd64 (internal ref: pentoo_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0002

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/8b8ae57a6c6eddb2bc22d813a7471ab7
Context of error(s): https://gist.github.com/asarubbo/c09f97ce73887a8fa379f0680faa74cd

**Comment by blshkv** [comment]
medusa-2.3_rc1.ebuild is out, please re-test
