### ISSUE TITLE
net-proxy/shadowsocks-rust-1.17.1 fails tests: [2024-02-17T03:36:54Z ERROR shadowsocks_service::server::tcprelay] tcp tunnel 127.0.0.1:48678 -> www.example.com:80 connect failed, error: dns resolve www.example.com:80 error: proto error: io error: Network

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#1826]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: net-proxy/shadowsocks-rust-1.17.1 fails tests.
Discovered on: amd64 (internal ref: pentoo_tinderbox)
System: GCC-14-SYSTEM (https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#GCC-14)

Info about the issue:
https://wiki.gentoo.org/wiki/Project:Tinderbox/Common_Issues_Helper#CF0015

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/asarubbo/d83d5a597d9cf58d9122919dd48ad4a8
Context of error(s): https://gist.github.com/asarubbo/1a77b457d974833ab386ac743da52e2e

**Comment by blshkv** [comment]
try with shadowsocks-rust-1.20.0.ebuild
