### ISSUE TITLE
missing EOL in /var/lib/layman/pentoo/profiles/pentoo/base/package.accept_keywords/app-forensics

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#188]
Maybe this is not an issue for you, but it has been for me lately. There's no EOL for the /var/lib/layman/pentoo/profiles/pentoo/base/package.accept_keywords/app-forensics file, which breaks things if one is simply concatenating /var/lib/layman/pentoo/profiles/pentoo/base/package.accept_keywords/* into a single file.

So, if you add an EOL back to that file, all is good.

Thanks.

**Comment by blshkv** [comment]
no problem at all
