### ISSUE TITLE
Unicorn/Capstone/Keystone bindings

### ISSUE THREAD

**Issue by brianmwaters** [pentoo/pentoo-overlay#189]
Currently there is a "unicorn" package which installs the C library, and a "unicorn-bindings" library which installs several bindings, depending on the use flags (Python, Java, etc.). On the other hand, w/ capstone there's a "capstone" package for the C libraries and a "capstone-python" package for the Python bindings. I also noticed a "python" use flag was added to the "capstone" package. Capstone comes from Gentoo but Unicorn comes from Pentoo. I'd like to introduce an ebuild for the Keystone engine to complete the trio - what pattern should we use for bindings? Should we change the Unicorn setup so that it's more similar to the Capstone setup?

**Comment by blshkv** [comment]
We provide capstone package with "python" flag with pulls capstone-python.

There are multiple ways to provide bindings. It can be single ebuild (and complex), or splitted per each binding (capstone-python) or combined bindings (unicorn-bindings).

<package>-bindings is easier to maintain multiple languages so I suggest not to change anything here.

**Comment by blshkv** [comment]
Create a pull request or post ebuild /patch. I'm closing the bug for now
