### ISSUE TITLE
dev-ruby/dm-migrations -- missed dependence

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#19]
Hi, here log:

 * Package:    dev-ruby/dm-migrations-1.2.0
 * Repository: pentoo
 * USE:        abi_x86_64 amd64 doc elibc_glibc kernel_linux pie ruby_targets_ruby19 ssp userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Running unpack phase for all ...
 * Unpacking .gem file... ...
 [ ok ]
 * Uncompressing metadata ...
 [ ok ]
 * Unpacking data.tar.gz ...
 [ ok ]
>>> Source unpacked in /var/tmp/portage/dev-ruby/dm-migrations-1.2.0/work
>>> Preparing source in /var/tmp/portage/dev-ruby/dm-migrations-1.2.0/work ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby19 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-ruby/dm-migrations-1.2.0/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-ruby/dm-migrations-1.2.0/work ...
 * Running compile phase for all ...
Jeweler (or a dependency) not available. Install it with: gem install jeweler -v 1.6.4
rake aborted!
Don't know how to build task 'yard'

Thx.

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/37

**Comment by blshkv** [comment]
```
okis, thx, only the #19 its a missed dependence, it need to be fixed.
```

no, jeweler is "DEVELOPMENT" dep, and required with doc flag only
see: https://rubygems.org/gems/dm-migrations/versions/1.2.0
