### ISSUE TITLE
arm64 testing

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#192]
https://github.com/sakaki-/gentoo-on-rpi3-64bit  

RPI-3 x1 (dear Gods I might need aquire a  few just for the DISTCC/Docker resilio.io etc... setup desktp with cross etc...  ) 
(HOLLY i486 Batman.... somethings emerge fast gcc or golang nooooo..... ) 
Has xfce , porthole etc. ... 

anyhow , soon as I get my brick back from samsung... i can fix my dropbox. etc...  (for packages etc..) 
PORTAGE_BINHOST="https://isshoni.org/pi64"
FEATURES="${FEATURES} getbinpkg" 

anyhow , I can test them 1x1 or a list. 
having pentoo on a micro device , might be fun , I can leave 1 behind pair with a **bash-bunny**  
[zerotier](https://bugs.gentoo.org/buglist.cgi?quicksearch=zerotier) for a hidden 10.x.x.x  etc address , for a hidden tunnel in.  ie remote pentoo. 
tatt , I likely can install for the slow tedious compiles... and or automate the arch testing...

**Comment by blshkv** [comment]
The issue is not clear

**Comment by necrose99** [comment]
RPI3  , I have a Gentoo Distro , trying to add Pentoo to it in arm64 
(full 64bit ABI. )

the compiles can be slow-ish...  or not long.   however , I'm willing to share back my compiled packages.

PORTAGE_BINHOST="https://isshoni.org/pi64"  has primary base packages ......

@ Ebuilds *** Keywords =" "  , if you add ~arm64 to them , **I'm Willing to TEST THEM.**

**Comment by necrose99** [comment]
pardon me , just with the bosses shoulder surfing in the Sec... area  ... didn't get a chance to finish before interrupted..  give me a list of ebuilds to try with the RPI3 in arm64 mode , and I'll try the keywords for ~arm64... and test...

**Comment by blshkv** [comment]
I suggest to go ahead with ** keywords first. Once tested, feel free to create a pull request with ~arm64 keywords for the tested ebuilds.

As for the list, whatever is under pentoo/pentoo metapackage would be good to test.
