### ISSUE TITLE
Go-pot 

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#1929]
Http/s honeypot.. 
(Laptops dead...  desktop took a strike⚡️so new power supply...  new  surge strip... so my apologies.. on mobile , bit limited if late)

Also pre compiled binaries on release page.. 

Skeleton ebuild.. 

EAPI=7

DESCRIPTION="A HTTP tarpit written in Go designed to maximize bot misery through very slowly feeding them an infinite stream of fake secrets."
HOMEPAGE="https://github.com/ryanolee/go-pot"
SRC_URI="https://github.com/ryanolee/go-pot/archive/refs/tags/v1.0.0-rc3.tar.gz -> ${P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~arm64 ~arm"
IUSE=""

DEPEND="dev-lang/go"
RDEPEND=""

src_compile() {
    go build -o "${S}/go-pot" 
}

src_install() {
    dobin "${S}/go-pot"
    dodoc README.md
}

**Comment by ryanolee** [comment]
Following up on this let me know if you need any support getting this honeypot placed if you find it worth adding :eyes:

**Comment by blshkv** [comment]
go projects is a pain to maintain. So please create a pull with working ebuild. Until when, i'll close this bug
