### ISSUE TITLE
genmenu

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#193]
no manifest...

**Comment by blshkv** [comment]
Does it work? Gentoo supports manifest less system

**Comment by necrose99** [comment]
thin manifest , however any 9999 packages _last I knew_ had to be signed in the Manifest file. 
as the live dist isnt needing it as commit history..shasum serves as... . wont build on arm64 or OSBOXES.org Gentoo/Sabayon vm's....  , emerge --manifest..... no go either. 

less they mad it easier, however REPOMAN , has a Moth!@#$%^ F ton of bugs .... on bugs.gentoo....

it will make Manifest files and >/path/path or just epicly fail....

**Comment by blshkv** [comment]
Please share an errorr output. I don't quite understand what is the problem.

**Comment by ZeroChaos-** [comment]
there is no issue here. 9999 ebuilds do NOT require a manifest, the manifest is only required for distfiles now since ebuilds and patches (and anything else checked into git) is already checksummed.
