### ISSUE TITLE
dev-util/ghidra: demangler does not have executable permissions

### ISSUE THREAD

**Issue by ElDavoo** [pentoo/pentoo-overlay#1984]
Hello,
I've tried analyzing a sample binary with Ghidra and I had this warning:
`Demangler GNU> Unable to demangle symbol: __DT_MIPS_BASE_ADDRESS at 00400000.  Message: java.io.IOException: Cannot run program "/usr/share/ghidra/Ghidra/../GPL/DemanglerGnu/os/linux_x86_64/demangler_gnu_v2_41": error=13, Permission denied`  
I checked out `/usr/share/ghidra/GPL/DemanglerGnu/os/linux_x86_64` and the files are indeed not executable, while they should be.

**Comment by ElDavoo** [comment]
same for `/usr/share/ghidra/Ghidra/Features/Decompiler/os/linux_x86_64/decompile`

**Comment by blshkv** [comment]
great find. Thanks!
