### ISSUE TITLE
wifi-pumpkin rogue-wifi-access-point-attack framework.

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#208]
https://n0where.net/rogue-wifi-access-point-attack-wifi-pumpkin/
1st round draft ebuild template..  really rough.. 
many of the depends are in Gentoo/pentoo... 

[wifi-pumpkin-0.8.5.ebuild-template.txt](https://github.com/pentoo/pentoo-overlay/files/1055559/wifi-pumpkin-0.8.5.ebuild-template.txt)

**Comment by necrose99** [comment]
tool is already in kali linux and blackarch. 
might be of use..

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/tree/master/net-wireless/wifi-pumpkin
