### ISSUE TITLE
SpiderFoot 2.10 tool req..

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#210]
https://github.com/smicallef/spiderfoot

http://www.spiderfoot.net/

SpiderFoot
SpiderFoot is an open source intelligence automation tool. Its goal is to automate the process of gathering intelligence about a given target.

Purpose
There are three main areas where SpiderFoot can be useful:

If you are a pen-tester, SpiderFoot will automate the reconnaisance stage of the test, giving you a rich set of data to help you pin-point areas of focus for the test.

Understand what your network/organisation is openly exposing to the outside world. Such information in the wrong hands could be a significant risk.

SpiderFoot can also be used to gather threat intelligence about suspected malicious IPs you might be seeing in your logs or have obtained via threat intelligence data feeds.

Features
Utilises a shedload of data sources; over 50 so far and counting, including SHODAN, RIPE, Whois, PasteBin, Google, SANS and more.

Designed for maximum data extraction; every piece of data is passed on to modules that may be interested, so that they can extract valuable information. No piece of discovered data is saved from analysis.

Runs on Linux and Windows. And fully open-source so you can fork it on GitHub and do whatever you want with it.

Visualisations. Built-in JavaScript-based visualisations or export to GEXF/CSV for use in other tools, like Gephi for instance.

Web-based UI and CLI. Choose between a GUI that is easy to use and a powerful command-line interface. Take a look through the gallery for screenshots of the GUI.

Highly configurable. Almost every module is configurable so you can define the level of intrusiveness and functionality.

Modular. Each major piece of functionality is a module, written in Python. Feel free to write your own and submit them to be incorporated!

SQLite back-end. All scan results are stored in a local SQLite database, so you can play with your data to your heart’s content.

Simultaneous scans. Each footprint scan runs as its own thread, so you can perform footprinting of many different targets simultaneously.

So much more.. check out the documentation for more information.

**Comment by necrose99** [comment]
https://ict.fit.cvut.cz/gitlab/gentoo/overlay/tree/a271a3ca5346d04a47266d2824741b678df2d955/sci-misc
stale on /gephi/gephi-0.8.1_beta.ebuild , but might be of use..

**Comment by necrose99** [comment]
templative ebuild. 
[spiderfoot-2.10-final.ebuild.txt](https://github.com/pentoo/pentoo-overlay/files/1055841/spiderfoot-2.10-final.ebuild.txt)

**Comment by linxon** [comment]
has been added as [app-forensics/spiderfoot](https://github.com/pentoo/pentoo-overlay/blob/5e4ef2f3f507ff41f44c260df505e6c08439bba8/app-forensics/spiderfoot/spiderfoot-2.12.0.ebuild)

close it
