### ISSUE TITLE
Asking_update official soapysdr_version based on that link

### ISSUE THREAD

**Issue by Brumi-2021** [pentoo/pentoo-overlay#2108]
Hello , 
Recently with the help of Stefan , we managed to add airspyhf to his cubicsdr  (he is maintaining it in his  gentoo overlay repo) . 
You can see all the related details in my PR to him , https://github.com/stefantalpalaru/gentoo-overlay/pull/153

But to implement  airspyhf to this cubicsdr , we also needed to modify locally  the official gentoo soapysdr-0.8.1-r1 ==> r2,
 (that I believe that you are maintaining it) 

In that PR , we modified cubicsdr and two dependencies : 

Cubicsdr → modifyed local ebuild copy of stefan’s : net-wireless/cubicsdr-0.2.7-r1          ---> r2
      

> **Soapysdr** → modifyed local ebuild copy of gentoo net-wireless/soapysdr-0.8.1-r1      --->r2

            

>  **Soapyairspyhf.** → generated new local ebuild net-wireless/soapyairspyhf-0.2.0      (new added Soapy sdr module)
>              Soapyhackrf     (other , exisiting Soapy  sdr modules)
>              Soapyrtlsdr       (other , exisiting Soapy  sdr modules)
>              Soapyplutosdr   (other , exisiting Soapy  sdr modules)
>              .... 

-------------------------------------------------------------------------
If you also feel interesting it  to all  gentoo / pentoo  community , pls, feel free to update the official gentoo  soapysdr ebuild  , with the new dependency , 

Soapysdr → modifyed local ebuild copy of gentoo net-wireless/soapysdr-0.8.1-r1----->r2
        

> Soapyairspyhf. → generated new local ebuilt net-wireless/soapyairspyhf-0.2.0 Soapy sdr module)

Thanks , cheers 

![image](https://github.com/user-attachments/assets/926b3219-3fe4-4853-93f3-b9c9efae0fe5)

  
[ Results for search key : soapy ]
Searching...

*  dev-python/simplesoapy
      Latest version available: 1.5.1-r1
      Latest version installed: 1.5.1-r1
      Size of files: 7 KiB
      Homepage:      https://github.com/xmikos/simplesoapy
      Description:   Simple pythonic wrapper for SoapySDR library
      License:       MIT

*  dev-python/soappy
      Latest version available: 0.12.22-r200
      Latest version installed: [ Not Installed ]
      Size of files: 169 KiB
      Homepage:      http://pywebsvcs.sourceforge.net/ https://pypi.org/project/SOAPpy/
      Description:   SOAP Services for Python
      License:       BSD

*  net-analyzer/scapy
      Latest version available: 2.5.0
      Latest version installed: 2.5.0
      Size of files: 5941 KiB
      Homepage:      https://scapy.net/ https://github.com/secdev/scapy
      Description:   A Python interactive packet manipulation program for mastering the network
      License:       GPL-2

*  net-libs/gsoap
      Latest version available: 2.8.114-r1
      Latest version installed: [ Not Installed ]
      Size of files: 33789 KiB
      Homepage:      http://gsoap2.sourceforge.net
      Description:   A cross-platform open source C and C++ SDK for SOAP/XML Web services
      License:       || ( gSOAP-1.3b GPL-2+-with-openssl-exception ) GPL-2+

*  net-wireless/soapy-sdrplay3 [ Masked ]
      Latest version available: 20230421
      Latest version installed: [ Not Installed ]
      Size of files: 22 KiB
      Homepage:      https://github.com/pothosware/SoapySDRPlay3
      Description:   Soapy SDR module for SRDPlay API v3
      License:       MIT

*  net-wireless/soapy_power
      Latest version available: 1.6.1-r1
      Latest version installed: 1.6.1-r1
      Size of files: 19 KiB
      Homepage:      https://github.com/xmikos/soapy_power
      Description:   Obtain power spectrum from SoapySDR devices
      License:       MIT

*  net-wireless/soapyairspyhf
      Latest version available: 0.2.0
      Latest version installed: 0.2.0
      Size of files: 12 KiB
      Homepage:      https://github.com/pothosware/SoapyAirspyHF
      Description:   SoapySDR Airspyhf-SDR Support Module
      License:       MIT

*  net-wireless/soapybladerf
      Latest version available: 0.4.1
      Latest version installed: 0.4.1
      Size of files: 29 KiB
      Homepage:      https://github.com/pothosware/SoapyBladeRF
      Description:   Soapy SDR plugin for the Blade RF
      License:       MIT

*  net-wireless/soapyhackrf
      Latest version available: 0.3.4
      Latest version installed: 0.3.4
      Size of files: 17 KiB
      Homepage:      https://github.com/pothosware/SoapyHackRF
      Description:   SoapySDR HackRF module
      License:       MIT

*  net-wireless/soapyplutosdr
      Latest version available: 0.2.2
      Latest version installed: 0.2.2
      Size of files: 25 KiB
      Homepage:      https://github.com/pothosware/SoapyPlutoSDR
      Description:   Soapy SDR plugin for the Pluto SDR
      License:       LGPL-2.1+

*  net-wireless/soapyremote [ Masked ]
      Latest version available: 9999
      Latest version installed: [ Not Installed ]
      Size of files: 0 KiB
      Homepage:      https://github.com/pothosware/SoapyRemote
      Description:   Soapy SDR remote module
      License:       Boost-1.0

*  net-wireless/soapyrtlsdr
      Latest version available: 0.3.3
      Latest version installed: 0.3.3
      Size of files: 17 KiB
      Homepage:      https://github.com/pothosware/SoapyRTLSDR
      Description:   SoapySDR RTL-SDR Support Module
      License:       MIT

*  net-wireless/soapysdr
      Latest version available: 0.8.1-r2
      Latest version installed: 0.8.1-r2
      Size of files: 129 KiB
      Homepage:      https://github.com/pothosware/SoapySDR
      Description:   vendor and platform neutral SDR support library
      License:       Boost-1.0

*  net-wireless/soapysdrplay [ Masked ]
      Latest version available: 20220120
      Latest version installed: [ Not Installed ]
      Size of files: 21 KiB
      Homepage:      https://github.com/pothosware/SoapySDRPlay3
      Description:   Soapy SDR plugin for SDRPlay
      License:       Boost-1.0

*  net-wireless/soapyuhd
      Latest version available: 0.4.1
      Latest version installed: 0.4.1
      Size of files: 34 KiB
      Homepage:      https://github.com/pothosware/SoapyUHD
      Description:   Soapy SDR plugins for UHD supported SDR devices
      License:       MIT

Cheers ,

**Comment by ZeroChaos-** [comment]
This is Pentoo's bug tracker not Zero_Chaos's personal bug tracker.

If you want to open a PR for Gentoo I can merge it but everything needed should be in the PR and not split randomly across things you expect me to fetch.

**Comment by Brumi-2021** [comment]
Done , I  already sent a partial PR proposal ,  to the Gentoo overlays.  
thanks
