### ISSUE TITLE
mitmproxy-2.0.2 test-bump 

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#211]
clone of pentoo ebuild to newer version ,  vs the other overlay and the million more packages.. 

(www.osboxes.org/sabayon/ used , used pentoo bins as many of the python compiles die.. )

[Manifest.txt](https://github.com/pentoo/pentoo-overlay/files/1059551/Manifest.txt)
[mitmproxy-2.0.2.ebuild.txt](https://github.com/pentoo/pentoo-overlay/files/1059552/mitmproxy-2.0.2.ebuild.txt)

item compiles.. 

[mitmproxy-2.0.2.tbz2.zip](https://github.com/pentoo/pentoo-overlay/files/1059554/mitmproxy-2.0.2.tbz2.zip) (.zip to shut up up-loader) AMD64

**Comment by blshkv** [comment]
Please stop filling useless bug reports. Your ebuild is still wrong. The requirement list is out of sync
https://github.com/mitmproxy/mitmproxy/blob/master/setup.py

**Comment by necrose99** [comment]
noted i just bumped the one to match the old ebuild with newer  upstream src. , and was at least was able to build thus.

**Comment by blshkv** [comment]
ecf3cec1bf0703f3ec6a1c56a18598d5bfdf42da
