### ISSUE TITLE
[help] Qubes

### ISSUE THREAD

**Issue by julie-de-ville** [pentoo/pentoo-overlay#2131]
I am trying to install the pentoo overlay on a qubes gentoo-minimal template. The qubes-specific components run on systemd, and I can't figure out if it's possible to build them specifically for OpenRC. Is it possible to use pentoo with systemd?

**Comment by ZeroChaos-** [comment]
Our profile masks systems but nothing else in the overlay should have an issue with systemd.  You are welcome to report any bugs you hit trying to use systemd but please check basic Gentoo docs for standard Gentoo operation before thinking it's a bug.

**Comment by julie-de-ville** [comment]
Thank you. I checked the setup guide on the wiki on this page, but was still having issues. I will try to again and see if I can get it, or at least replicate the issue.

**Comment by julie-de-ville** [comment]
Currently I am trying to install into a qubes template using the installation ISO. It seems to be working normally, except when I exit the grub configuration on the last step, it does not continue with the installation. I will post the logs shortly.

**Comment by ZeroChaos-** [comment]
The installer has known issues installing legacy boot, ensure you are using uefi
