### ISSUE TITLE
dsniff-2.4_beta1-r10.ebuild for libressl

### ISSUE THREAD

**Issue by androdev4u** [pentoo/pentoo-overlay#223]
--- net-analyzer/dsniff/dsniff-2.4_beta1-r10.ebuild     2017-07-27 15:00:00.000992576 +0200
+++ net-analyzer/dsniff/dsniff-2.4_beta1-r11.ebuild     2017-07-27 15:00:51.191083965 +0200
@@ -15,12 +15,16 @@
 
 SLOT="0"
 KEYWORDS="~amd64 ~ppc ~x86"
-IUSE="X"
+IUSE="X libressl ssl"
 
 DEPEND="net-libs/libpcap
        >=net-libs/libnet-1.1.2.1-r1
        >=net-libs/libnids-1.21
-       >=dev-libs/openssl-0.9.6e:0=
+
+       ssl? (
+       !libressl? ( dev-libs/openssl:0= )
+           libressl? ( dev-libs/libressl:0= )
+               )
        >=sys-libs/db-4.2.52_p4:*
        X? ( x11-libs/libXmu
                 x11-libs/libX11 )"

**Comment by androdev4u** [comment]
Here the readable patch.


[dsniff-ebuild-libressl.patch.txt](https://github.com/pentoo/pentoo-overlay/files/1180049/dsniff-ebuild-libressl.patch.txt)

**Comment by blshkv** [comment]
This software was released back in 2002 ... I would rather just kill it
