### ISSUE TITLE
dev-python/jsbeautifier: global scope cut

### ISSUE THREAD

**Issue by l29ah** [pentoo/pentoo-overlay#237]
And a few more ebuilds too.

**Comment by blshkv** [comment]
not sure what you mean

**Comment by l29ah** [comment]
On Mon, Aug 21, 2017 at 07:00:06PM -0700, Anton Bolshakov wrote:
> not sure what you mean

https://devmanual.gentoo.org/ebuild-writing/variables/

> Some ebuilds use calls to sed, awk and / or cut to do this. This must not be done for any new code, and should be fixed to use either versionator or bash substitution where possible. Global scope non-bash code is highly discouraged.

Repeated fork+exec calls during dependence resolution or metadata generation are slowing things down a lot.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by blshkv** [comment]
oh, I see. That will be the lowest priority in my list. Feel free to create a pull request and I'll merge it faster.

**Comment by blshkv** [comment]
it's actually pretty straightforward. Could you fix the rest affected builds and create a pull request since you care? Thanks in advnace

**Comment by blshkv** [comment]
should be fixed now. Thanks
