### ISSUE TITLE
set a global unicorn target variable

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-overlay#238]
before I forgot:
https://github.com/pentoo/pentoo-overlay/pull/233

**Comment by hackrfbyt** [comment]
We are using pentoo-amd64-hardened-2017.0_RC5.3_pre20170824. It's much better than the  other virsions .THX  . It is better to contain wqy-zenhei wqy-microhei fonts in the next version for chinese fonts webs showing.
The first audio output way is HDMI.So sometims vlc does not play audio.
we try like these: 
aplay -l 

leafpad /etc/asound.conf  add :
defaults.ctl.card 1
defaults.pcm.card 1
defaults.timer.card 1
set the analog way for vedio palyers.

**Comment by blshkv** [comment]
@hackrfbyt your comment has nothing to do with this bug. Please do not mix different issue. It will be ignored. 

Open a separate bug report for each issue.

**Comment by brianmwaters** [comment]
It looks like you had gone and added the flags previously @blshkv, so you can probably re-close this now (just a reminder).

**Comment by blshkv** [comment]
Laat time i checked the flags were not enabled. Ill double check that

**Comment by blshkv** [comment]
Doh! https://github.com/unicorn-engine/unicorn/issues/869
