### ISSUE TITLE
net-wireless/reaver-wps-fork-t6x: cannot update ref

### ISSUE THREAD

**Issue by junked** [pentoo/pentoo-overlay#239]
Failed compilation reaver-wps-fork-t6x with "cannot update ref" error.
https://pastebin.com/feVW1SY6

**Comment by blshkv** [comment]
The problem is at your end. Fix file permissions or delete git a directory in /usr/portage/distfiles

**Comment by junked** [comment]
https://pastebin.com/Mi2KVqsi log after deleting git directory in /usr/portage/distfiles 
I can't compile only this package.

**Comment by blshkv** [comment]
looks like the upstream has restructured git repo. I have just bumped it.
