### ISSUE TITLE
dev-ruby/rubydns -- doc use

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#24]
Hi, here log:

 * Package:    dev-ruby/rubydns-1.0.1
 * Repository: pentoo
 * USE:        abi_x86_64 amd64 doc elibc_glibc kernel_linux ruby_targets_ruby19 ruby_targets_ruby20 ruby_targets_ruby21 userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Running unpack phase for all ...
 * Unpacking .gem file... ...
 [ ok ]
 * Uncompressing metadata ...
 [ ok ]
 * Unpacking data.tar.gz ...
 [ ok ]
>>> Source unpacked in /var/tmp/portage/dev-ruby/rubydns-1.0.1/work
>>> Preparing source in /var/tmp/portage/dev-ruby/rubydns-1.0.1/work ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby19 ...
 * Running source copy phase for ruby20 ...
 * Running source copy phase for ruby21 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-ruby/rubydns-1.0.1/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-ruby/rubydns-1.0.1/work ...
 * Running compile phase for all ...
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
Don't know how to build task 'rdoc'

Thx.

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/37
