### ISSUE TITLE
libre-minipli-sources

### ISSUE THREAD

**Issue by gitbugged** [pentoo/pentoo-overlay#240]
Not sure if there is any interest in this, but I adapted your minipli sources to include [FSFLA's linux-libre](https://www.fsfla.org/ikiwiki/selibre/linux-libre/) kernel. It works very well.

Attached:
[libre-minipli-sources-4.9.48.txt](https://github.com/pentoo/pentoo-overlay/files/1289471/libre-minipli-sources-4.9.48.txt)

**Comment by blshkv** [comment]
We focus on security and not much on libre. I would suggest to add  to the main Gentoo tree instead

**Comment by blshkv** [comment]
Let me know if you want to maintain it and I will be happy to add it. Until then, we can live with "-deblob" USE flag (not tested).
