### ISSUE TITLE
new tool: cuckoo sandbox

### ISSUE THREAD

**Issue by gbmaster** [pentoo/pentoo-overlay#246]
Would it be possible to write an ebuild for this tool for automated malware analysis?

https://cuckoosandbox.org/

**Comment by blshkv** [comment]
https://cuckoo.sh/docs/installation/host/requirements.html

**Comment by blshkv** [comment]
may I ask why you closed the issue?

**Comment by gbmaster** [comment]
Sorry, I thought your reply was pointing me to an alternative way to install cuckoo, instead of using an ebuild.

I'll be reopening this issue

**Comment by blshkv** [comment]
no, I was adding a documentation on how to install it  ;-) From what it looks, shouldn't be very difficult.

**Comment by blshkv** [comment]
I started to add ebuilds for this tool and hit the wall. Basically, the tool supports python2 only at the moment  and it is almost impossible to add all deps for it such as mitmproxy specifically.

https://github.com/cuckoosandbox/cuckoo/issues/2440
https://github.com/hatching/httpreplay/issues/19

Please re-open this bug once the upstream has resolved these issues.
