### ISSUE TITLE
dev-ruby/typhoeus -- doc use

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#25]
Hi, here log:

 * Package:    dev-ruby/typhoeus-0.3.3
 * Repository: pentoo
 * USE:        abi_x86_64 amd64 doc elibc_glibc hardened kernel_linux ruby_targets_ruby19 userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Running unpack phase for all ...
 * Unpacking .gem file... ...
 [ ok ]
 * Uncompressing metadata ...
 [ ok ]
 * Unpacking data.tar.gz ...
 [ ok ]
>>> Source unpacked in /var/tmp/portage/dev-ruby/typhoeus-0.3.3/work
>>> Preparing source in /var/tmp/portage/dev-ruby/typhoeus-0.3.3/work ...
 * Running prepare phase for all ...
 * !!! Typhoeus may only work if ruby19 is MPROTECT disabled
 *   Please disable it if required using paxctl -m /usr/bin/ruby19
 * Running source copy phase for ruby19 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-ruby/typhoeus-0.3.3/work ...
 * Running configure phase for ruby19 ...
extconf.rb:9: Use RbConfig instead of obsolete and deprecated Config.
checking for curl/curl.h in /opt/local/include,/opt/local/include/curl,/usr/include/curl,/usr/include,/usr/include/curl,/usr/local/include/curl... yes
checking for curl_easy_init() in -lcurl... yes
creating Makefile
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-ruby/typhoeus-0.3.3/work ...
 * Running compile phase for ruby19 ...
make -l9 -j9 -C ext/typhoeus 
make: Entering directory '/var/tmp/portage/dev-ruby/typhoeus-0.3.3/work/ruby19/typhoeus-0.3.3/ext/typhoeus'
compiling native.c
compiling typhoeus_easy.c
compiling typhoeus_multi.c
compiling typhoeus_form.c
[01m[Ktyphoeus_multi.c:[m[K In function ‘[01m[Kmulti_perform[m[K’:
[01m[Ktyphoeus_multi.c:165:5:[m[K [01;35m[Kwarning: [m[K‘[01m[Krb_thread_select[m[K’ is deprecated (declared at [01m[K/usr/include/ruby-1.9.1/ruby/intern.h:390[m[K) [-Wdeprecated-declarations]
     rc = rb_thread_select(maxfd+1, &fdread, &fdwrite, &fdexcep, &tv);
[01;32m[K     ^[m[K
[01m[Ktyphoeus_easy.c:[m[K In function ‘[01m[Kread_callback[m[K’:
[01m[Ktyphoeus_easy.c:103:16:[m[K [01;35m[Kwarning: [m[Kconversion to ‘[01m[Ksize_t[m[K’ from ‘[01m[Kint[m[K’ may change the sign of the result [-Wsign-conversion]
     realsize = mem->size - mem->read;
[01;32m[K                ^[m[K
[01m[Ktyphoeus_easy.c:108:15:[m[K [01;35m[Kwarning: [m[Kconversion to ‘[01m[Ksize_t[m[K’ from ‘[01m[Kint[m[K’ may change the sign of the result [-Wsign-conversion]
     mem->read += realsize;
[01;32m[K               ^[m[K
[01m[Ktyphoeus_easy.c:108:18:[m[K [01;35m[Kwarning: [m[Kconversion to ‘[01m[Kint[m[K’ from ‘[01m[Ksize_t[m[K’ may alter its value [-Wconversion]
     mem->read += realsize;
[01;32m[K                  ^[m[K
In file included from [01m[K/usr/include/ruby-1.9.1/ruby.h:32:0[m[K,
                 from [01m[K./native.h:4[m[K,
                 from [01m[K./typhoeus_easy.h:4[m[K,
                 from [01m[Ktyphoeus_easy.c:1[m[K:
[01m[Ktyphoeus_easy.c:[m[K In function ‘[01m[Keasy_set_request_body[m[K’:
[01m[K/usr/include/ruby-1.9.1/ruby/ruby.h:673:5:[m[K [01;35m[Kwarning: [m[Kconversion to ‘[01m[Kint[m[K’ from ‘[01m[Klong int[m[K’ may alter its value [-Wconversion]
     (!(RBASIC(str)->flags & RSTRING_NOEMBED) ? \
[01;32m[K     ^[m[K
[01m[Ktyphoeus_easy.c:167:36:[m[K [01;36m[Knote: [m[Kin expansion of macro ‘[01m[KRSTRING_LEN[m[K’
   curl_easy->request_chunk->size = RSTRING_LEN(data);
[01;32m[K                                    ^[m[K
linking shared-object typhoeus/native.so
make: Leaving directory '/var/tmp/portage/dev-ruby/typhoeus-0.3.3/work/ruby19/typhoeus-0.3.3/ext/typhoeus'
 * Running compile phase for all ...
rake aborted!
Don't know how to build task 'rdoc'

Thx.

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/37
