### ISSUE TITLE
sys-kernel/pentoo-sources-4.13.8 fails due to failed genpatches download

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#259]
[emerge.out.txt](https://github.com/pentoo/pentoo-overlay/files/1594788/emerge.out.txt)

I created a local sys-kernel/pentoo-sources-4.13.8-r1 and changed K_GENPATCHES_VER= from 10 to 19. The kernel sources downloaded, emerge completed, and kernel compiled and installed, but has issues. Like, it thinks it's 4.13.16, which is odd. Also, it can't seem to "see" my Intel Ethernet hardware.

**Comment by blshkv** [comment]
genpatchs are not generic ;-) i.e. you cannot apply to any random version.

**Comment by blshkv** [comment]
also, feel free to keyword and test the latest and the greatest: 
3a10b1622976632850c66aded6a6cd745a86b008

**Comment by bill-e-ghote** [comment]
Yah, blindly modding genpatches was noobish, but I was stuck and it seemed worth a try. Semifunctional, at best.

Is there a generated config available yet? I note this link does not work:
https://raw.githubusercontent.com/pentoo/pentoo-livecd/master/livecd/amd64/kernel/config-4.14.8
...whereas this one does:
https://raw.githubusercontent.com/pentoo/pentoo-livecd/master/livecd/amd64/kernel/config-4.13.8

Easy enough to start with an earlier one and just go from there, of course... though quite a bit has changed/been added, it seems.

**Comment by blshkv** [comment]
yeah, take the previous one and upgrade with ```make oldconfig``` first

I remove a lot of drivers and customise is heavily usually so it is faster to compile and size is much smaller. Feel free to do it as well.
