### ISSUE TITLE
bump requested: dev-libs/libcerror

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#261]
>>> Downloading 'https://github.com/libyal/libcerror/releases/download/20170101/libcerror-beta-20170101.tar.gz'
--2018-01-11 14:37:49--  https://github.com/libyal/libcerror/releases/download/20170101/libcerror-beta-20170101.tar.gz
...
2018-01-11 14:37:50 ERROR 404: Not Found.

Looking at https://github.com/libyal/libcerror/releases/, I see that version is no longer there, but there is:
libcerror-beta-20180102
libcerror-beta-20170824

**Comment by blshkv** [comment]
Oh boy, this project is silly. Why do they need to delete an old version

**Comment by blshkv** [comment]
I suspect we will need to bump the entire list of libs as well:
```
dev-libs/libcthreads
dev-libs/libcdata
dev-libs/libclocale
dev-libs/libcnotify
dev-libs/libcdatetime
dev-libs/libcsplit
dev-libs/libuna
dev-libs/libcfile
dev-libs/libcpath
dev-libs/libfguid
dev-libs/libfdatetime
dev-libs/libcstring
dev-libs/libcsystem
dev-libs/libfcache
dev-libs/libfdata
dev-libs/libfvalue
dev-libs/libfwnt
dev-libs/libfmapi
dev-libs/libsmdev
```
