### ISSUE TITLE
net-misc/tcpick-0.2.1-r1 fails to emerge with loop.c:(.text+0x1d3): undefined reference to `verify'

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#262]
Thanks.

[environment.txt](https://github.com/pentoo/pentoo-overlay/files/1628787/environment.txt)

[emerge-pqv.txt](https://github.com/pentoo/pentoo-overlay/files/1628786/emerge-pqv.txt)

[emerge-info.txt](https://github.com/pentoo/pentoo-overlay/files/1628785/emerge-info.txt)
[build.log](https://github.com/pentoo/pentoo-overlay/files/1628783/build.log)

**Comment by blshkv** [comment]
this is abandoned tool (last release in 2005!!!) and should not be used to be honest. Wireshark does a better job. However, I applied random patches from debian and it compiled. I'll let it live because I'm lazy to remove it ;-)
