### ISSUE TITLE
gOSINT integration

### ISSUE THREAD

**Issue by Nhoya** [pentoo/pentoo-overlay#263]
Hi guys,
What about integrating gOSINT in the overlay?

https://github.com/Nhoya/gOSINT

**Comment by blshkv** [comment]
ok, this is cute. The tool is 1 week old, has 3 releases and very active.

However, I'm sick and tired of such "one day" frameworks. I will not have time to bump it everyday and you might stop developing it after few months eventually. 

I can see some potentials but I would rather wait until it become more mature or become part of any other existing framework.

**Comment by Nhoya** [comment]
Hi and thanks for the answer,
Thanks for the feedback i'll try to improve the stability of releases and i'll come back when/if it became more mature. 

By the way, just to be clear, the tool exists from Aug 2016, i just started pushing releases last week. 

Thanks again for the answer, see you  soon again i hope 😄
