### ISSUE TITLE
Default Audio selection and multiple monitors

### ISSUE THREAD

**Issue by john44066** [pentoo/pentoo-overlay#267]
Okay, I found GNU Radio Companion. It was abbreviated as GRC (was GRA - my bad). Who would have thought. It seems to work good.

With regard to the audio it is defaulting to my monitor. I don't want it to default to my monitor. I want it to default to HDA Intel PCH, ALC3861. I was able to run VLC Media Player and in the Audio Device dropdown it was set to blank. I selected HDA Intel PCH and was able to get audio okay. I could not find any area in the Applications where I could set my audio to the default HDA In...... How can I do that?

With regard to the monitors I went into display and checked the box for multiple displays. It was suppose to detect my other 3 displays but failed to do so. How to I get all four monitors to work?

Regards,

John

**Comment by blshkv** [comment]
I can't find GRA. What is the package name?

**Comment by john44066** [comment]
Sorry about that - it is GRC in the Development folder.

**Comment by blshkv** [comment]
Pentoo is an overlay (extension) of Gentoo and we don't touch Gentoo stuff usually.
So I suggest to look for a solution at Gentoo's wiki or forum:
https://wiki.gentoo.org/wiki/ALSA
https://wiki.gentoo.org/wiki/PulseAudio
https://bugs.gentoo.org
https://forums.gentoo.org

Just remember that your system is very flexible and you are free to re-compile it with or without any specific package (I do not have pulseaudio in my setup for example).

As always, do let us know if you will find a fix which could be implemented by default.
We will be happy to push it for everybody (or push it to upstream).

**Comment by john44066** [comment]
Ok, thank very much for that information.
