### ISSUE TITLE
net-analyzer/blindelephant-9999 fails smart-live-rebuild

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#272]
[build.log.gz](https://github.com/pentoo/pentoo-overlay/files/1730158/build.log.gz)
[emerge-info.txt](https://github.com/pentoo/pentoo-overlay/files/1730159/emerge-info.txt)
[emerge-pqv.txt](https://github.com/pentoo/pentoo-overlay/files/1730160/emerge-pqv.txt)
[environment.txt](https://github.com/pentoo/pentoo-overlay/files/1730161/environment.txt)

http://blindelephant.sourceforge.net/
->
"Project web is currently offline pending the final migration of its data to our new datacenter."

Actual error:
svn: E170013: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/blindelephant/code/trunk'
svn: E000111: Error running context: Connection refused

etc.

**Comment by blshkv** [comment]
It looks like they have migrated to github

**Comment by blshkv** [comment]
I think Wappalyzer or WhatWeb do a better job and should be used instead
