### ISSUE TITLE
app-forensics/libewf removal in Gentoo

### ISSUE THREAD

**Issue by a17r** [pentoo/pentoo-overlay#274]
This package is currently pending removal in Gentoo because no one volunteered to (proxy-)maintain it. It only caught my attention because I was looking at a testdisk-7.1 version bump (for dropping the Qt4 revdep).

https://bugs.gentoo.org/547418

@blshkv: At a first glance your ebuild in pentoo-overlay looks technically sound. I thought it would make sense to drop you a note on this since you are already doing the work in pentoo-overlay on GitHub, you may as well consider submitting your libewf ebuilds to Gentoo, which under gentoo-proxy-maint imo is a straightforward way to directly contribute via PRs.

**Comment by blshkv** [comment]
I would be happy if Gentoo could take it over, but I don't see the point in proxy maintenaning. It's basically a double work for me. Use pentoo overlay if you need out tools :)

**Comment by blshkv** [comment]
Hi again, I looked at the issue in the morning and here is the conclusion.

The current libewf situation is a mess. This library does NOT provide a stable API and not ready for production (forensic especially) use in general. Every new "experimental" or "alpha" version of libewf might change an API and forensic tools must review and test it. See guymanager, for example:
https://sourceforge.net/p/guymager/feature-requests/11/ . Its author decided to fork libewf so he can rely on it.

So a libewf maintainer must make sure that all tools are compatible (or compile at least) with the current version and monitor upstreams or/and apply upstream/random patches. However, this mess should not be kept in the main tree and deserve removal.

I will try to maintain it in Pentoo but use it on your own risk.
