### ISSUE TITLE
net-wireless/op25 fails to build due to cmake/Python-related problems

### ISSUE THREAD

**Issue by WGH-** [pentoo/pentoo-overlay#278]
The basic symptom is that cmake says
```
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS) (Required is at least version "2")
```
and then proceeds to use plain `python`, which usually is `python3` on modern systems, which causes prompt syntax errors and build failure.

Interestingly enough, this does not happen when you clone the repository and build the code outside ebuild system.

I compared cmake traces. and found what causes the problem.

Apparently, when cmake is running under ebuild, it behaves differently with regard to python versions. There is this Gentoo-specific patch in mainline Portage tree (`/usr/portage/dev-util/cmake/files/cmake-3.9.0_rc2-FindPythonInterp.patch`):
```diff
From 325652950ecc5d72f0a6ac843889a048fe9e32cf Mon Sep 17 00:00:00 2001
From: Lars Wendler <polynomial-c@gentoo.org>
Date: Fri, 9 Jun 2017 02:08:03 +0200
Subject: [PATCH] Don't mess with python versions too much

---
 Modules/FindPythonInterp.cmake | 8 +++++++-
 1 file changed, 7 insertions(+), 1 deletion(-)

diff --git a/Modules/FindPythonInterp.cmake b/Modules/FindPythonInterp.cmake
index 64b98a879..73bd35b56 100644
--- a/Modules/FindPythonInterp.cmake
+++ b/Modules/FindPythonInterp.cmake
@@ -64,6 +64,11 @@ if(PythonInterp_FIND_VERSION)
 else()
     set(_PYTHON_FIND_OTHER_VERSIONS ${_PYTHON3_VERSIONS} ${_PYTHON2_VERSIONS} ${_PYTHON1_VERSIONS})
 endif()
+
+if (CMAKE_GENTOO_BUILD OR CMAKE_BUILD_TYPE STREQUAL Gentoo)
+    set(_Python_NAMES python)
+endif()
+
 find_program(PYTHON_EXECUTABLE NAMES ${_Python_NAMES})
 
 # Set up the versions we know about, in the order we will search. Always add
@@ -88,12 +93,13 @@ unset(_PYTHON2_VERSIONS)
 unset(_PYTHON3_VERSIONS)
 
 # Search for newest python version if python executable isn't found
-if(NOT PYTHON_EXECUTABLE)
+if(NOT PYTHON_EXECUTABLE AND NOT (CMAKE_GENTOO_BUILD OR CMAKE_BUILD_TYPE STREQUAL Gentoo))
     foreach(_CURRENT_VERSION IN LISTS _Python_VERSIONS)
       set(_Python_NAMES python${_CURRENT_VERSION})
       if(CMAKE_HOST_WIN32)
         list(APPEND _Python_NAMES python)
       endif()
+
       find_program(PYTHON_EXECUTABLE
         NAMES ${_Python_NAMES}
         PATHS
-- 
2.13.1

```

So when cmake runs outside of ebuild, `_Python_NAMES` contains the list of all available Python interpreters (and `GrPython` cmake module bundled with op25 successfully selects `python2`), and in case of ebuild,  `_Python_NAMES` contains just `python`.

I weren't able to figure out how to fix this. I don't even know how this is supposed to work.

**Comment by WGH-** [comment]
I've found my own old ebuild for some other GNU Radio module, which builds correctly. The difference was pretty easy to spot.

In order to fix this, one should change `inherit python-r1` to `inherit python-single-r1`. PR incoming.

**Comment by blshkv** [comment]
FYI, there is also a much bigger problem with this badly supported package, see the following fix as well:
c0d1f5c5ea2503f554ed07375c656d7c5bcad2f4

**Comment by WGH-** [comment]
Haha, yes, I know, I wanted to submit it as a follow-up PR :)
