### ISSUE TITLE
digest problem with scapy-2.4.0_p20180626

### ISSUE THREAD

**Issue by tothi** [pentoo/pentoo-overlay#287]
net-analyzer/scapy-2.4.0_p20180626 is a github snapshot of [scapy](https://github.com/secdev/scapy) as of commit [c32159d454608739dc39c08f5775b8e17066c85e](https://github.com/secdev/scapy/archive/c32159d454608739dc39c08f5775b8e17066c85e.zip).

the file size and hash in the Manifest file seems to be wrong (or maybe the commit archive has been changed since the pentoo bump?).

anyway, emerging with a recreated digest it simply works.

i recommend updating the Manifest file.

**Comment by blshkv** [comment]
that is strange, the commit not suppose to change. I have compared both tar.gz files, here is the diff:
```
--- scapy-c32159d454608739dc39c08f5775b8e17066c85e.old/scapy/__init__.py 2018-06-25 15:45:38.000000000 +0800
+++ scapy-c32159d454608739dc39c08f5775b8e17066c85e/scapy/__init__.py    2018-06-25 15:45:38.000000000 +0800
@@ -78,7 +78,7 @@
         except:
             # Rely on git archive "export-subst" git attribute.
             # See 'man gitattributes' for more details.
-            git_archive_id = 'c32159d45  (HEAD -> master)'
+            git_archive_id = 'c32159d45 '
             sha1 = git_archive_id.strip().split()[0]
             match = re.search('tag:(\\S+)', git_archive_id)
             if match:
```

Doesn't look suspicious

**Comment by blshkv** [comment]
the strange thing is that ```git_archive_id = 'c32159d45  (HEAD -> master)'``` is back later.
Ok, let's bump a next commit instead.

**Comment by tothi** [comment]
yeah, the diff doesnt look suspicious. but youre right, we should check the diffs carefully. changes in the commits back in time shouldnt be normal. in particular since [gentoo github hack](https://infra-status.gentoo.org/notice/20180629-github) ;)

**Comment by blshkv** [comment]
Here we go again : https://github.com/pentoo/pentoo-overlay/commit/e4f0b1ddc16f385b9c9c31558bc4728e68209da8  need to report to upstream

**Comment by ZeroChaos-** [comment]
GitHub regenerates tarballs sometimes, I have no idea why, but it is
typically rare.

This appears to be the first instance I know of where it changed twice.
