### ISSUE TITLE
[PlutoSDR] please add PlutoSDR support

### ISSUE THREAD

**Issue by beta-tester** [pentoo/pentoo-overlay#288]
hi,

i have a [PlutoSDR](https://wiki.analog.com/university/tools/pluto/users) ([...](http://www.analog.com/en/education/education-library/videos/5765544380001.html)) and
it would be very nice to have all [PlutoSDR drivers](https://wiki.analog.com/university/tools/pluto/drivers/linux) available in Pentoo out of the box
and PlutoSDR "_plugins_" for [GNURadio](https://wiki.analog.com/resources/tools-software/linux-software/gnuradio), Gqrx, [SoapySDR](https://github.com/jocover/SoapyPlutoSDR)

**Comment by blshkv** [comment]
not exactly sure how can we help. The [PlutoSDR drivers] (https://wiki.analog.com/university/tools/pluto/drivers/linux)  page says "On most modern distributions - these will be installed/compiled by default".

As for the plugins, you need to contact each software individually and ask them to support your card.

We will be happy to include it to Pentoo after that.

**Comment by beta-tester** [comment]
> The PlutoSDR drivers page says "On most modern distributions - these will be installed/compiled by default" and the listed (standard) drivers are enabled in our kernel.

yes, the kernel modules what are required to run the iio libraries/tools are in the most kernels.
but you need the libiio, libad6361 libraries to get the PlutoSDR run and to get the PlutoSDR working in GNURadio you need the gr-iio plugin.

i am running Pentoo always from the LiveDVD (booted via [PXE boot](https://github.com/beta-tester/RPi-PXE-Server)). that means every time i want to use my PlutoSDR under Pentoo's GNURadio i have to compile those stuff and that takes 25 minutes minimum on my computer.

that is the reason, why it would be nice to have it already included in Pentoo LiveDVD out of the box.

here the steps/script i run to get PlutoSDR work under Pentoo's GNURadio:
```
#!/bin/bash


# dev environment
sudo emerge --noreplace git cmake libxml2 dev-libs/libxml2 swig net-wireless/gnuradio bison flex doxygen;


# libiio / libiio-utils
cd;
git clone --depth 1 https://github.com/analogdevicesinc/libiio.git;
mkdir ~/libiio/build/;
cd ~/libiio/build/;
cmake -DCMAKE_INSTALL_PREFIX=/usr ..;
make;
sudo make install;


# rule to use PlutoSDR without root
sudo sh -c "cat << EOF > /etc/udev/rules.d/53-adi-plutosdr-usb.rules
# allow "plugdev" group read/write access to ADI PlutoSDR devices
# DFU Device
SUBSYSTEM=="usb", ATTRS{idVendor}=="0456", ATTRS{idProduct}=="b674", MODE="0664", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="2fa2", ATTRS{idProduct}=="5a32", MODE="0664", GROUP="plugdev"
# SDR Device
SUBSYSTEM=="usb", ATTRS{idVendor}=="0456", ATTRS{idProduct}=="b673", MODE="0664", GROUP="plugdev"
SUBSYSTEM=="usb", ATTRS{idVendor}=="2fa2", ATTRS{idProduct}=="5a02", MODE="0664", GROUP="plugdev"
# tell the ModemManager (part of the NetworkManager suite) that the device is not a modem, 
# and don't send AT commands to it
SUBSYSTEM=="usb", ATTRS{idVendor}=="0456", ATTRS{idProduct}=="b673", ENV{ID_MM_DEVICE_IGNORE}="1"
SUBSYSTEM=="usb", ATTRS{idVendor}=="2fa2", ATTRS{idProduct}=="5a02", ENV{ID_MM_DEVICE_IGNORE}="1"
EOF";
sudo udevadm control --reload-rules;


# libas9361-iio
cd;
git clone --depth 1 https://github.com/analogdevicesinc/libad9361-iio.git;
mkdir ~/libad9361-iio/build/;
cd ~/libad9361-iio/build/;
cmake -DCMAKE_INSTALL_PREFIX=/usr ..;
make;
sudo make install;


# gr-iio for GNURadio
cd;
git clone --depth 1 https://github.com/analogdevicesinc/gr-iio.git;
mkdir ~/gr-iio/build/;
cd ~/gr-iio/build/;
cmake -DCMAKE_INSTALL_PREFIX=/usr ..;
make;
sudo make install;


sudo ldconfig;

```

all the stuff is from Analog Devices Inc. itself, so i think this is the official way how to do it.
for debian/ubuntu distributions there are packages for libiio-utils available but not for Pentoo/Gentoo distribution as far as i could see.

and the gr-iio plugin for GNURadio there is no other way as to compile it.

i have tested the install script under "pentoo-amd64-hardened-2018.0_RC6.3.iso"
and there it works.

i have tried "pentoo-amd64-hardened-2018.0_RC7_pre20180703.iso" as well, but there GNURadio is broken at all. so i couldn't test PlutoSDR under its GNURadio application there but iio_info and the other libiio stuff is working.

**Comment by blshkv** [comment]
ok, that is much more useful info. By right, you should never run compile commands manually under Gentoo. The best way to write ebuilds for each software.
There is gr-iio ebuild in the gnuradio overlay (http://gpo.zugaina.org/net-wireless/gr-iio) and may be others. I will have a look at it.

**Comment by blshkv** [comment]
btw, please open a separate bug report about "pentoo-amd64-hardened-2018.0_RC7_pre20180703.iso" and gnuradio problem. It should be working fine.

**Comment by beta-tester** [comment]
> ok, that is much more useful info. By right, you should never run compile commands manually under Gentoo. The best way to write ebuilds for each software.
> There is gr-iio ebuild in the gnuradio overlay (http://gpo.zugaina.org/net-wireless/gr-iio) and may be others. I will have a look at it.
> 

i am not that familiar with Gentoo like distributions.
thank you for the info.

**Comment by blshkv** [comment]
Can you confirm that gr-iio from gnuradio overlay works? Ill push it to pentoo then

**Comment by beta-tester** [comment]
yes, i can confirm that gr-iio from "gnuradio" (net-libs/libiio-9999::gnuradio, net-libs/libad9361-9999::gnuradio, net-wireless/gr-iio-9999::gnuradio)
is working with gnuradio 3.7.13.3 on pentoo-amd64-hardened-2018.0_RC7.2.iso
(tested 2018-07-22)

is can use PlutoSDR in gnuradio to receive and send at the same time.

i did the folowing steps:
```
sudo emerge --sync

# to add gnuradio "overlay"
sudo layman -a gnuradio

# to unmask masked packages
sudo emerge --autounmask --autounmask-write gr-iio
sudo dispatch-conf
# 2x [u] = use-new

# to finally install gr-iio
sudo emerge gr-iio
```

**Comment by blshkv** [comment]
Also, https://github.com/pentoo/pentoo-overlay/commit/6c15952e6a6a3c6561edf6eb9c40bef468cbcd07

Ok, it is not included by default yet, but it should be easier to install it now. I dont we need IIO blocks by default since it is a very specific area. Please ping if you think overwise.

**Comment by beta-tester** [comment]
hello, it's me again...

thank you for your work!

... but, i just tried out the **pentoo-full-amd64-hardened-2018.0_RC8_p20180828.iso**
and tried to install **gr-iio**, by simple do `sudo emerge gr-iio`.
the install process looks like to succeed, but in gnuradio-companion the gr-iio plugin will not appear.
the iio libraries itself will install correct, because i can run the `iio_info -n 192.168.2.1` command successfuly.
only the gnuradio plugin install part seems to not working correctly.

```
pentoo@pentoo ~ $ sudo emerge gr-iio

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild  N    ~] net-wireless/gr-iio-0.3::pentoo  54 KiB
[ebuild  N    ~]  net-libs/libad9361-iio-0.1-r1::pentoo  27 KiB
[ebuild  N    ~]   net-libs/libiio-0.15::pentoo  189 KiB

Total: 3 packages (3 new), Size of downloads: 269 KiB

>>> Verifying ebuild manifests
>>> Emerging (1 of 3) net-libs/libiio-0.15::pentoo
>>> Installing (1 of 3) net-libs/libiio-0.15::pentoo
>>> Emerging (2 of 3) net-libs/libad9361-iio-0.1-r1::pentoo
>>> Installing (2 of 3) net-libs/libad9361-iio-0.1-r1::pentoo
>>> Emerging (3 of 3) net-wireless/gr-iio-0.3::pentoo
>>> Installing (3 of 3) net-wireless/gr-iio-0.3::pentoo
>>> Recording net-wireless/gr-iio in "world" favorites file...
>>> Jobs: 3 of 3 complete                           Load avg: 1.08, 0.81, 0.45
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

pentoo@pentoo ~ $ iio_info -n 192.168.2.1
Library version: 0.15 (git tag: v0.15)
Compiled with backends: local xml ip usb
IIO context created with network backend.
Backend version: 0.15 (git tag: v0.15  )
Backend description string: 192.168.2.1 Linux (none) 4.9.0-10475-g2398d50 #263 SMP PREEMPT Mon Aug 20 15:30:08 CEST 2018 armv7l
IIO context has 8 attributes:
	hw_model: Analog Devices PlutoSDR Rev.B (Z7010-AD9363)
	fw_version: v0.29
...

pentoo@pentoo ~ $ gnuradio-companion 
<<< Welcome to GNU Radio Companion 3.7.13.4 >>>
```
in gnuradio, i  have NO **Industrial IO**, and  when i search for "Pluto" i get nothing.


while when triying **pentoo-full-amd64-hardened-2018.0_RC8.iso**
i can install **gr-iio** successfuly so, that it will appear in gnuradio-companion correctly

```
pentoo@pentoo ~ $ sudo emerge layman

Local copy of remote index is up-to-date and will be used.

Local copy of remote index is up-to-date and will be used.

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild  N     ] app-portage/layman-2.4.2-r1::gentoo  USE="git gpg mercurial sqlite subversion sync-plugin-portage -bazaar -cvs -darcs (-g-sorcery) -squashfs {-test}" PYTHON_TARGETS="python3_6 (-pypy) -python2_7 -python3_4 -python3_5" 135 KiB
[ebuild  N     ]  dev-vcs/mercurial-4.6.2::gentoo  USE="-bugzilla -emacs -gpg {-test} -tk" PYTHON_TARGETS="python2_7" 6,258 KiB
[ebuild  N     ]  dev-python/pyGPG-0.2::gentoo  PYTHON_TARGETS="python2_7 python3_6 -python3_4 -python3_5" 16 KiB

Total: 3 packages (3 new), Size of downloads: 6,408 KiB

>>> Verifying ebuild manifests
>>> Running pre-merge checks for app-portage/layman-2.4.2-r1
>>> Emerging (1 of 3) dev-python/pyGPG-0.2::gentoo
>>> Emerging (2 of 3) dev-vcs/mercurial-4.6.2::gentoo
>>> Installing (1 of 3) dev-python/pyGPG-0.2::gentoo
>>> Installing (2 of 3) dev-vcs/mercurial-4.6.2::gentoo
>>> Emerging (3 of 3) app-portage/layman-2.4.2-r1::gentoo
>>> Installing (3 of 3) app-portage/layman-2.4.2-r1::gentoo
>>> Recording app-portage/layman in "world" favorites file...
>>> Jobs: 3 of 3 complete                           Load avg: 1.61, 1.08, 0.49

 * Messages for package dev-python/pyGPG-0.2:

 * There may be some python 3 compatibility issues still.
 * Please help debug/fix/report them in github or bugzilla.

 * Messages for package dev-vcs/mercurial-4.6.2:

 * If you want to convert repositories from other tools using convert
 * extension please install correct tool:
 *   dev-vcs/cvs
 *   dev-vcs/darcs
 *   dev-vcs/git
 *   dev-vcs/monotone
 *   dev-vcs/subversion
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

pentoo@pentoo ~ $ sudo layman -S

 * Fetching remote list...
 * Warning: an installed db file was not found at: ['/var/lib/layman/cache_930c3ed4a5f89f74fd810585751a06e3.xml']
 * Fetch Ok

 * Syncing selected overlay(s)...

pentoo@pentoo ~ $ sudo layman -a gnuradio

 * Adding overlay...
 * Overlay "gnuradio" is not official. Continue installing? [y/n]: y
 * Running Git... # ( cd /var/lib/layman  && /usr/bin/git clone https://github.com/hololeap/gentoo-gnuradio /var/lib/layman/gnuradio )
Cloning into '/var/lib/layman/gnuradio'...
remote: Counting objects: 1155, done.
remote: Total 1155 (delta 0), reused 0 (delta 0), pack-reused 1155
Receiving objects: 100% (1155/1155), 213.78 KiB | 558.00 KiB/s, done.
Resolving deltas: 100% (506/506), done.
 * Running Git... # ( cd /var/lib/layman/gnuradio  && /usr/bin/git config user.name "layman" )
 * Running Git... # ( cd /var/lib/layman/gnuradio  && /usr/bin/git config user.email "layman@localhost" )
 * Successfully added overlay(s) gnuradio.

pentoo@pentoo ~ $ sudo emerge --autounmask --autounmask-write gr-iio

Local copy of remote index is up-to-date and will be used.

Local copy of remote index is up-to-date and will be used.

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild  N    #] net-wireless/gr-iio-9999:0/9999::gnuradio  USE="-doc" PYTHON_TARGETS="python2_7" 0 KiB
[ebuild  N    #]  net-libs/libad9361-9999:0/9999::gnuradio  0 KiB
[ebuild  N    *]   net-libs/libiio-9999:0/9999::gnuradio  0 KiB

Total: 3 packages (3 new), Size of downloads: 0 KiB

The following keyword changes are necessary to proceed:
 (see "package.accept_keywords" in the portage(5) man page for more details)
# required by net-wireless/gr-iio-9999::gnuradio
# required by gr-iio (argument)
=net-libs/libad9361-9999 **
# required by net-wireless/gr-iio-9999::gnuradio
# required by gr-iio (argument)
=net-libs/libiio-9999 **
# required by gr-iio (argument)
=net-wireless/gr-iio-9999 **

The following mask changes are necessary to proceed:
 (see "package.unmask" in the portage(5) man page for more details)
# required by net-wireless/gr-iio-9999::gnuradio
# required by gr-iio (argument)
# /var/lib/layman/gnuradio/profiles/package.mask:
# multilib-strict check failed!
=net-libs/libad9361-9999
# required by gr-iio (argument)
# /var/lib/layman/gnuradio/profiles/package.mask:
# Depends on libad9361
=net-wireless/gr-iio-9999

NOTE: The --autounmask-keep-masks option will prevent emerge
      from creating package.unmask or ** keyword changes.

Autounmask changes successfully written.

 * IMPORTANT: 2 config files in '/etc/portage' need updating.
 * See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
 * sections of the emerge man page to learn how to update config files.
pentoo@pentoo ~ $ sudo dispatch-conf

--- /tmp/tmpmsfl3frv/0	2018-08-31 06:19:11.979007651 +0000
+++ /etc/portage/._cfg0000_package.accept_keywords	2018-08-31 06:19:07.791007596 +0000
@@ -1 +1,8 @@
-/dev/null
+# required by net-wireless/gr-iio-9999::gnuradio
+# required by gr-iio (argument)
+=net-libs/libad9361-9999 **
+# required by net-wireless/gr-iio-9999::gnuradio
+# required by gr-iio (argument)
+=net-libs/libiio-9999 **
+# required by gr-iio (argument)
+=net-wireless/gr-iio-9999 **

>> (1 of 2) -- /etc/portage/package.accept_keywords
>> q quit, h help, n next, e edit-new, z zap-new, u use-new
   m merge, t toggle-merge, l look-merge:  
u

--- /tmp/tmpbo7iyjd6/0	2018-08-31 06:19:19.015007743 +0000
+++ /etc/portage/._cfg0000_package.unmask	2018-08-31 06:19:07.792007596 +0000
@@ -1 +1,9 @@
-/dev/null
+# required by net-wireless/gr-iio-9999::gnuradio
+# required by gr-iio (argument)
+# /var/lib/layman/gnuradio/profiles/package.mask:
+# multilib-strict check failed!
+=net-libs/libad9361-9999
+# required by gr-iio (argument)
+# /var/lib/layman/gnuradio/profiles/package.mask:
+# Depends on libad9361
+=net-wireless/gr-iio-9999

>> (2 of 2) -- /etc/portage/package.unmask
>> q quit, h help, n next, e edit-new, z zap-new, u use-new
   m merge, t toggle-merge, l look-merge:  
u

pentoo@pentoo ~ $ sudo emerge gr-iio

Local copy of remote index is up-to-date and will be used.

Local copy of remote index is up-to-date and will be used.

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild  N    #] net-wireless/gr-iio-9999:0/9999::gnuradio  USE="-doc" PYTHON_TARGETS="python2_7" 0 KiB
[ebuild  N    #]  net-libs/libad9361-9999:0/9999::gnuradio  0 KiB
[ebuild  N    *]   net-libs/libiio-9999:0/9999::gnuradio  0 KiB

Total: 3 packages (3 new), Size of downloads: 0 KiB

>>> Verifying ebuild manifests
>>> Emerging (1 of 3) net-libs/libiio-9999::gnuradio
>>> Installing (1 of 3) net-libs/libiio-9999::gnuradio
>>> Emerging (2 of 3) net-libs/libad9361-9999::gnuradio
>>> Installing (2 of 3) net-libs/libad9361-9999::gnuradio
>>> Emerging (3 of 3) net-wireless/gr-iio-9999::gnuradio
>>> Installing (3 of 3) net-wireless/gr-iio-9999::gnuradio
>>> Recording net-wireless/gr-iio in "world" favorites file...
>>> Jobs: 3 of 3 complete                           Load avg: 1.21, 0.91, 0.57
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

pentoo@pentoo ~ $ iio_info -n 192.168.2.1
Library version: 0.15 (git tag: c80412c)
Compiled with backends: local xml ip usb
IIO context created with network backend.
Backend version: 0.15 (git tag: v0.15  )
Backend description string: 192.168.2.1 Linux (none) 4.9.0-10475-g2398d50 #263 SMP PREEMPT Mon Aug 20 15:30:08 CEST 2018 armv7l
IIO context has 8 attributes:
	hw_model: Analog Devices PlutoSDR Rev.B (Z7010-AD9363)
	hw_model_variant: 1
...

pentoo@pentoo ~ $ gnuradio-companion 
<<< Welcome to GNU Radio Companion 3.7.13.4 >>>
```
in gnuradio, i  have **Industrial IO**, and  when i search for "Pluto" i get a **Pluto Sink** and a **Pluto Source** as search result.

**Comment by blshkv** [comment]
Please try to merge the latest 9999 from pentoo and let me know results

**Comment by beta-tester** [comment]
i am not sure, if i understand you correctly with 9999 from pentoo?...
i shall try to do the following on the new beta iso ?
```
sudo emerge layman
sudo layman -S
sudo layman -a gnuradio
sudo emerge --autounmask --autounmask-write net-libs/libiio::gnuradio net-libs/libad9361::gnuradio net-wireless/gr-iio::gnuradio
sudo dispatch-conf
sudo emerge net-libs/libiio::gnuradio net-libs/libad9361::gnuradio net-wireless/gr-iio::gnuradio
gnuradio-companion 
```
... this will install the gr-iio correctly to gnuradio. i can see Industrial IO with Pluto Sink and Pluto Source.

if you didn't mean that, please give me detailed advise what i have to do.

**Comment by blshkv** [comment]
From your log, you are installing net-wireless/gr-iio-0.3::pentoo and net-wireless/gr-iio-9999::gnuradio including deps. I suggested to install 9999:pentoo

**Comment by blshkv** [comment]
You can switch profile to bleeding btw, it should have required keywords

**Comment by ZeroChaos-** [comment]
if you confirm working version of this stuff I will have them moved into gentoo so everyone benefits.  I want plutosdr support but no way to test.

**Comment by blshkv** [comment]
my bad, missed a very obvious issue. Please open a new bug if any problems

**Comment by beta-tester** [comment]
@blshkv  & @ZeroChaos- 
yes, thank you very much... you updated ebuild of gr-iio is working as expected now ! 👍 
i tested it and it works with PLutoSDR hardware.
i can see and work with **Industrial IO** plugin in gnuradio-companion with its blocks **Pluto Source** to receive and **Pluto Sink** to transmit.

```
pentoo@pentoo ~ $ sudo emerge gr-iio

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.


These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild  N    ~] net-wireless/gr-iio-0.3-r1::pentoo  PYTHON_TARGETS="python2_7" 54 KiB
[ebuild  N    ~]  net-libs/libad9361-iio-0.1-r1::pentoo  27 KiB
[ebuild  N    ~]   net-libs/libiio-0.15::pentoo  189 KiB

Total: 3 packages (3 new), Size of downloads: 269 KiB

>>> Verifying ebuild manifests
>>> Emerging (1 of 3) net-libs/libiio-0.15::pentoo
>>> Installing (1 of 3) net-libs/libiio-0.15::pentoo
>>> Emerging (2 of 3) net-libs/libad9361-iio-0.1-r1::pentoo
>>> Installing (2 of 3) net-libs/libad9361-iio-0.1-r1::pentoo
>>> Emerging (3 of 3) net-wireless/gr-iio-0.3-r1::pentoo
>>> Installing (3 of 3) net-wireless/gr-iio-0.3-r1::pentoo
>>> Recording net-wireless/gr-iio in "world" favorites file...
>>> Jobs: 3 of 3 complete                           Load avg: 1.32, 1.13, 0.58
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.

 * IMPORTANT: 17 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.

pentoo@pentoo ~ $ gnuradio-companion 
<<< Welcome to GNU Radio Companion 3.7.13.4 >>>

Block paths:
	/usr/share/gnuradio/grc/blocks
/usr/lib64/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py:16629: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")

Generating: '/home/pentoo/top_block.py'

Executing: /usr/bin/python2.7 -u /home/pentoo/top_block.py

/home/pentoo/.gnuradio/prefs/vmcircbuf_default_factory: No such file or directory
vmcircbuf_createfilemapping: createfilemapping is not available

>>> Done

Generating: '/home/pentoo/top_block.py'

Executing: /usr/bin/python2.7 -u /home/pentoo/top_block.py


>>> Done

Generating: '/home/pentoo/top_block.py'

Executing: /usr/bin/python2.7 -u /home/pentoo/top_block.py


>>> Done
pentoo@pentoo ~ $ 
```

**Comment by ZeroChaos-** [comment]
So, which version of everything do I need to move over to Gentoo for this
to work?

**Comment by beta-tester** [comment]
> So, which version of everything do I need to move over to Gentoo for this to work?

you mean ::gnuradio overlay
`sudo emerge net-libs/libiio::gnuradio net-libs/libad9361::gnuradio net-wireless/gr-iio::gnuradio`

or ::pentoo
`sudo emerge net-libs/libiio::pentoo net-libs/libad9361::pentoo net-wireless/gr-iio::pentoo`

both are working to me.

when i have to install it by hand, i prefered the pentoo one, because of less steps to me, to install.
but when integrating it to ::gentoo i can't give suggestions - my knowledge is too weak in gentoo/pentoo - no knowledge if those ebuilds are different or equal.

**Comment by blshkv** [comment]
ZC  please double check dependencies, may be not accurate

**Comment by beta-tester** [comment]
hi, only one question...
i tried pentoo-full-amd64-hardened-2018.0_RC8_p20180906.iso
net-libs/**libiio** and net-libs/**libad9361** are now installed out of the box (e.g. iio_info works out of the box).
but in gnuradio there is no **Industial IO**/**PlutoSDR** plugin...
to have the **PlutoSDR** plugin in gnuradio it is still necessary to do `sudo emerge gr-iio`... is that right?

(or was it maybe an issue of installation sequence / installing gr-iio before gnuradio-companion was installed for the iso)

**Comment by blshkv** [comment]
I suspect this is because your had to mess around with libraries and you might installed them manually without -1 flag. You should not install any dependency normally. They will be installed/uninstalled automatically when you install/uninstall the main package.

```grep libs /var/lib/portage/world``` review this list and any other deps, and delete all dependency.

And yes, you still have to run ```emerge gr-iio``` since we do not install it by default.

**Comment by blshkv** [comment]
```
[nomerge       ] net-wireless/qspectrumanalyzer-2.2.0 
[nomerge       ]  net-wireless/soapy_power-1.6.1-r1 
[nomerge       ]   dev-python/simplesoapy-1.5.1-r1 
[nomerge       ]    net-wireless/soapysdr-0.6.1-r1 [0.6.1] USE="plutosdr%*" 
[ebuild  N    ~]     net-wireless/soapyplutosdr-0.0_p20180825 
[ebuild  N    ~]      net-libs/libad9361-iio-0.1-r2 
[ebuild  N    ~]       net-libs/libiio-0.15-r1  USE="aio avahi"
```

the last two are required by the latest soapyplutosdr that's why there are installed by default

**Comment by beta-tester** [comment]
> And yes, you still have to run `emerge gr-iio` since we do not install it by default.

ok, thank you for your answer.

> no idea why libiio/libad9361 are installed. They shouldn't

i don't know if it is really installed, but i know `iio_info -n 192.168.2.1` is working out of the box now. 
so i assumed that libiio and libad9361 are installed by default now.
and when i do `emerge gr-iio`, no other dependencies/packages are installed except of gr-iio itself.
(in the past libiio and libad9361 were installed as dependency packages).

i don't want to make more trouble here...
thank you that you made the installation of **gr-iio** as easy as possible to me. :+1:

**Comment by beta-tester** [comment]
> > the last two are required by the latest soapyplutosdr that's why there are installed by default
> 
> that means i am also able to use soapyplutosdr... for example in gqrx... cool... that i have to try

cool, i can use gqrx with "Soapy" to use my PlutoSDR now... it works out-of-the-box... very nice :+1:

**Comment by GlenLangston** [comment]
Hi
Very interesting discussion you've been having.
Could you please put a copy of your succesful firmware images on line?
Thansk - Glen
