### ISSUE TITLE
accept-keywords: open-vm-tools needs masked "dev-libs/xml-security-c"

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-overlay#291]
> !!! The following update has been skipped due to unsatisfied dependencies:
> 
> app-emulation/open-vm-tools:0
> 
>   selected: (app-emulation/open-vm-tools-10.1.15:0/0::gentoo, ebuild scheduled for merge)
>   skipped: (app-emulation/open-vm-tools-10.2.5:0/0::gentoo, ebuild scheduled for merge) (see unsatisfied dependency below)
> 
> !!! All ebuilds that could satisfy "dev-libs/xml-security-c" have been masked.
> !!! One of the following masked packages is required to complete your request:
> - dev-libs/xml-security-c-1.7.3::gentoo (masked by: ~amd64 keyword)
> 
> (dependency required by "app-emulation/open-vm-tools-10.2.5::gentoo[xml-security-c,vgauth]" [ebuild])
> For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.

**Comment by ZeroChaos-** [comment]
merged pr
