### ISSUE TITLE
Beef ebuild not working

### ISSUE THREAD

**Issue by izemmouri** [pentoo/pentoo-overlay#296]
www-apps/beef installs correctly but just executing `beef' yields the following error:
https://paste.pound-python.org/show/Gq6NCENWxYIvUXsK297n/

**Comment by blshkv** [comment]
This is an upstream bug and we are unable to resolve it easily.
Please see https://github.com/beefproject/beef/issues/1590

**Comment by blshkv** [comment]
beef is a mess. It requires random mixture of conflicting libraries, some of them are outdated, unsupported and fails to compile with a modern compiler (v8 javascript library). I have filled all bugs to relevant upstreams and link them up. No idea when (if at all) it can be fixed.

So we cannot fix this either. v8 engine bugs  are way belong of our bandwidth.

**Comment by blshkv** [comment]
ok, upstream was helpful eventually, the latest snapshot works.
There are still few bugs, but the tool is able to start at least
