### ISSUE TITLE
stegosip

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#298]
[stegosip-9999.ebuild.txt](https://github.com/pentoo/pentoo-overlay/files/2207006/stegosip-9999.ebuild.txt)
https://github.com/epinna/Stegosip

useful in hiding Peer to peer/ppp data xfers as normal voip traffic... http, ftp , etc... 

**inherit python-sinlge-r1**
_/facepalm...._

**Comment by blshkv** [comment]
your ebuilds are joke. Please do not provide broken untested ebuilds so I would not waste my time.

**Comment by blshkv** [comment]
This tool is a joke too. Its author published a code for his degree 6 years ago and did touch it since then. We are not going to waste time on it unless somebody will take a GOOD care of it, check/update the code, create a proper pull request with a tested ebuild.
