### ISSUE TITLE
Webshells ebuild?

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#299]
Hi all,

I'd love to see an ebuild that pulls in several webshells like:

- https://tools.kali.org/maintaining-access/webshells, or;
- https://github.com/BlackArch/webshells.

I've never written an ebuild myself but I'm willing to spend some time creating one that, for example, pulls in the latest BlackArch webshells from GitHub.

**Comment by blshkv** [comment]
there are many more:
https://github.com/tennc/webshell
https://github.com/xl7dev/WebShell
https://github.com/tdifg/WebShell

can you check which one is the most useful?

**Comment by gkroon** [comment]
@blshkv Super fast response and ebuild publish, fantastic! Though I'm not familiar with the other 3 repos you mentioned. So unless someone else can confirm their usefulness, I'd hold off until then. :slightly_smiling_face:

**Comment by blshkv** [comment]
I was just happened to be around, and it was easy ;-).

Can you do a little research: download each archive, compare it and justify which one shall we use?

**Comment by blshkv** [comment]
you can always translate online and review the source code

**Comment by blshkv** [comment]
ok, let's go with BlackArch archive as a trusted source then. They are willing to accept new shells so we will be submitting new shells to them if required and bumping versions here.
