### ISSUE TITLE
dev-python/nassl-1.1.3-r1 emerge failure

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#300]
[build.log.gz](https://github.com/pentoo/pentoo-overlay/files/2237902/build.log.gz)
[build.log.txt](https://github.com/pentoo/pentoo-overlay/files/2237903/build.log.txt)
[emerge-info.txt](https://github.com/pentoo/pentoo-overlay/files/2237904/emerge-info.txt)
[emerge-pqv.txt](https://github.com/pentoo/pentoo-overlay/files/2237905/emerge-pqv.txt)
[environment.txt](https://github.com/pentoo/pentoo-overlay/files/2237906/environment.txt)

From the build log:
<snip>
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../x86_64-pc-linux-gnu/bin/ld:bin/openssl-legacy/lin
ux64/libssl.a: file format not recognized; treating as linker script
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../x86_64-pc-linux-gnu/bin/ld:bin/openssl-legacy/lin
ux64/libssl.a:1: syntax error
collect2: error: ld returned 1 exit status
error: command 'x86_64-pc-linux-gnu-gcc' failed with exit status 1
 * ERROR: dev-python/nassl-1.1.3-r1::pentoo failed (compile phase):
</snip>
Google "file format not recognized; treating as linker script" leads to some interesting comments. Seems to be a known issue for downlevel versions.

**Comment by blshkv** [comment]
upgrade to gcc 7 and try again

**Comment by ZeroChaos-** [comment]
I had the same error on gcc 7, it magically resolved after trying to
upgrade world a few times.  All I know is it wasn't rebuilding openssl that
fixed it.

**Comment by blshkv** [comment]
That might be the same bug as reported by Alpine https://github.com/nabla-c0d3/nassl/issues/31.
However, we do build everything from scratch using the provided script, so there is still no solution

**Comment by blshkv** [comment]
can you try to rebuild the latest -r2 version please?

**Comment by bill-e-ghote** [comment]
I upgraded gcc for other reasons, but the failure persists, even with the -r2 version. I did not try a world upgrade yet, as this is a slow AF Oraclebox guest instance.

**Comment by blshkv** [comment]
hm.. can you try to rebuild openssl deps only?

```
RDEPEND=">=app-misc/c_rehash-1.7-r1                                                                                        
        gmp? ( >=dev-libs/gmp-5.1.3-r1[static-libs(+)?,${MULTILIB_USEDEP}] )                                               
        zlib? ( >=sys-libs/zlib-1.2.8-r1[static-libs(+)?,${MULTILIB_USEDEP}] )                                             
        kerberos? ( >=app-crypt/mit-krb5-1.11.4[${MULTILIB_USEDEP}] )"                                                     
DEPEND="${RDEPEND}                                                                                                         
        >=dev-lang/perl-5                                                                                                  
        sctp? ( >=net-misc/lksctp-tools-1.0.12 )
 ```

it might be also something to do with git:
```
dev-vcs/git-2.16.4 (blksha1 curl gpg iconv nls pcre perl python python_targets_python2_7 threads tk webdav)
```

**Comment by bill-e-ghote** [comment]
I tried 'emerge -e --usepkg=n @world' and it failed again on nassl (after emerging 1242 of 1933 ebuilds - ugh). I'll try again with your last suggestion again tonight.

**Comment by bill-e-ghote** [comment]
So re-emerging openssl deps only did not help. nassl emerge is still bombing.

**Comment by blshkv** [comment]
well, there is only a full update left. And I'm willing to push it to the upstream if it will not help.

**Comment by blshkv** [comment]
Can you attach that .so file as well:
/var/tmp/portage/ <somewhere> bin/openssl-legacy/linux64/libssl.a

**Comment by blshkv** [comment]
I think I found it:
```Traceback (most recent call last):                                                                                         
  File "./build_from_scratch.py", line 14, in <module>                                                                     
    from setup import MODERN_OPENSSL_LIB_INSTALL_PATH, CURRENT_PLATFORM, SupportedPlatformEnum, \                          
  File "/var/tmp/portage/dev-python/nassl-1.1.3-r1/work/nassl-1.1.3/setup.py", line 11, in <module>                        
    from setuptools import setup, Extension                                                                                
ImportError: No module named 'setuptools' 
```

Please verify and install if it is missing:
emerge -1 dev-python/setuptools

**Comment by blshkv** [comment]
I'm closing this bug until you update the world, migrate to python3.6 and fix your setuptools.
Please ping here again if it won't fix it.

**Comment by bill-e-ghote** [comment]
OK, so I've built latest kernel, updated world, already have dev-python/setuptools emerged. The only thing missing was that my default python install was 3.5. Switched over to that, and of course the sh*t emerged. Probably that was all that needed to be changed. Oh well.
Thanks for the assistance.

**Comment by blshkv** [comment]
There is a new v2.0 and it got totally new way of building it. Please open a new bug for a new version of something doesn't work
