### ISSUE TITLE
Install fails at 'Install Bootloader' stage - Installing from Live USB

### ISSUE THREAD

**Issue by bl4krat** [pentoo/pentoo-overlay#304]
I'm trying to install pentoo to the HDD from a live USB stick (ver Pentoo 2018.0 RC7.1):

Issue:
Install gets as far as installing the bootloader. I choose 'GRUB2-UEFI' (ie, the only supported option), which fails with error message 'WARNING: The last step returned an error!'. (accurate, but unhelpful).

So i choose 'UEFI' - which returns the same error message.

Options chosen:
clock format - UTC
 Timezone London
Keyboard - UK

manually chosen partitions:
root = /dev/sdb5
other = /dev/sdb6 as swap

distribution copied (without any un-sync'd changes)

profile (whatever this means...???) = 55 - .....amd64/binary

configure:
keymap = 'UK"
mount points (no change made):
  /dev/sdb5 / ext4 defaults 0 1
  /dev/sdb6 none defaults 0 0
resolve.conf, hosts & locale.gen not edited
root password - set appropriately
username changed pentoo >> bl4krat
hostname = pentoo

My system:
Dell Inspiron 15 5577
Intel core I7-7700HQ
8GB ram
128GB ssd
1TB HDD (i'm trying to install to /dev/sdb5 on this drive)
Geforce GTX1050m - 4GB
already installed - win10 & Kali

**Comment by ZeroChaos-** [comment]
you require a fat32 partition for /boot or at minimum /boot/efi.  I'll try to add an earlier warning for that.

Autopartition prevents issues like this for those less familiar with requirements.
