### ISSUE TITLE
pentoo-installer masked

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-overlay#305]
pentoo-installer-9999 has ~amd64 and is not unmasked in profile anywhere.

Please kindly revert 91f52fa276d737e3bbae499c289fee09cc8e2515 or solve it some other way.

**Comment by ZeroChaos-** [comment]
the installer auto update mechanism handles this.  I don't want people installing the installer.  this *IS* solved unless you care to share an actual issue.

**Comment by Wuodan** [comment]
I just can't see any auto-update code, just a check and a warning to user. If I'm missing it, please enlighten me.
And if there is auto-update code: Is it on the rc7.2 iso? If not, how will users update the installer after a sync?

**Comment by ZeroChaos-** [comment]
I'm sorry but once a CD is cut it does not change, so setting the keywords
doesn't fix it either.  New betas already have the fix and will make a
release probably Monday with them.
