### ISSUE TITLE
dev-ruby/sys-proctable -- doc use

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#31]
Hi, here log:

 * Package:    dev-ruby/sys-proctable-0.9.3
 * Repository: pentoo
 * USE:        abi_x86_64 amd64 doc elibc_glibc kernel_linux pie ruby_targets_ruby19 ssp userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Running unpack phase for all ...
 * Unpacking .gem file... ...
 [ ok ]
 * Uncompressing metadata ...
 [ ok ]
 * Unpacking data.tar.gz ...
 [ ok ]
>>> Source unpacked in /var/tmp/portage/dev-ruby/sys-proctable-0.9.3/work
>>> Preparing source in /var/tmp/portage/dev-ruby/sys-proctable-0.9.3/work ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby19 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-ruby/sys-proctable-0.9.3/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-ruby/sys-proctable-0.9.3/work ...
 * Running compile phase for all ...
rake aborted!
Don't know how to build task 'rdoc'

Thx.

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/37
