### ISSUE TITLE
dev-python/yara-python should support several python3 versions

### ISSUE THREAD

**Issue by ikelos** [pentoo/pentoo-overlay#310]
The yara-python ebuild should have a PYTHON_COMPAT line that includes python 3, versions 3.3, 3.4, 3.5 and 3.6 at least (according to the project's [travis file](https://github.com/VirusTotal/yara-python/blame/c9b293ce631d027bedb31c8864b5e52bb3b36d51/.travis.yml)).

I've personally tested it successfully with python 3.6.  Please let me know if you need any further information...

**Comment by blshkv** [comment]
ok, done. Thanks!
