### ISSUE TITLE
AMD Driver

### ISSUE THREAD

**Issue by bala257** [pentoo/pentoo-overlay#311]
Hai
i am New user for pentoo. 
i need a help. witch pentoo ISO better for AMD GPU Support? how to update or install. 
AMD HD7970 Driver??? or AMD RX Vega 64. please help me

**Comment by blshkv** [comment]
We use Gentoo, so look for gentoo documentation.

**Comment by bala257** [comment]
please help for me i try cant give me a link
how to update or install amd  driver

please please please

**Comment by ZeroChaos-** [comment]
Try RC8

**Comment by blshkv** [comment]
So we try our best to make it work out of the box, but you can always verify and tweak it further. Just google for it: http://lmgtfy.com/?q=AMD+HD+7970+%20gentoo+wiki 
It is all well documented.

**Comment by bala257** [comment]
thanks

i download RC8 when i boot usb finally cant login
user name password cant login

maybe  grafix

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by blshkv** [comment]
https://github.com/JPaulMora/Pyrit/issues/573
https://github.com/BlackArch/blackarch-site/issues/98
LoL
