### ISSUE TITLE
How to setup boot Pentoo from a Live ISO file by GRUB2 

### ISSUE THREAD

**Issue by rickyzhang82** [pentoo/pentoo-overlay#313]
I got a large USB stick. I want to add Pentoo live ISO file as one of my multi live Linux image boot by GRUB2.

I placed the ISO file in `/iso/pentoo-full-amd64-hardened-2018.0_RC8.iso`. But I'm not sure pentoo boot command. When I boot from below config, pentoo stuck in asking for root block device.

Can anyone share their experiences on this?

```
menuentry "Live Image: pentoo-full-amd64-hardened-2018.0_RC8.iso" {
    set isofile='/iso/pentoo-full-amd64-hardened-2018.0_RC8.iso'
    loopback loop $isofile
    linux (loop)/isolinux/pentoo root=/dev/ram0 init=/linuxrc nox nodhcp secureconsole overlayfs max_loop=256 nokeymap video=uvesafb:mtrr:3,ywrap,1024x768-16 console=tty0 net.ifnames=0 scsi_mod.use_blk_mq=1 ipv6.autoconf=0 verify looptype=squashfs loop=/image.squashfs cdboot
    initrd (loop)/isolinux/pentoo.igz
}
```

**Comment by blshkv** [comment]
Search for how to boot from iso. It has nothing to do with pentoo

**Comment by ostree** [comment]
typo? "cdboot" - should be cdroot

**Comment by rickyzhang82** [comment]
@blshkv It has everything to do with Pentoo. The parameter for `isolinux/pentoo` is pentoo specific. Different distro has complete different parm or the way to boot from a ISO file.

@ostree  `cdroot` is copied from `grub.cfg` file in Live ISO CD. Below are the original:
```
[Ricky@t20 cdrom]$ cat grub/grub.cfg
#
set default="0"

insmod efi_gop
insmod efi_uga

set lang=en_US
loadfont /grub/unicode.pf2
set gfxmode=auto
insmod gfxterm
terminal_output gfxterm
insmod gfxmenu
loadfont /grub/themes/pentoo/dejavu_10.pf2
loadfont /grub/themes/pentoo/dejavu_12.pf2
loadfont /grub/themes/pentoo/dejavu_14.pf2
loadfont /grub/themes/pentoo/dejavu_16.pf2
loadfont /grub/themes/pentoo/dejavu_bold_14.pf2
insmod png
set theme=/grub/themes/pentoo/theme.txt
export theme

set timeout_style=menu
set timeout="10"
set hidden_timeout_quiet=false

insmod play
play 960 440 1 0 4 440 1

menuentry 'Boot Pentoo LiveCD (kernel: pentoo)' --class gnu-linux --class os {
	linux /isolinux/pentoo root=/dev/ram0 init=/linuxrc nox nodhcp secureconsole overlayfs max_loop=256 dokeymap video=uvesafb:mtrr:3,ywrap,1024x768-16 console=tty0 net.ifnames=0 scsi_mod.use_blk_mq=1 ipv6.autoconf=0 verify looptype=squashfs loop=/image.squashfs cdroot
	initrd /isolinux/pentoo.igz
}
```

**Comment by blshkv** [comment]
@rickyzhang82 it is "cdroot" even in your last post.

Anyway, here is my grub2 config from installed version as well:
```
kernel /kernel-genkernel-x86_64-4.17.11-pentoo root=/dev/sda3 rootfstype=ext4 video=uvesafb:mtrr:3,ywrap,1024x768-16 console=tty1 ro net.ifnames=0
initrd /initramfs-genkernel-x86_64-4.17.11-pentoo
```

**Comment by rickyzhang82** [comment]
Ok. Good catch. I will give a try again.

**Comment by rickyzhang82** [comment]
No, it didn't work. It shows `Media not found` and Could not find root device.

**Comment by blshkv** [comment]
I suspect it has something to do with overlayfs. Try the following:
https://unix.stackexchange.com/questions/206037/how-to-boot-sabayon-linux-with-isoboot-and-overlayfs-parameters

**Comment by rickyzhang82** [comment]
`isoboot` option fix the problem. For record here is my boot option:

```
menuentry "Live Image: pentoo-full-amd64-hardened-2018.0_RC8.iso" {
    set isofile='/iso/pentoo-full-amd64-hardened-2018.0_RC8.iso'
    loopback loop $isofile
    linux (loop)/isolinux/pentoo root=/dev/ram0 init=/linuxrc nox nodhcp secureconsole overlayfs max_loop=256 nokeymap video=uvesafb:mtrr:3,ywrap,1024x768-16 console=tty0 net.ifnames=0 scsi_mod.use_blk_mq=1 ipv6.autoconf=0 looptype=squashfs loop=/image.squashfs cdroot isoboot=$isofile
    initrd (loop)/isolinux/pentoo.igz
}
```
Thanks. Please close the ticket.

**Comment by blshkv** [comment]
told you to look for grub iso booting options ;-)

**Comment by mar00** [comment]
> @blshkv It has everything to do with Pentoo. The parameter for `isolinux/pentoo` is pentoo specific. Different distro has complete different parm or the way to boot from a ISO file.
> 
> @ostree `cdroot` is copied from `grub.cfg` file in Live ISO CD. Below are the original:
> 
> ```
> [Ricky@t20 cdrom]$ cat grub/grub.cfg
> #
> set default="0"
> 
> insmod efi_gop
> insmod efi_uga
> 
> set lang=en_US
> loadfont /grub/unicode.pf2
> set gfxmode=auto
> insmod gfxterm
> terminal_output gfxterm
> insmod gfxmenu
> loadfont /grub/themes/pentoo/dejavu_10.pf2
> loadfont /grub/themes/pentoo/dejavu_12.pf2
> loadfont /grub/themes/pentoo/dejavu_14.pf2
> loadfont /grub/themes/pentoo/dejavu_16.pf2
> loadfont /grub/themes/pentoo/dejavu_bold_14.pf2
> insmod png
> set theme=/grub/themes/pentoo/theme.txt
> export theme
> 
> set timeout_style=menu
> set timeout="10"
> set hidden_timeout_quiet=false
> 
> insmod play
> play 960 440 1 0 4 440 1
> 
> menuentry 'Boot Pentoo LiveCD (kernel: pentoo)' --class gnu-linux --class os {
> 	linux /isolinux/pentoo root=/dev/ram0 init=/linuxrc nox nodhcp secureconsole overlayfs max_loop=256 dokeymap video=uvesafb:mtrr:3,ywrap,1024x768-16 console=tty0 net.ifnames=0 scsi_mod.use_blk_mq=1 ipv6.autoconf=0 verify looptype=squashfs loop=/image.squashfs cdroot
> 	initrd /isolinux/pentoo.igz
> }
> ```

no  found : theme.txt  for  iso pentoo-full-amd64  ??

**Comment by ZeroChaos-** [comment]
> > @blshkv It has everything to do with Pentoo. The parameter for `isolinux/pentoo` is pentoo specific. Different distro has complete different parm or the way to boot from a ISO file.
> > @ostree `cdroot` is copied from `grub.cfg` file in Live ISO CD. Below are the original:
> > ```
> > [Ricky@t20 cdrom]$ cat grub/grub.cfg
> > #
> > set default="0"
> > 
> > insmod efi_gop
> > insmod efi_uga
> > 
> > set lang=en_US
> > loadfont /grub/unicode.pf2
> > set gfxmode=auto
> > insmod gfxterm
> > terminal_output gfxterm
> > insmod gfxmenu
> > loadfont /grub/themes/pentoo/dejavu_10.pf2
> > loadfont /grub/themes/pentoo/dejavu_12.pf2
> > loadfont /grub/themes/pentoo/dejavu_14.pf2
> > loadfont /grub/themes/pentoo/dejavu_16.pf2
> > loadfont /grub/themes/pentoo/dejavu_bold_14.pf2
> > insmod png
> > set theme=/grub/themes/pentoo/theme.txt
> > export theme
> > 
> > set timeout_style=menu
> > set timeout="10"
> > set hidden_timeout_quiet=false
> > 
> > insmod play
> > play 960 440 1 0 4 440 1
> > 
> > menuentry 'Boot Pentoo LiveCD (kernel: pentoo)' --class gnu-linux --class os {
> > 	linux /isolinux/pentoo root=/dev/ram0 init=/linuxrc nox nodhcp secureconsole overlayfs max_loop=256 dokeymap video=uvesafb:mtrr:3,ywrap,1024x768-16 console=tty0 net.ifnames=0 scsi_mod.use_blk_mq=1 ipv6.autoconf=0 verify looptype=squashfs loop=/image.squashfs cdroot
> > 	initrd /isolinux/pentoo.igz
> > }
> > ```
> 
> no found : theme.txt for iso pentoo-full-amd64 ??

Necromancy is forbidden.  Please don't bring new issues to 6 year old threads.  You will get no support like this.
