### ISSUE TITLE
dev-ruby/arachni-rpc-em -- doc use

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#32]
Hi, here log:

 * Package:    dev-ruby/arachni-rpc-em-0.2
 * Repository: pentoo
 * USE:        abi_x86_64 amd64 doc elibc_glibc kernel_linux pie ruby_targets_ruby19 ssp userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Running unpack phase for all ...
 * Unpacking .gem file... ...
 [ ok ]
 * Uncompressing metadata ...
 [ ok ]
 * Unpacking data.tar.gz ...
 [ ok ]
>>> Source unpacked in /var/tmp/portage/dev-ruby/arachni-rpc-em-0.2/work
>>> Preparing source in /var/tmp/portage/dev-ruby/arachni-rpc-em-0.2/work ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby19 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-ruby/arachni-rpc-em-0.2/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-ruby/arachni-rpc-em-0.2/work ...
 * Running compile phase for all ...
rake aborted!
Unable to determine name from existing gemspec. Use :name => 'gemname' in #install_tasks to manually set it.
/var/tmp/portage/dev-ruby/arachni-rpc-em-0.2/work/all/arachni-rpc-em-0.2/Rakefile:13:in `<top (required)>'

Thx.

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/37
