### ISSUE TITLE
new tool: gobuster

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#320]
https://github.com/OJ/gobuster. Like the dev I prefer this one over dirbuster because I don't need a "fat Java GUI". [sic]

**Comment by blshkv** [comment]
Is it better than https://github.com/pentoo/pentoo-overlay/issues/290?

**Comment by gkroon** [comment]
Nice tool, I wasn't familiar with that one yet! Would be really cool to have that one as well as it enumerates in a different way. Gobuster is a brute-force tool which you feed a wordlist, whereas dirhunt seems to be a crawler/spider on steroids. Slightly different tools and I would therefore not argue one is better than the other. It would be preferable to have both in the future, IMHO.

I already started creating ebuilds for gobuster and its dependencies but I think I'm gonna need some help as the compilation give me some errors ("doins failed"). Should I submit a pull request, or how should I share my experimental newbie ebuilds?

**Comment by blshkv** [comment]
Can you pastebin it or create a pull request, either way is fine. I would need to review it and fix potential bugs.

**Comment by blshkv** [comment]
ok, fixed. There is a hack: you need to install it manually. The default installer does ```doins -r pkg src``` which is applicable for dependencies only

**Comment by blshkv** [comment]
FYI, we have few other dns brute force/discovery tools:
https://github.com/pentoo/pentoo-overlay/issues/273

I got sick and tired of all these "yet another" small but very useful one-day scripts.
It would be good if they all come together and write  one tool which works.

**Comment by blshkv** [comment]
I still think this is a duplicate and hope this tool is really better.
So far, we have dirb, DirBuster and Wfuzz, may be others. Let's see which one will die first

**Comment by gkroon** [comment]
Thanks a lot! I'd be happy to help maintain gobuster in the mean time.

**Comment by blshkv** [comment]
Well done with the ebuilds btw.

**Comment by blshkv** [comment]
FYI, I had to rename go-uuid, see:
https://github.com/pentoo/pentoo-overlay/commit/be1ee83976e9ecbb456d1af1013ecc25b545397f
and https://github.com/repology/repology-rules/issues/86
