### ISSUE TITLE
new tool: SecLists

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#321]
https://github.com/danielmiessler/SecLists. It would be really nice to pull in the latest SecLists to have some dictionaries shipped with Pentoo for cracking / brute forcing.

**Comment by blshkv** [comment]
It is already in the tree. Just emerge it

**Comment by gkroon** [comment]
Sorry, my bad.

**Comment by blshkv** [comment]
no problem, I have just added it last week so you might not synced the repo yet ;-)
