### ISSUE TITLE
gentoo.efimg checksum Fail

### ISSUE THREAD

**Issue by bilandl** [pentoo/pentoo-overlay#329]
Hi
I have a problem to start and install pentoo 2018.0 RC8 in UEFI mode. The checksum check is failing for **gentoo.efimg**.
It stays after keymap chose "gentoo.efimg: FAILED"

Please fix this issue. I want to use a HackRF One with this awsome OS better than Kali.

Thanks

**Comment by blshkv** [comment]
Please report such issues at https://github.com/pentoo/pentoo-livecd/issues in future.

@ZeroChaos- something for you to investigate

**Comment by ZeroChaos-** [comment]
there is nothing for me to investigate.  This happened for one of two reasons:

1.) the checksum failed because of actual corruption. that's why we verify checksums
2.) I have (rarely) seen UEFI that modify that file, turning on secureboot seems to stop that negative behavior.

**Comment by blshkv** [comment]
@bilandi please double check and confirm

**Comment by bilandl** [comment]
Oh yes. Win32DiskImager 1.0 didn't do his job right.

The checksum of gentoo.efimg was wrong after cloneing the iso to an USB drive with Win32DiskImager. dd does his job right.

Thanks - closed
