### ISSUE TITLE
dev-ruby/ethon -- doc use

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#33]
Hi, here log:

 * Package:    dev-ruby/ethon-0.7.0
 * Repository: pentoo
 * USE:        abi_x86_64 amd64 doc elibc_glibc hardened kernel_linux pie ruby_targets_ruby19 ssp userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
 * Running unpack phase for all ...
 * Unpacking .gem file... ...
 [ ok ]
 * Uncompressing metadata ...
 [ ok ]
 * Unpacking data.tar.gz ...
 [ ok ]
>>> Source unpacked in /var/tmp/portage/dev-ruby/ethon-0.7.0/work
>>> Preparing source in /var/tmp/portage/dev-ruby/ethon-0.7.0/work ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby19 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-ruby/ethon-0.7.0/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-ruby/ethon-0.7.0/work ...
 * Running compile phase for all ...
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
Bundler::GitError: The git source https://github.com/sinatra/sinatra.git is not yet checked out. Please run `bundle install` before trying to start your application
/var/tmp/portage/dev-ruby/ethon-0.7.0/work/all/ethon-0.7.0/Rakefile:2:in `<top (required)>'

Thx.

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/37
