### ISSUE TITLE
www-apps/beef No Rakefile

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#34]
Hi, here log:

 * Package:    www-apps/beef-0.4.6.1
 * Repository: pentoo
 * USE:        abi_x86_64 amd64 doc elibc_glibc kernel_linux ruby_targets_ruby19 userland_GNU
 * FEATURES:   preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking beef-0.4.6.1.tar.gz to /var/tmp/portage/www-apps/beef-0.4.6.1/work
>>> Source unpacked in /var/tmp/portage/www-apps/beef-0.4.6.1/work
>>> Preparing source in /var/tmp/portage/www-apps/beef-0.4.6.1/work/beef-0.4.6.1 ...
 * Applying 0.4.5_unbundler.patch ...
 [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/www-apps/beef-0.4.6.1/work/beef-0.4.6.1 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/www-apps/beef-0.4.6.1/work/beef-0.4.6.1 ...
 * Running compile phase for all ...
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

Thx

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/37
