### ISSUE TITLE
gentoo - bugs

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#35]
Hi, some dependencies in gentoo have bugs with the doc use, the bugs are listed here:

https://gist.github.com/latot/a8c7b748adf2e2134c83

dev-ruby/arel-helpers
dev-ruby/metasploit-concern
dev-ruby/metasploit-credential
dev-ruby/metasploit-model
dev-ruby/packetfu
dev-ruby/postgres_ext
dev-ruby/recog
dev-ruby/rubyntlm

basically are two solutions, add this packages with -doc in the profile in the overlay, or search other working version while the bug are solved in gentoo.

**Comment by blshkv** [comment]
we don't want explicitly force users to disable "doc" flag and it is disabled by default.
FYI, https://www.gentoo.org/support/use-flags/
```
doc	Add extra documentation (API, Javadoc, etc). It is recommended to enable per package instead of globally
```

anyways, all these packages were written by us initially. ZC just pushed it to Gentoo. I guess we can file an upstream bug report (bugs.gentoo.org)  and let ZC finish the job ;-)

**Comment by ZeroChaos-** [comment]
this bug is fine, I'll fix all of them....as soon as I know how...

**Comment by necrose99** [comment]
suricata-1.0.5.ebuild
https://packages.gentoo.org/packages/net-analyzer/suricata :  3.1 : 0 	3.0.1 : 0 	2.0.11 : 0

**Comment by blshkv** [comment]
well, there is still no progress after these 3 years. Let's Gentoo guys handle it, feel free to open a bug at their bugzilla.
