### ISSUE TITLE
new tool: BoNeSi DDoS Botnet Simulator

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-overlay#36]
https://github.com/markus-go/bonesi

**Comment by ZeroChaos-** [comment]
I see this is already done... but I caution you both, this distro is for pentesters not ddosing script kiddies.

**Comment by blshkv** [comment]
read the description of the tool. It is only possible to execute certain ddos test cases if you are in the same subnet, i.e. in the lab. I do have clients which require such tests once in awhile. They want to test before somebody else does. There is nothing wrong with this approach.

**Comment by ostree** [comment]
moreover, how to evaluate anti ddos solutions? This tool is very valuable.
