### ISSUE TITLE
new tools for source code analysis etc.

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#361]
https://github.com/sharkdp/bat

Drop-in replacement for cat with Git integration, syntax highlighting, et cetera. which helps source code analysis and such.

We already have https://github.com/gentoo/gentoo-rust/blob/master/app-misc/bat/bat-0.3.0.ebuild, but I feel it's rather silly to add a whole overlay for one ebuild. I tried making a more up-to-date bat ebuild, but it doesn't compile with the slightly outdated `dev-lang/rust` in the Gentoo tree. The 0.3.0 version works fine in the meantime, though. What do you guys think?

**Comment by gkroon** [comment]
Also found https://github.com/so-fancy/diff-so-fancy

**Comment by blshkv** [comment]
I haven't seen any good source code analysers at all. But feel free to add if you use it.

**Comment by gkroon** [comment]
You're right, these tools only display contents or changes. They just help me with spotting low hanging fruit. :-)

**Comment by gkroon** [comment]
Seeing as I haven't invested my time for this in almost a week (and because I agree with https://github.com/pentoo/pentoo-overlay/issues/367#issuecomment-420284510) I'm closing this one for now.
