### ISSUE TITLE
new tool: jwt-cracker

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#367]
https://github.com/brendan-rius/c-jwt-cracker

A tool to crack JWTs that are protected by shared secrets. I'd be happy to claim this one to create an ebuild.

**Comment by blshkv** [comment]
Sure, please go ahead. You don't need to ask :)

**Comment by gkroon** [comment]
Thanks :)

For my own reference to check which one works best:
https://github.com/AresS31/jwtcat
https://github.com/brendan-rius/c-jwt-cracker
https://github.com/ojensen5115/jwtcrack

**Comment by gkroon** [comment]
I'm going to close this as hashcat already supports it (hashcat -m 16500)

**Comment by blshkv** [comment]
Great. Let's try to avoid dozen little scripts which are getting forgotten by their authors after few months
