### ISSUE TITLE
"doc" use flag is not supported

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-overlay#37]
I'm opening this bug as an aggregator for all packages. We have neither power no interest in supporting "doc" flag at the moment. So feel free to create pull request and we will be happy to merge it.

**Comment by latot** [comment]
okis, thx, only the https://github.com/pentoo/pentoo-overlay/issues/19 its a missed dependence, it need to be fixed.

**Comment by necrose99** [comment]
https://github.com/postmodern/spidr seems to be a fork? dose have a rakefile. 
https://github.com/chriskite/anemone likewise fork? (dev-ruby/spider No Rakefile #21)  

https://github.com/ioquatix/rubydns/releases/tag/v1.0.2 ebuild bump? might fix it?  (dev-ruby/rubydns )
https://gitweb.gentoo.org/repo/gentoo.git/diff/dev-ruby/jsobfu/jsobfu-0.3.0.ebuild?id=0b675d1102ec0bbacde10bec17e29306527402fb

**Comment by blshkv** [comment]
jsobfu: removed from Pentoo. It is in the main tree.

**Comment by blshkv** [comment]
guys, I'm trying to close all pentoo issue or keep them minimal. That bug does not help as there is no progress here. Do not enable doc file if you use Pentoo or create a pull request if you care.
Open a separate bug report at bugs.gentoo.org if it is a Gentoo package.
