### ISSUE TITLE
app-fuzz/ohrwurm download not found

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#389]
>>> Emerging (1 of 6) app-fuzz/ohrwurm-0.1::pentoo
 * Fetching files in the background.
 * To view fetch progress, run in another terminal:
 * tail -f /var/log/emerge-fetch.log
>>> Downloading 'http://distfiles.gentoo.org/distfiles/ohrwurm-0.1.tar.bz2'
--2018-11-14 22:08:58--  http://distfiles.gentoo.org/distfiles/ohrwurm-0.1.tar.bz2
Resolving distfiles.gentoo.org... 137.226.34.46, 140.211.166.134, 156.56.247.195, ...
Connecting to distfiles.gentoo.org|137.226.34.46|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-11-14 22:08:58 ERROR 404: Not Found.

>>> Downloading 'http://mazzoo.de/d/ohrwurm-0.1.tar.bz2'
--2018-11-14 22:08:58--  http://mazzoo.de/d/ohrwurm-0.1.tar.bz2
Resolving mazzoo.de... 194.150.168.91
Connecting to mazzoo.de|194.150.168.91|:80... failed: Connection refused.
!!! Couldn't download 'ohrwurm-0.1.tar.bz2'. Aborting.
 * Fetch failed for 'app-fuzz/ohrwurm-0.1', Log file:
 *  '/var/tmp/portage/app-fuzz/ohrwurm-0.1/temp/build.log.gz'

>>> Failed to emerge app-fuzz/ohrwurm-0.1, Log file:

>>>  '/var/tmp/portage/app-fuzz/ohrwurm-0.1/temp/build.log.gz'

**Comment by blshkv** [comment]
gone! Thanks
