### ISSUE TITLE
tool request - faraday

### ISSUE THREAD

**Issue by ZeroChaos-** [pentoo/pentoo-overlay#39]
https://github.com/infobyte/faraday

**Comment by necrose99** [comment]
:+1: awesome find

**Comment by necrose99** [comment]
forked Faraday have an initial pull for gentoo req package(s)  .txt  based on thier Client/server /extra's model. 
despite being salavitinigly good , a makefile , make.client make.server etc could be made , however might be a touch above my meddlesome tinkerage skills. / "Paygrade" 
 i do see in /Debian folder a few hints..
then emake install.  or emake ALL..  IUSE=client , +Server for the other ... extras for opt depts.. 


anyhow this is a provisional List of deps... 

[gentoo_requirements.txt](https://github.com/pentoo/pentoo-overlay/files/1048619/gentoo_requirements.txt)
[gentoo_requirements_server.txt](https://github.com/pentoo/pentoo-overlay/files/1048618/gentoo_requirements_server.txt)

**Comment by necrose99** [comment]
Prototype units  , start twisted services , couchdb and network manager , invoke Faraday web service. 



[faraday-webserver.service.txt](https://github.com/pentoo/pentoo-overlay/files/1808025/faraday-webserver.service.txt) systemd
[faraday-webserver-rc.txt](https://github.com/pentoo/pentoo-overlay/files/1808021/faraday-webserver-rc.txt) openrc/etc init file.

**Comment by blshkv** [comment]
It may sound as a good idea to have this tool but I say "no":
 - nobody took over ownership during 3 years;
 - I dont need this tool personally and it would take a lot to maintain this tool
 - non true spirit of opensource: they have pro and enterprise versions. I could be interested in reporting module but it is available in pro version only. So we don't want to be an advertising distro. 

Closing this bug for now. Feel free to ping me if you want to maintain it.

**Comment by necrose99** [comment]
@blshkv  setup.py is now included in the project , so thus building it has should be much less hell.

**Comment by blshkv** [comment]
as expected, this is a demo version. Half of menus are not available. Well, enjoy it.

**Comment by necrose99** [comment]
any rate , the licecing keys for community or Comercial should enable more according to them. 
just if i had enough red clients a year to toarch $3k i could test it but will ask them for a short dev key.  for pentoo's sake.

**Comment by blshkv** [comment]
The license key will not help. The source code is simply not public

**Comment by necrose99** [comment]
https://github.com/infobyte/faraday_plugins  https://github.com/infobyte/faraday_agent_dispatcher 
https://github.com/infobyte/faraday_burp 

https://github.com/infobyte/faraday_addon   :: firefox 

few more add on repos

**Comment by blshkv** [comment]
There is not much point in input plugins if you can't generate a report.
