### ISSUE TITLE
Graphics Driver not allowing an x session to start

### ISSUE THREAD

**Issue by hazmat09** [pentoo/pentoo-overlay#392]
NVIDIA GEForce GTX 1070 card installed in MSI GS65 Stealth Thin laptop.  When "startx" command issued, x session never opens.  Running from live USB.

**Comment by blshkv** [comment]
please provide xorg.log and live usb version.

**Comment by blshkv** [comment]
Closing seens no response. You may want to upgrade xorg, make sure suid flag is off. That was a gentoo bug. Feel free to google, try other version of nvidia drivers and report a solution. Anyway, it has nothing to do with security
