### ISSUE TITLE
dev-python/qt-py-1.2.0_beta2 fails to download

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#399]
>>> Fetching (6 of 7) dev-python/qt-py-1.2.0_beta2::pentoo
>>> Downloading 'http://distfiles.gentoo.org/distfiles/qt-py-1.2.0_beta2.tar.gz'
--2018-12-04 19:49:03--  http://distfiles.gentoo.org/distfiles/qt-py-1.2.0_beta2
.tar.gz
Resolving distfiles.gentoo.org... 216.165.129.135, 64.50.233.100, 64.50.236.52, 
...
Connecting to distfiles.gentoo.org|216.165.129.135|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-12-04 19:49:03 ERROR 404: Not Found.

>>> Downloading 'https://github.com/mottosso/Qt.py/archive/qt-py-1.2.0.b2.tar.gz
'
--2018-12-04 19:49:03--  https://github.com/mottosso/Qt.py/archive/qt-py-1.2.0.b
2.tar.gz
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/mottosso/Qt.py/tar.gz/qt-py-1.2.0.b2 [foll
owing]
--2018-12-04 19:49:03--  https://codeload.github.com/mottosso/Qt.py/tar.gz/qt-py
-1.2.0.b2
Resolving codeload.github.com... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-12-04 19:49:04 ERROR 404: Not Found.

!!! Couldn't download 'qt-py-1.2.0_beta2.tar.gz'. Aborting.
 * Fetch failed for 'dev-python/qt-py-1.2.0_beta2'

>>> Failed to emerge dev-python/qt-py-1.2.0_beta2

**Comment by bill-e-ghote** [comment]
This seems to be valid download location:
https://github.com/mottosso/Qt.py/archive/1.2.0.b2.tar.gz

**Comment by ZeroChaos-** [comment]
agreed, have a good evening
