### ISSUE TITLE
guymager The latest version is 0.7.4. 

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#40]
slight version bump... Gui for xmount etc... 
The latest version is 0.7.4. http://guymager.sourceforge.net/

**Comment by necrose99** [comment]
https://github.com/necrose99/necromancy-overlay/blob/master/app-forensics/xmount/xmount-0.7.3.ebuild  mangling on it for speculative CMAKE issue since upstream switched. 
hopefully can have it ready to test soon in clean VM install. 
blshvk /zc have repo rights (many speculative ebuild's or wip's in this repo) 

Note:just not having a cloud build server  atm and or having to test in vm , moved to tx HDD holding Gentoo  is kinda dying..  unforeseen cost have delayed me in getting new one on my own overlay.. 

feel free to abscond with an ebuild or 2 .

**Comment by blshkv** [comment]
Can you repeat it in English? ;-)

**Comment by necrose99** [comment]
app-forensics/guymager-0.7.4-2 version bump... 

patches inside archive if needed.... 
https://forensics.cert.org/fedora/cert/17/SRPMS/guymager-0.7.4-2.fc17.src.rpm

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/commit/52f6d4628916bf84d704c52b8041f4be22e7e635
