### ISSUE TITLE
net-analyzer/medusa-2.2_p20180712::pentoo failed (configure phase): No package 'freerdp2' found

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#402]
Attaching build.log.gz and other files.
[build.log.gz](https://github.com/pentoo/pentoo-overlay/files/2683158/build.log.gz)
[emerge-info.txt](https://github.com/pentoo/pentoo-overlay/files/2683159/emerge-info.txt)
[emerge-pqv.txt](https://github.com/pentoo/pentoo-overlay/files/2683160/emerge-pqv.txt)
[environment.txt](https://github.com/pentoo/pentoo-overlay/files/2683161/environment.txt)

**Comment by blshkv** [comment]
upstream bug https://github.com/jmk-foofus/medusa/issues/27

**Comment by blshkv** [comment]
done, thanks
