### ISSUE TITLE
Package block between johntheripper and johntheripper-jumbo

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#405]
Recent breakout of johntheripper into two separate packages leads to package block. From my read of the pentoo-cracking/pentoo-cracking-2018.3-r1.ebuild dependency spec, either john build should suffice. Not sure why a package block arises. I tried uninstalling johntheripper and re-running updater, but on subsequent builds the block is back again. Maybe this problem is ephemeral and goes away when the open Gentoo bug for johntheripper-jumbo is fixed? It seems that metasploit ebuild should also be updated to permit the non-jumbo build, maybe?

(Incidentally, I totally do not "get" the thought process behind breaking john into two packages.)

[blocks B      ] app-crypt/johntheripper-jumbo ("app-crypt/johntheripper-jumbo" is blocking app-cryp
t/johntheripper-1.8.0, app-crypt/johntheripper-1.7.9-r11)
[blocks B      ] app-crypt/johntheripper ("app-crypt/johntheripper" is blocking app-crypt/johntherip
per-jumbo-1.8.0)

Total: 32 packages (3 upgrades, 29 new), Size of downloads: 36,135 KiB
Conflict: 2 blocks (2 unsatisfied)

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (app-crypt/johntheripper-1.8.0:0/0::gentoo, ebuild scheduled for merge) pulled in by
    app-crypt/johntheripper required by (pentoo/pentoo-cracking-2018.3-r1:0/0::pentoo, installed)

  (app-crypt/johntheripper-jumbo-1.8.0:0/0::gentoo, ebuild scheduled for merge) pulled in by
    app-crypt/johntheripper-jumbo required by (net-analyzer/metasploit-4.17.21-r4:4.17/4.17::gentoo,
 installed)

**Comment by blshkv** [comment]
That was fixed an hour ago. Do *sync* before reporting ;-)
b5fb7525c9831be5824ea9ec74e9a93943c5b4f6
