### ISSUE TITLE
new tool: qark

### ISSUE THREAD

**Issue by oxr463** [pentoo/pentoo-overlay#407]
> Tool to look for several security related Android application vulnerabilities
--https://github.com/linkedin/qark

**Comment by blshkv** [comment]
I unbundled apktools and dex2jar. It would be good if you could also test the functionality since our versions are more recent.

Thanks

**Comment by oxr463** [comment]
I haven't heard of this one before but from what I've read on their site, I'd rather use qark since it doesn't require using android studio.
