### ISSUE TITLE
new tool: LMD

### ISSUE THREAD

**Issue by oxr463** [pentoo/pentoo-overlay#408]
> Linux Malware Detect (LMD) is a malware scanner for Linux released under the GNU GPLv2 license, that is designed around the threats faced in shared hosted environments. 
--https://www.rfxn.com/projects/linux-malware-detect

**Comment by blshkv** [comment]
I think is would better to push it to Gentoo 
https://bugs.gentoo.org/414423 (2012) where it can be integrated with ClamAV:
```- integrated detection of ClamAV to use as scanner engine for improved performance```

We do not have bandwidth for such category of security tools.
Feel free to create a pull with working ebuild. I'd be happy to merge it.
