### ISSUE TITLE
net-wireless/editcp-bin download not found

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#410]
>>> Emerging (2 of 2) net-wireless/editcp-bin-1.0.11::pentoo
>>> Downloading 'http://distfiles.gentoo.org/distfiles/editcp-1.0.11.tar.xz'
--2019-01-23 20:43:57--  http://distfiles.gentoo.org/distfiles/editcp-1.0.11.tar.xz
Resolving distfiles.gentoo.org... 64.50.236.52, 137.226.34.46, 140.211.166.134, ...
Connecting to distfiles.gentoo.org|64.50.236.52|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-01-23 20:43:57 ERROR 404: Not Found.

>>> Downloading 'https://www.farnsworth.org/dale/codeplug/editcp/downloads/linux/editcp-1.0.11.tar.x
z'
--2019-01-23 20:43:57--  https://www.farnsworth.org/dale/codeplug/editcp/downloads/linux/editcp-1.0.
11.tar.xz
Resolving www.farnsworth.org... 198.74.58.51
Connecting to www.farnsworth.org|198.74.58.51|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-01-23 20:43:58 ERROR 404: Not Found.

!!! Couldn't download 'editcp-1.0.11.tar.xz'. Aborting.
 * Fetch failed for 'net-wireless/editcp-bin-1.0.11', Log file:
 *  '/var/tmp/portage/net-wireless/editcp-bin-1.0.11/temp/build.log.gz'

>>> Failed to emerge net-wireless/editcp-bin-1.0.11, Log file:

**Comment by ZeroChaos-** [comment]
thanks for the report, bumped
