### ISSUE TITLE
new tool: rdp-sec-check?

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#415]
https://github.com/portcullislabs/rdp-sec-check
I think this one was removed previously, correct? Please let me know if this one is not desired anymore, or if there's a better alternative. Otherwise, I'm happy to add and maintain it.

**Comment by blshkv** [comment]
we don't remove software if it is supported and useful. Feel free to create a pull request

**Comment by gkroon** [comment]
Great, I was only confused because of commit 94dee4cca90725ad01ddf3b3f56b42743cc2843e that mentions "Encoding-BER: new perl module, required by rdp-sec-check", but I couldn't find rdp-sec-check itself anywhere. :-)

**Comment by blshkv** [comment]
I was testing a windows box and added its dependency which was enough to run the single file tool. Later, I was either lazy or forgot or both to complete it ;-) So thanks!
