### ISSUE TITLE
bump request for net-wireless/rtl8812au_aircrack-ng

### ISSUE THREAD

**Issue by Elleni57** [pentoo/pentoo-overlay#421]
As it would not compile with kernel >=5.0.0. In gentoo forum I was told, that it is already [fixed by upstream](https://github.com/aircrack-ng/rtl8812au/blob/v5.2.20/os_dep/linux/rtw_android.c#L627), so I tested with the modified rtw_android.c and it compiled fine. 

Thank you :)

**Comment by blshkv** [comment]
sure, enjoy ;-)
