### ISSUE TITLE
pentoo-analyzer/pentoo-analyzer-2018.3 depends on deprecated/masked net-analyzer/netcat6

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#422]
As seen in the update:

# Michał Górny <mgorny@gentoo.org> (13 Mar 2019)
# An ancient netcat clone that has been declared obsolete upstream,
# yet keeps confusing Gentoo users into thinking it's better than
# the original.  Recommended alternatives are net-analyzer/netcat,
# net-analyzer/openbsd-netcat, net-misc/socat...
# Removal in 30 days.  Bug #573814.
=net-analyzer/netcat6-1.0-r2

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/commit/e4bb5b3f651920fa97cce8d89c732b6a0ed8f0e1 thanks!
