### ISSUE TITLE
Arachni updates

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#43]
some of your woeful bugs might be closed #37  

anyhow some of the ebuilds for the various components have been vastly updated.  >=program/sub-modules  than ebuild/s.  
2.0 on rpc sub-module https://github.com/Arachni/arachni-rpc/archive/v0.2.1.2.tar.gz

http://gpo.zugaina.org/Overlays/spike/dev-ruby/arachni-rpc 
http://data.gpo.zugaina.org/spike/dev-ruby/arachni-rpc/arachni-rpc-0.2.1.1.ebuild
http://data.gpo.zugaina.org/spike/dev-ruby/arachni-rpc/arachni-rpc-0.2.1.2.ebuild
http://data.gpo.zugaina.org/spike/dev-ruby/arachni-rpc/arachni-rpc-0.2.0.ebuild
http://data.gpo.zugaina.org/spike/dev-ruby/arachni-rpc/Manifest

all likely put in by dev-perl/app-witchcraft no doubt  https://github.com/Spike-Pentesting/App-witchcraft/releases 
anyhow saves you a we bit of time...

**Comment by blshkv** [comment]
I've looked at the Spike overlay. They just copied our ebuilds and our patches so all these links are useless.

FYI. The latest version is 1.3.2

**Comment by blshkv** [comment]
I've got it working:
0810271b3fd7333a75e2df58494970409c074713

Feel free to test

**Comment by necrose99** [comment]
no biggy i just was trying to audit spikes automated bumps against pentoo , do wish their was a faster means of doing so.  hopefully since the bleeding is slowing down from the move , my accounts will in the black instead of bleeding $$ , and i've been needing a server quite badly.
