### ISSUE TITLE
Tools for scan data stored on a local computer

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#445]
https://www.kitploit.com/2019/03/mxtract-memory-extractor-analyzer.html
https://github.com/rek7/mXtract

**Comment by linxon** [comment]
What do you think about recovery tools for scan data stored on a local computer such as:
- mXtract
- [LaZagne](https://github.com/AlessandroZ/LaZagne)
- [mysql-magic](https://github.com/hc0d3r/mysql-magic)
- etc...

I think a user may want to add the "pentoo-overlay" and install one of the necessary utilities from this list

**Comment by blshkv** [comment]
The more ebuild the better :)
