### ISSUE TITLE
new tool: termshark

### ISSUE THREAD

**Issue by ZeroChaos-** [pentoo/pentoo-overlay#454]
https://termshark.io/

high priority if anyone wants to package golang stuff :-)

**Comment by blshkv** [comment]
I think you can drop ```-bin```. We create -bin ebuilds when the source code is not available, it takes too long to compile or not able to provide a proper ebuild

**Comment by blshkv** [comment]
I received a comment from @linxon that he added a -bin version in concern that a user would need to install an additional compiler. However, we do have golang installed for other tools (amass/bettercap etc) so this is not the case.  I still think we can drop thermshark-bin and ffuf-bin to avoid unnecessary maintenance
