### ISSUE TITLE
app-forensics/volatility-2.6.1 fails: filesize does not match recorded size

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#456]
Beyond this filesize mismatch error, I question whether Pentoo needs its own build. The difference between Gentoo and Pentoo ebuilds appears insignificant.

11c11
< SRC_URI="https://downloads.volatilityfoundation.org/releases/${PV}/${P}.zip"
---
> SRC_URI="https://github.com/volatilityfoundation/volatility/archive/${PV}.tar.gz -> ${P}.tar.gz"
18c18
< S=${WORKDIR}/${PN}-master
---
> #S=${WORKDIR}/${PN}-master
32c32
< 	rmdir --ignore-fail-on-non-empty "${D}/usr/contrib" || die
---
> 	rm -r "${D}/usr/contrib" || die

For whatever it's worth, the Gentoo build emerges OK.

**Comment by blshkv** [comment]
Thanks. The forensic upstream failed to understand how important it is.
