### ISSUE TITLE
net-proxy/zaproxy-2.7.0 fails to download extension ascanrules-release-28.zap

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#457]
>>> Emerging (1 of 13) net-proxy/zaproxy-2.7.0::pentoo
 * Fetching files in the background.
 * To view fetch progress, run in another terminal:
 * tail -f /var/log/emerge-fetch.log
 * ZAP_2.7.0_Core.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...            [ ok ]
>>> Downloading 'https://github.com/zaproxy/zap-extensions/releases/download/2.7/ascanrules-release-28.zap'
--2019-04-26 18:13:05--  https://github.com/zaproxy/zap-extensions/releases/download/2.7/ascanrules-release-28.zap
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-04-26 18:13:05 ERROR 404: Not Found.

!!! Couldn't download 'zaproxy-2.7.0-ascanrules-release-28.zap'. Aborting.
 * Fetch failed for 'net-proxy/zaproxy-2.7.0', Log file:
 *  '/var/tmp/portage/net-proxy/zaproxy-2.7.0/temp/build.log'

>>> Failed to emerge net-proxy/zaproxy-2.7.0, Log file:

>>>  '/var/tmp/portage/net-proxy/zaproxy-2.7.0/temp/build.log'

**Comment by blshkv** [comment]
It's been a while since the last release. Upstream has started to delete some plugins. Thanks, fixed!

**Comment by gordonzola** [comment]
Hi, I also have this issue in the current overlay version

**Comment by blshkv** [comment]
Could you post the error please? The current version is zaproxy-2.7.0-r1.ebuild.

**Comment by blshkv** [comment]
oh, ok.
