### ISSUE TITLE
virtual/jdk-1.8.0-r4 overrides main gentoo without good reason

### ISSUE THREAD

**Issue by ikelos** [pentoo/pentoo-overlay#460]
There is no longer a reason to have virtual/jdk-1.8 in the pentoo tree, and because it hasn't stayed in sync with the main tree, it currently prevents openjdk:8 (with the gentoo-vm USE flag) from being used to satisfy the requirements for virtual/jdk.  This in turn means that the openjdk cannot be used to satisfy virtual/jre (even though this isn't overriden by pentoo).  The simplest resolution is to remove this ebuild, but it might also be worthwhile reviewing the pentoo tree for other old ebuilds that overrode the main tree but are no longer necessary...  5:)

**Comment by blshkv** [comment]
the main reason of this change is to build jdk  from source. Updated, thanks!

**Comment by ikelos** [comment]
Thanks for the quick fix, but looking at the diff:
```diff
--- jdk-1.8.0-r5.ebuild	2019-05-10 12:57:01.292867096 +0100
+++ /usr/portage/virtual/jdk/jdk-1.8.0-r4.ebuild	2019-02-10 12:36:19.111007210 +0000
@@ -5,12 +5,12 @@
 
 DESCRIPTION="Virtual for Java Development Kit (JDK)"
 SLOT="1.8"
-KEYWORDS="amd64 ~arm ~arm64 ppc64 x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~sparc64-solaris ~x64-solaris"
+KEYWORDS="~amd64 ~arm ~arm64 ~ppc64 ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~sparc64-solaris ~x64-solaris"
 
 RDEPEND="|| (
-		dev-java/icedtea:8
 		dev-java/icedtea-bin:8
-		dev-java/openjdk:8[gentoo-vm(+)]
+		dev-java/icedtea:8
 		dev-java/openjdk-bin:8[gentoo-vm(+)]
+		dev-java/openjdk:8[gentoo-vm(+)]
 		dev-java/oracle-jdk-bin:1.8
 	)"
--- jdk-11.ebuild	2019-05-10 12:57:01.292867096 +0100
+++ /usr/portage/virtual/jdk/jdk-11.ebuild	2018-10-21 21:40:54.409640460 +0100
@@ -8,7 +8,7 @@
 KEYWORDS="~amd64 ~arm64 ~ppc64"
 
 RDEPEND="|| (
-		dev-java/openjdk:${SLOT}[gentoo-vm(+)]
 		dev-java/openjdk-bin:${SLOT}[gentoo-vm(+)]
+		dev-java/openjdk:${SLOT}[gentoo-vm(+)]
 		dev-java/oracle-jdk-bin:${SLOT}[gentoo-vm(+)]
 	)"
```
It doesn't look like the files are actually different (other than keywords)?  So how does having it help the jdk to be built from source?

**Comment by ikelos** [comment]
The ordering is arbitrary and only comes into play if the packages haven't been installed, and can easily be resolved by installing the jdk first and then installing the virtual.  Overriding the package is just a recipe for it no working 3 years down the line when the main tree has caught up or overtaken...  5:S

**Comment by blshkv** [comment]
our ebuilds pull virtual/jdk which pulls the first package in the list, i.e. icedtea (not a -bin version) if jdk is not installed. If it is installed, we respect a user's change

**Comment by ikelos** [comment]
Yep, but as demonstrated, 3 years later it could prevent users from having openjdk satisfy the jdk requirement.  I think it's very dangerous to override an ebuild (and have to then maintain it from 2016, which didn't happen here) in order for a one-off cosmetic fix of *preferring* source over binary.  I'd strongly recommend suggesting that users who care mask off the binary builds instead...

**Comment by blshkv** [comment]
@ZeroChaos-  can you mask -bins during building iso image only?

**Comment by blshkv** [comment]
I'll let @ZeroChaos-  to verify my change. Thanks, fixed!

**Comment by ZeroChaos-** [comment]
I'll see what happens to the livecd builds today and if I care to deal with it.  there is actually a huge amount of handling for this crap in the build scripts.

fuck java
