### ISSUE TITLE
app-arch/upx-ucl-3.95 ebuild tries to install TODO and uses dohtml

### ISSUE THREAD

**Issue by ikelos** [pentoo/pentoo-overlay#462]
app-arch/upx-ucl-3.95 throws an error attempting to dodoc TODO (which doesn't appear to exist in the source anymore), and then uses dohtml which has been [banned from EAPI 7](https://dev.gentoo.org/~mgorny/articles/the-ultimate-guide-to-eapi-7.html#dohtml).

Sorry about all the sudden bugs, but they'd been piling up and finally there were enough that I decided to do something about them...  5:P

**Comment by blshkv** [comment]
you should ask for the access and fix it yourself ;) Thanks

**Comment by ikelos** [comment]
Cool, who would I ask?  5:)

**Comment by ZeroChaos-** [comment]
Me :-)  What key do you use to sign commits?

**Comment by ikelos** [comment]
Nice.  I typically sign stuff with 0xD3CF61546B08277D...  5:)

**Comment by ZeroChaos-** [comment]
you have access now, please try to follow the same general policies as gentoo

**Comment by ikelos** [comment]
Yep, will do, thanks (I think most of the changes I had stocked up have
already been fixed by Anton, but I'm sure something will crop up in the
future!  5:)

**Comment by ikelos** [comment]
Hmmm, do github's hooks not handle subkeys?  I signed a commit (adding python3.7 support to scapy-2.4.2) using that key, but it's still telling me it's not accepted.  Does it need the specific signature subkey (0x0D129BD4062378F1) from it?
