### ISSUE TITLE
dev-db/neo4j-community-3.5.3 fails in install stage

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#467]
With error:
doexe: /var/tmp/portage/dev-db/neo4j-community-3.5.3/work/neo4j-community-3.5.3/bin/neo4j-shell does not exist

**Comment by linxon** [comment]
Thank you!
Please report any problem here

Commit: https://github.com/pentoo/pentoo-overlay/commit/9ca0755f91218a2027bc36ce900441a98b74612a

**Comment by bill-e-ghote** [comment]
Thank you for the update. Builds and executes as expected.
