### ISSUE TITLE
Issue with ZAP and tiling window managers

### ISSUE THREAD

**Issue by oxr463** [pentoo/pentoo-overlay#469]
Just FYI, in order to run `net-proxy/zaproxy` under a tiling window manager, the following environment variable needs to be set:

```terminal
export _JAVA_AWT_WM_NONREPARENTING=1
```

Not sure if this should be put in `/etc/conf.d/zaproxy`, or `/etc/default/zaproxy`, or the like.

**Comment by blshkv** [comment]
According to https://wiki.archlinux.org/index.php/java, that must be done in global settings,
/etc/profile.d/jre.sh or similar. Let me know if you still think it must be for zap (and not for burp) proxy only.

Closing, as it is a WM related issue.
