### ISSUE TITLE
PORTAGE_BZIP2_COMMAND setting is invalid: 'lbzip2'

### ISSUE THREAD

**Issue by ashcatium** [pentoo/pentoo-overlay#470]
I get these erros whenever i try to env-update after selecting Pentoo profile in my Gentoo.
PORTAGE_BZIP2_COMMAND setting is invalid: 'lbzip2'
PORTAGE_BZIP2_COMMAND setting is invalid: 'lbunzip2'

Should I change them in /usr/share/portage/config/make.globals ?

**Comment by ZeroChaos-** [comment]
lbzip2 will be installed on first @world update and the warning will go away.  it's harmless. enjoy the speed improvement.
