### ISSUE TITLE
visual-studio-code

### ISSUE THREAD

**Issue by hex45** [pentoo/pentoo-overlay#473]
Can we get a build in the overlay for most recent Visual Studio Code releases?

**Comment by blshkv** [comment]
There are few ebuilds are already available via other overlays:
http://gpo.zugaina.org/app-editors/visual-studio-code

Could you test and suggest which one works the best?

**Comment by hex45** [comment]
I have been using jorgicio for some time now. It has been working fine as far as I can tell.

**Comment by blshkv** [comment]
can you try ikelos (I just noticed) @ikelos  is a Gentoo developer and contribute to Pentoo sometimes.

**Comment by hex45** [comment]
ikelos is currently behind at 1.34 where 1.35 was released a few days ago. I'm not sure how to evaluate the merits of one ebuild over another but it did work fine for 1.34

**Comment by blshkv** [comment]
pushed  @ikelos ebuild, seems slightly ahead.

**Comment by ZeroChaos-** [comment]
@ikelos can you push this to Gentoo, it seems people want it.

**Comment by ikelos** [comment]
Errr, I'm a little concerned about keeping it maintained, particularly given how often updates come about and how popular a package it seems to be?  My ebuild was just one that I found on zugaina.org with a couple of basic tweaks and I'm happy to look after it as long as it's not high maintenance (which, in my repo, it isn't).  If you want to help maintain it in the main tree, @ZeroChaos-, then I guess we can both look after it?

**Comment by blshkv** [comment]
Guys, i did not rename it into  -bin, but it is. Please do not push it to Gentoo until it is written to compile from sources
