### ISSUE TITLE
net-analyzer/medusa: Can't compile on gentoo 17.1

### ISSUE THREAD

**Issue by V10lator** [pentoo/pentoo-overlay#476]
Medusa tries to link to libraries from /usr/lib while it should look into /usr/lib64 and as such the linking fails. More infos:

> the lib->lib64 compatibility symlink is removed.
> 64-bit libraries need to be installed directly to lib64.  /lib
> and /usr/lib become real directories, that are used for cross-arch
> and native non-library packages (gcc, clang) and 32-bit libraries
> on the multilib profile (which improves compatibility with prebuilt x86
> packages).

(Source: https://www.gentoo.org/support/news-items/2019-06-05-amd64-17-1-profiles-are-now-stable.html )

**Comment by V10lator** [comment]
Made a quick&dirty patch:

```
--- medusa-8edc73ad77985e85ae2a40711ab7468f280d7936.old/configure.ac    2018-07-11 18:29:37.000000000 +0200
+++ medusa-8edc73ad77985e85ae2a40711ab7468f280d7936/configure.ac        2019-06-16 09:40:06.780774102 +0200
@@ -74,7 +74,7 @@
   then
     AC_MSG_RESULT([found])
     CPPFLAGS="$CPPFLAGS -I$1/include"
-    LDFLAGS="$LDFLAGS -L$1/lib"
+    LDFLAGS="$LDFLAGS -L$1/lib64"
     return 0
   else
     AC_MSG_RESULT([not found])
```
While this allows it to compile it installes the modules to /usr/lib64/medusa/modules which is wrong.

**Comment by linxon** [comment]
Closed via https://github.com/pentoo/pentoo-overlay/commit/19c50f1f802714c3f7cb5bc830abfe0e53659ce3 commit
