### ISSUE TITLE
emerge: there are no ebuilds to satisfy "dev-java/openjdk-bin:11[gentoo-vm(+)]".

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#478]
This is a very frustrating error... :-(
More details from my system if needed.
In the meantime, any hints?

**Comment by blshkv** [comment]
Please post full log

**Comment by blshkv** [comment]
Please note that ghidra (you should mention it in your report) requires jdk-11 which is currently masked in Gentoo. I have just unmasked it for you, but you still have eselect it yourself after the installation.

**Comment by bill-e-ghote** [comment]
My problem was a broken /etc/portage directory. My fault, I'm sure. package.use.mask was sitting in /etc/portage and not /etc/portage/profile. Mea culpa.

**Comment by blshkv** [comment]
well, yeah, that tree structure is not very logical. They could come up with something like package*s*.unmask and package.use.unmask to reflect a global setting vs individual package. But that might bring even more confusions. So just need to follow it blindly for now.

Thanks for the report!
