### ISSUE TITLE
xmount 0.7.3-1  (bin ebuild for now) 

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#48]
https://github.com/necrose99/necromancy-overlay/blob/master/app-forensics/xmount-bin/xmount-bin-0.7.3-1.ebuild   not all Keywords setup {$ARCH-linux}   Have ??? armfpl mips etc just not sure were to match them in the URI_SRC array 
a few of the Gentoo MIPS etc, but going for Deb's via unpackaer.eclass may's well go ALL IN. 
for now I can comment out the unused debs and see if she goes.

https://raw.githubusercontent.com/necrose99/necromancy-overlay/master/app-forensics/xmount/xmount-0.7.3.ebuild cmake's getting on my nerves since they swamped to cmake.

**Comment by necrose99** [comment]
[32;01m * [39;49;00mPackage:    app-forensics/xmount-0.7.3

[32;01m * [39;49;00mRepository: necromancy-overlay

[32;01m * [39;49;00mMaintainer: <invalid metadata.xml>

[32;01m * [39;49;00mUSE:        abi_x86_64 aff amd64 elibc_glibc ewf kernel_linux userland_GNU

[32;01m * [39;49;00mFEATURES:   compressdebug preserve-libs sandbox splitdebug userpriv usersandbox

>>> Unpacking source...

>>> Unpacking xmount-0.7.3.tar.gz to /var/tmp/portage/app-forensics/xmount-0.7.3/work

>>> Source unpacked in /var/tmp/portage/app-forensics/xmount-0.7.3/work

>>> Preparing source in /var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3 ...

>>> Source prepared.

>>> Configuring source in /var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3 ...

>>> Working in BUILD_DIR: "/var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build"

cmake --no-warn-unused-cli -C /var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_DISABLE_FIND_PACKAGE_LibAFF=no -DCMAKE_DISABLE_FIND_PACKAGE_LibEWF=no -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_DO_STRIP=OFF -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build/gentoo_toolchain.cmake  /var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3

Not searching for unused variables given on the command line.

loading initial cache file /var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build/gentoo_common_config.cmake

-- The C compiler identification is unknown

-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc

-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- broken

CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:61 (message):

  The C compiler "/usr/bin/x86_64-pc-linux-gnu-gcc" is not able to compile a

  simple test program.



  It fails with the following output:



   Change Dir: /var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build/CMakeFiles/CMakeTmp



  



  Run Build Command:"/usr/bin/gmake" "cmTC_88512/fast"



  /usr/bin/gmake -f CMakeFiles/cmTC_88512.dir/build.make

  CMakeFiles/cmTC_88512.dir/build



  gmake[1]: Entering directory

  '/var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build/CMakeFiles/CMakeTmp'





  Building C object CMakeFiles/cmTC_88512.dir/testCCompiler.c.o



  /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -march=x86-64 -pipe -o

  CMakeFiles/cmTC_88512.dir/testCCompiler.c.o -c

  /var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build/CMakeFiles/CMakeTmp/testCCompiler.c





  gcc-config: error: could not run/locate 'x86_64-pc-linux-gnu-gcc'



  CMakeFiles/cmTC_88512.dir/build.make:65: recipe for target

  'CMakeFiles/cmTC_88512.dir/testCCompiler.c.o' failed



  gmake[1]: *** [CMakeFiles/cmTC_88512.dir/testCCompiler.c.o] Error 1



  gmake[1]: Leaving directory

  '/var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build/CMakeFiles/CMakeTmp'





  Makefile:126: recipe for target 'cmTC_88512/fast' failed



  gmake: *** [cmTC_88512/fast] Error 2



  



  



  CMake will not be able to correctly generate this project.

Call Stack (most recent call first):

  CMakeLists.txt:2 (project)





-- Configuring incomplete, errors occurred!

See also "/var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build/CMakeFiles/CMakeOutput.log".

See also "/var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build/CMakeFiles/CMakeError.log".

 [31;01m*[0m ERROR: app-forensics/xmount-0.7.3::necromancy-overlay failed (configure phase):

 [31;01m*[0m   cmake failed

 [31;01m*[0m 

 [31;01m*[0m Call stack:

 [31;01m*[0m     ebuild.sh, line   93:  Called src_configure

 [31;01m*[0m   environment, line 2835:  Called cmake-utils_src_configure

 [31;01m*[0m   environment, line  717:  Called _execute_optionally 'src_configure'

 [31;01m*[0m   environment, line  277:  Called enable_cmake-utils_src_configure

 [31;01m*[0m   environment, line 1060:  Called die

 [31;01m*[0m The specific snippet of code:

 [31;01m*[0m       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";

 [31;01m*[0m 

 [31;01m*[0m If you need support, post the output of `emerge --info '=app-forensics/xmount-0.7.3::necromancy-overlay'`,

 [31;01m*[0m the complete build log and the output of `emerge -pqv '=app-forensics/xmount-0.7.3::necromancy-overlay'`.

 [31;01m*[0m The complete build log is located at '/var/tmp/portage/app-forensics/xmount-0.7.3/temp/build.log'.

 [31;01m*[0m The ebuild environment file is located at '/var/tmp/portage/app-forensics/xmount-0.7.3/temp/environment'.

 [31;01m*[0m Working directory: '/var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3_build'

 [31;01m*[0m S: '/var/tmp/portage/app-forensics/xmount-0.7.3/work/xmount-0.7.3'

**Comment by necrose99** [comment]
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=5
SCM=

if [[ ${PV} = 9999 ]]; then
	SCM=git-r3
	EGIT_REPO_URI="https://code.pinguin.lu/diffusion/XMOUNT/xmount.git"
	EGIT_BOOTSTRAP=""
fi
CMAKE_BUILD_TYPE=Release

inherit cmake-utils ${SCM} multilib

DESCRIPTION="Convert on-the-fly between multiple input and output harddisk image types"
HOMEPAGE="https://www.pinguin.lu/xmount"

if [[ ${PV} = 9999 ]]; then
	KEYWORDS=""
else
	SRC_URI="http://files.pinguin.lu/${P}.tar.gz"
	KEYWORDS="~amd64 ~x86"
fi

LICENSE="GPL-3"
SLOT="0"
IUSE="+aff +ewf"

RDEPEND="sys-fs/fuse
	aff? ( app-forensics/afflib )
	ewf? ( app-forensics/libewf )"
DEPEND="${RDEPEND}
	dev-util/pkgconfig"

src_prepare() {
	sed -i -e "s#lib/xmount#$(get_libdir)/xmount#g" $(find -name CMakeLists.txt) || die
}

src_configure() {
	local mycmakeargs=(
		-DCMAKE_DISABLE_FIND_PACKAGE_LibAFF=$(usex !aff)
		-DCMAKE_DISABLE_FIND_PACKAGE_LibEWF=$(usex !ewf)
	)

	cmake-utils_src_configure
}

**Comment by necrose99** [comment]
000175 
000176 
000177 Invalid ebuild name: /var/lib/layman/necromancy-overlay/app-forensics/xmount-bin/xmount-bin-0.7.3-1.ebuild
000178 [ebuild  N    *] app-forensics/xmount-bin-0.7.3.1  USE="aff ewf" 
000179 
000180 The following keyword changes are necessary to proceed:
000181  (see "package.accept_keywords" in the portage(5) man page for more details)
000182 # required by =app-forensics/xmount-bin-0.7.3.1 (argument)
000183 =app-forensics/xmount-bin-0.7.3.1 **
000184 
000185 NOTE: The --autounmask-keep-masks option will prevent emerge
000186       from creating package.unmask or ** keyword changes.
000187 
000188 Use --autounmask-write to write changes to config files (honoring
000189 CONFIG_PROTECT). Carefully examine the list of proposed changes,
000190 paying special attention to mask or keyword changes that may expose
000191 experimental or unstable packages.
000192 *** process completed ***
000193 *** USE="aff ewf" ACCEPT_KEYWORDS='~amd64-linux' emerge --buildpkg --nospinner =app-forensics/xmount-bin-0.7.3.1 ***
000194 Error during set creation: Configuration error in section 'gentoo-zh sets': Could not find repository 'gentoo-zh'
000195 
000196  * IMPORTANT: 21 news items need reading for repository 'gentoo'.
000197  * Use eselect news read to view new items.
000198 
000199 Calculating dependencies  
000200 Invalid ebuild name: /var/lib/layman/necromancy-overlay/app-forensics/xmount-bin/xmount-bin-0.7.3-1.ebuild
000201 ... done!
000202 
000203 >>> Verifying ebuild manifests
000204 
000205 >>> Emerging (1 of 1) app-forensics/xmount-bin-0.7.3.1::necromancy-overlay
000206 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/bin/xmount: No such file or directory
000207 fperms failed
000208 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/lib/xmount/libxmount_input_aaff.so: No such file or directory
000209 fperms failed
000210 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/lib/xmount/libxmount_input_aewf.so: No such file or directory
000211 fperms failed
000212 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/lib/xmount/libxmount_input_aff.so: No such file or directory
000213 fperms failed
000214 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/lib/xmount/libxmount_input_ewf.so: No such file or directory
000215 fperms failed
000216 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/lib/xmount/libxmount_input_raw.so: No such file or directory
000217 fperms failed
000218 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/lib/xmount/libxmount_morphing_combine.so: No such file or directory
000219 fperms failed
000220 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/lib/xmount/libxmount_morphing_raid.so: No such file or directory
000221 fperms failed
000222 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/lib/xmount/libxmount_morphing_unallocated.so: No such file or directory
000223 fperms failed
000224 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/share/doc/xmount/NEWS.gz: No such file or directory
000225 fperms failed
000226 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/share/doc/xmount/README.gz: No such file or directory
000227 fperms failed
000228 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/share/doc/xmount/changelog.Debian.gz: No such file or directory
000229 fperms failed
000230 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/share/doc/xmount/changelog.gz: No such file or directory
000231 fperms failed
000232 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/share/doc/xmount/copyright: No such file or directory
000233 fperms failed
000234 chmod: cannot access /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image//usr/share/man/man1/xmount.1.gz: No such file or directory
000235 fperms failed
000236  * Xmount Binary from Debian Installed, a true from source bump is in the works
000237  * Upstream switched over to Cmake, so 6.x to 7.3 and soon 7.4 has had to be compleatly refactored
000238 >>> Unpacking source...
000239 mv: cannot stat /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/work/usr: No such file or directory
000240 >>> Source unpacked in /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/work
000241 >>> Preparing source in /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/work/xmount-bin-0.7.3.1 ...
000242 >>> Source prepared.
000243 >>> Configuring source in /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/work/xmount-bin-0.7.3.1 ...
000244 >>> Source configured.
000245 >>> Compiling source in /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/work/xmount-bin-0.7.3.1 ...
000246 >>> Source compiled.
000247 >>> Test phase [not enabled]: app-forensics/xmount-bin-0.7.3.1
000248 
000249 >>> Install xmount-bin-0.7.3.1 into /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image/ category app-forensics
000250 >>> Completed installing xmount-bin-0.7.3.1 into /var/tmp/portage/app-forensics/xmount-bin-0.7.3.1/image/
000251 
000252 >>> Done.
000253 
000254 >>> Installing (1 of 1) app-forensics/xmount-bin-0.7.3.1::necromancy-overlay
000255 
000256 Invalid ebuild name: /var/lib/layman/necromancy-overlay/app-forensics/xmount-bin/xmount-bin-0.7.3-1.ebuild
000257 
000258 >>> Recording app-forensics/xmount-bin in "world" favorites file...
000259 
000260  * Messages for package app-forensics/xmount-bin-0.7.3.1:
000261 
000262  * Xmount Binary from Debian Installed, a true from source bump is in the works
000263  * Upstream switched over to Cmake, so 6.x to 7.3 and soon 7.4 has had to be compleatly refactored
000264 >>> Auto-cleaning packages...
000265 
000266 >>> No outdated packages were found on your system.
000267 
000268  * GNU info directory index is up-to-date.
000269 
000270  * IMPORTANT: 21 news items need reading for repository 'gentoo'.
000271  * Use eselect news read to view new items.
000272 
000273 *** process completed ***

**Comment by blshkv** [comment]
Sorry, I can't figure out what have you posted. Could you clean up a bit? Try to use markdown as well. Thanks ..

**Comment by necrose99** [comment]
almost had a debian ebuild working for new xmount i just posted logs. (STOP GAP) 

[Manifest.txt](https://github.com/pentoo/pentoo-overlay/files/46458/Manifest.txt)


[xmount-0.7.3.ebuild.txt](https://github.com/pentoo/pentoo-overlay/files/46460/xmount-0.7.3.ebuild.txt)

also one of the devs helped me tidy up a cmake ebuild for the same. however something frustratingly borks yet still. or yet more broken ish. 
[Manifest-xmount-bin.txt](https://github.com/pentoo/pentoo-overlay/files/46461/Manifest-xmount-bin.txt)
[xmount-bin-0.7.3.1.ebuild.txt](https://github.com/pentoo/pentoo-overlay/files/46462/xmount-bin-0.7.3.1.ebuild.txt)

I tried to refactor something in the xmount-bin (again WE ALL PREFFER from source) however for more immediate use (and note the fact it has MORE ARCH support ie more cpu systems support) 
and funny thing it acts as if the package installs i may have missed axmount-{$pv}.*.deb i think. 
anyhow I figured i'd pass over the logs and a fresh set of eyes.

**Comment by blshkv** [comment]
I'm still not sure what all this noise is about. It compiles just fine from the source.
See 2257c9dc12a565c4e8b94002a83f37400761f372
cheers

**Comment by necrose99** [comment]
Might have been the Live USB , but anyhow I was beating on that ebuild for weeks. 
but i'll can em from necromancy.  mission accomplished.

**Comment by blshkv** [comment]
we have a better ebuild now and you can remove your -bin.ebuild. This is not the right way of doing it.
