### ISSUE TITLE
QCSuper: a tool communicating with Qualcomm-based phones and modems, allowing to capture raw 2G/3G/4G radio frames, among other things

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#482]
https://github.com/P1sec/QCSuper

**Comment by blshkv** [comment]
This primitive python script simply runs wireshark for you.. not sure how useful it is. But let's see how it goes

**Comment by blshkv** [comment]
As expected, there is no further development of this script. Feel free to re-open this bug if there is a progress in future
