### ISSUE TITLE
[missing deps] net-misc/seafile: seaf-cli is doesn't work

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#484]
```bash
linxon@minako-chan /tmp/linxon-tmp-files $ seaf-cli 
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 99, in <module>
    import seafile
ImportError: No module named seafile

```

**Comment by blshkv** [comment]
I spent few days trying to make the tool (both server and client) work, but gave up eventually. There are way too many patches and opened pull requests which need to be addressed.
I'm not wasting my time anymore until my bugs are resolved:
https://github.com/haiwen/seafile-server/issues/236
https://github.com/haiwen/seafile-server/issues/235

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/commit/949e48a21ad229ca7319865faf23933a4e5d4f5f ;-)
