### ISSUE TITLE
rtl8812au_aircrack-ng-5.3.4_p20190511-r1 not building against (gentoo-sources) kernel 5.2.0

### ISSUE THREAD

**Issue by Elleni57** [pentoo/pentoo-overlay#485]
Tried 9999 which compiled fine. I thought, I should report here. Following the build log: 
http://dpaste.com/12EGFE0

Thanks

**Comment by blshkv** [comment]
Thanks. btw, pentoo-sources has few extra patches for wireless hacking, you might want our kernel. It is not always the latest but it was tested and works (usually).
