### ISSUE TITLE
app-misc/needle

### ISSUE THREAD

**Issue by oxr463** [pentoo/pentoo-overlay#486]
> _Needle_ is an open source, modular framework to streamline the process of conducting security assessments of iOS apps.

https://github.com/mwrlabs/needle

Wasn't sure which category to use, so I just used `app-misc`.

Resources:

- https://github.com/mwrlabs/needle/wiki/Installation-Guide#workstation-setup

**Comment by oxr463** [comment]
Also, there is a note about dozer in the [`pentoo/pentoo-mobile` ebuild](https://github.com/pentoo/pentoo-overlay/blob/master/pentoo/pentoo-mobile/pentoo-mobile-2018.4-r2.ebuild#L15).

**Comment by blshkv** [comment]
Hi, thanks for the report. I think the main reason why we don't have both tools in Pentoo yet is a lack of distro-friendly design (setup.py, output to user's dir etc) which would require running additional tests after each new release. Meanwhile,  we do have all required deps (except badly outdated mitmproxy), but the main reason is that main load lies down on users anyway. They need to have a rooted phone with Needle Agent installed and this requires certain skills. If they can do that, they can also fork the tool manually and run it from a local folder ;-)

Anyway, feel free to write an ebuild if you care.

**Comment by blshkv** [comment]
The project is half-dead and I do not think we will see a setup.py anytime soon.
So let's just keep monitoring it. And yes, your pull request will be accepted immediately
