### ISSUE TITLE
Compile error for usbmuxd-1.1.1_pre20190521 (Requested by Anton Bolshakov)

### ISSUE THREAD

**Issue by fkrogh** [pentoo/pentoo-overlay#487]
Result of emerging usbmuxd on a ~amd64 system, as requested.  If you want more just ask for it.  Thanks.
Fred

mon1 ~ # emerge usbmuxd
Calculating dependencies... done!

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) app-pda/usbmuxd-1.1.1_pre20190521::pentoo
 * usbmuxd-1.1.1_pre20190521.tar.gz BLAKE2B SHA512 size ;-) ...         [ ok ]
>>> Unpacking source...
>>> Unpacking usbmuxd-1.1.1_pre20190521.tar.gz to /var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work
>>> Source unpacked in /var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work
>>> Preparing source in /var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work/usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df ...
 * Running eautoreconf in '/var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work/usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df' ...
 * Running libtoolize --install --copy --force --automake ...           [ ok ]
 * Running aclocal -I m4 ...                                            [ ok ]
 * Running autoconf --force ...                                         [ ok ]
 * Running autoheader ...                                               [ ok ]
 * Running automake --add-missing --copy --foreign --force-missing ...  [ ok ]
 * Running elibtoolize in: usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df/
 *   Applying portage/1.2.0 patch ...
 *   Applying sed/1.5.6 patch ...
 *   Applying as-needed/2.4.3 patch ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work/usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df ...
 * systemd functionally was not tested. Please report bugs if any
 * econf: updating usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df/config.guess with /usr/share/gnuconfig/config.guess
 * econf: updating usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df/config.sub with /usr/share/gnuconfig/config.sub
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/usbmuxd-1.1.1_pre20190521 --htmldir=/usr/share/doc/usbmuxd-1.1.1_pre20190521/html --libdir=/usr/lib64 --with-systemd
checking for a BSD-compatible install... /usr/lib/portage/python3.6/ebuild-helpers/xattr/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for x86_64-pc-linux-gnu-gcc... x86_64-pc-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-pc-linux-gnu-gcc accepts -g... yes
checking for x86_64-pc-linux-gnu-gcc option to accept ISO C89... none needed
checking whether x86_64-pc-linux-gnu-gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of x86_64-pc-linux-gnu-gcc... none
checking for x86_64-pc-linux-gnu-g++... x86_64-pc-linux-gnu-g++
checking whether we are using the GNU C++ compiler... yes
checking whether x86_64-pc-linux-gnu-g++ accepts -g... yes
checking dependency style of x86_64-pc-linux-gnu-g++... none
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by x86_64-pc-linux-gnu-gcc... /usr/x86_64-pc-linux-gnu/bin/ld
checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/x86_64-pc-linux-gnu-nm -B
checking the name lister (/usr/bin/x86_64-pc-linux-gnu-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-linux-gnu/bin/ld option to reload object files... -r
checking for x86_64-pc-linux-gnu-objdump... x86_64-pc-linux-gnu-objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-pc-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-pc-linux-gnu-ar... x86_64-pc-linux-gnu-ar
checking for archiver @FILE support... @
checking for x86_64-pc-linux-gnu-strip... x86_64-pc-linux-gnu-strip
checking for x86_64-pc-linux-gnu-ranlib... x86_64-pc-linux-gnu-ranlib
checking command to parse /usr/bin/x86_64-pc-linux-gnu-nm -B output from x86_64-pc-linux-gnu-gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for x86_64-pc-linux-gnu-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... x86_64-pc-linux-gnu-gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if x86_64-pc-linux-gnu-gcc supports -fno-rtti -fno-exceptions... no
checking for x86_64-pc-linux-gnu-gcc option to produce PIC... -fPIC -DPIC
checking if x86_64-pc-linux-gnu-gcc PIC flag -fPIC -DPIC works... yes
checking if x86_64-pc-linux-gnu-gcc static flag -static works... yes
checking if x86_64-pc-linux-gnu-gcc supports -c -o file.o... yes
checking if x86_64-pc-linux-gnu-gcc supports -c -o file.o... (cached) yes
checking whether the x86_64-pc-linux-gnu-gcc linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... x86_64-pc-linux-gnu-g++ -E
checking for ld used by x86_64-pc-linux-gnu-g++... /usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64
checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the x86_64-pc-linux-gnu-g++ linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for x86_64-pc-linux-gnu-g++ option to produce PIC... -fPIC -DPIC
checking if x86_64-pc-linux-gnu-g++ PIC flag -fPIC -DPIC works... yes
checking if x86_64-pc-linux-gnu-g++ static flag -static works... yes
checking if x86_64-pc-linux-gnu-g++ supports -c -o file.o... yes
checking if x86_64-pc-linux-gnu-g++ supports -c -o file.o... (cached) yes
checking whether the x86_64-pc-linux-gnu-g++ linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for x86_64-pc-linux-gnu-pkg-config... /usr/bin/x86_64-pc-linux-gnu-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libusb-1.0 >= 1.0.9... yes
checking for libplist >= 1.11... yes
checking for libimobiledevice-1.0 >= 1.2.1... yes
checking for pthread_create, pthread_mutex_lock in -lpthread... yes
checking for ANSI C header files... (cached) yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking for library containing clock_gettime... none required
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for strcasecmp... yes
checking for strdup... yes
checking for strerror... yes
checking for strndup... yes
checking for stpcpy... yes
checking for ppoll... yes
checking for clock_gettime... yes
checking for localtime_r... yes
checking whether to enable WIN32 build settings... no
checking for supported compiler flags...  -g -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter
checking whether make supports nested variables... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating udev/Makefile
config.status: creating systemd/Makefile
config.status: creating docs/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

Configuration for usbmuxd 1.1.1:
-------------------------------------------

  install prefix ............: /usr
  preflight worker support ..: yes
  activation method .........: systemd
  systemd unit directory ....: /lib/systemd/system
  udev rules directory ......: /lib/udev/rules.d
  compiler ..................: x86_64-pc-linux-gnu-gcc

  Now type 'make' to build usbmuxd 1.1.1,
  and then 'make install' for installation.

>>> Source configured.
>>> Compiling source in /var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work/usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df ...
make -j4 
make  all-recursive
make[1]: Entering directory '/var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work/usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df'
Making all in src
make[2]: Entering directory '/var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work/usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df/src'
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I..  -g -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter  -I/usr/include/libusb-1.0  -O2 -march=native -pipe -c -o usbmuxd-client.o `test -f 'client.c' || echo './'`client.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I..  -g -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter  -I/usr/include/libusb-1.0  -O2 -march=native -pipe -c -o usbmuxd-device.o `test -f 'device.c' || echo './'`device.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I..  -g -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter  -I/usr/include/libusb-1.0  -O2 -march=native -pipe -c -o usbmuxd-preflight.o `test -f 'preflight.c' || echo './'`preflight.c
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I..  -g -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter  -I/usr/include/libusb-1.0  -O2 -march=native -pipe -c -o usbmuxd-log.o `test -f 'log.c' || echo './'`log.c
In file included from /usr/include/sys/time.h:21,
                 from device.c:27:
/usr/include/features.h:185:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
  185 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
preflight.c: In function ‘preflight_worker_handle_device_add’:
preflight.c:236:3: error: unknown type name ‘lockdownd_service_descriptor_t’
  236 |   lockdownd_service_descriptor_t service = NULL;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
preflight.c:236:44: warning: initialization of ‘int’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
  236 |   lockdownd_service_descriptor_t service = NULL;
      |                                            ^~~~
preflight.c:237:92: warning: passing argument 3 of ‘lockdownd_start_service’ from incompatible pointer type [-Wincompatible-pointer-types]
  237 | t_service(lockdown, "com.apple.mobile.insecure_notification_proxy", &service);
      |                                                                     ^~~~~~~~
      |                                                                     |
      |                                                                     int *

In file included from preflight.c:35:
/usr/local/include/libimobiledevice/lockdown.h:82:101: note: expected ‘uint16_t *’ {aka ‘short unsigned int *’} but argument is of type ‘int *’
   82 | e(lockdownd_client_t client, const char *service, uint16_t *port);
      |                                                   ~~~~~~~~~~^~~~

preflight.c:248:3: warning: implicit declaration of function ‘lockdownd_service_descriptor_free’ [-Wimplicit-function-declaration]
  248 |   lockdownd_service_descriptor_free(service);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
preflight.c:249:11: warning: assignment to ‘int’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
  249 |   service = NULL;
      |           ^
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I..  -I../include -I..  -g -Wall -Wextra -Wmissing-declarations -Wredundant-decls -Wshadow -Wpointer-arith -Wwrite-strings -Wswitch-default -Wno-unused-parameter  -I/usr/include/libusb-1.0  -O2 -march=native -pipe -c -o usbmuxd-usb.o `test -f 'usb.c' || echo './'`usb.c
make[2]: *** [Makefile:500: usbmuxd-preflight.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work/usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df/src'
make[1]: *** [Makefile:422: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work/usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df'
make: *** [Makefile:354: all] Error 2
 * ERROR: app-pda/usbmuxd-1.1.1_pre20190521::pentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=app-pda/usbmuxd-1.1.1_pre20190521::pentoo'`,
 * the complete build log and the output of `emerge -pqv '=app-pda/usbmuxd-1.1.1_pre20190521::pentoo'`.
 * The complete build log is located at '/var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/temp/environment'.
 * Working directory: '/var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work/usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df'
 * S: '/var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/work/usbmuxd-8bcbac4d0bf857ef2ccbaf5be4f7af3613f4f5df'

>>> Failed to emerge app-pda/usbmuxd-1.1.1_pre20190521, Log file:

>>>  '/var/tmp/portage/app-pda/usbmuxd-1.1.1_pre20190521/temp/build.log'

**Comment by blshkv** [comment]
@fkrogh you should try to read the error yourself too.
The problematic file is ```/usr/local/include/libimobiledevice/lockdown.h:``` which is not installed by Gentoo/Pentoo. You have probably installed manually using ```make install```.

Run ```rm -r /usr/local``` and never install anything without the portage, i.e. emerge.

**Comment by fkrogh** [comment]
I have a lot in /usr/local and as far as I know there is nothing in my system that I have not installed using emerge.  But I did rm _rf /usr/local/libimobiledevice.  And with that done usbmuxd compiled with no problems.  I'm sorry I bothered you with this issue, but am very grateful that you pointed the way to fix it.

**Comment by blshkv** [comment]
Well, again, Gentoo don't install anything into local. You can may want to investigate. 'enquiry b <path>" is your friend

**Comment by blshkv** [comment]
@fkrogh see "edit" note above ;-)
