### ISSUE TITLE
Pentoo persistence usb

### ISSUE THREAD

**Issue by blackdon2019** [pentoo/pentoo-overlay#490]
Hi guys, i use gentoo and i need to do persistent usb, i tried but i got error ... please help me, the official site says to type changes = / dev / sdXY but when downloading a program it says that there is not enough space being I record on a 64gb pen drive

**Comment by ZeroChaos-** [comment]
/dev/sdXY is an example, you need to say "/dev/sda2" or some other real partition, and that partition must be writable.

**Comment by blshkv** [comment]
we intentionally did not write "sda", so users won't spoil their main disk by blinding copy-pasting the example. Please learn and understand what are you doing before running any commands.

**Comment by blshkv** [comment]
Your report is very weak and there are not many details.
There are two pages reffered to sdXY
https://www.pentoo.ch/docs/bootcheatcodes
https://www.pentoo.ch/docs/faq

Can you provide more details, and also which manual are you trying to follow?

**Comment by blshkv** [comment]
this user is using a just created account, unable to find his own report and unable to provide useful information (logs, screenshots). He must be a troll.

I'm closing this report until we have some useful data.
