### ISSUE TITLE
Pentoo Persistence USB

### ISSUE THREAD

**Issue by blackdon2019** [pentoo/pentoo-overlay#491]
I put a topic about usb persistent and you did not answer me, deleted the topic, I do not know why the forum, but if anyone can answer me would be grateful, because I followed the gentoo wiki but it seems to corrupt the files on boot .. .I expect an answer this time ...

**Comment by blshkv** [comment]
We did not delete it. It is still at the same location:
https://github.com/pentoo/pentoo-overlay/issues/490
