### ISSUE TITLE
wpa_sycophant: relay phase 2 authentication attempts to access corporate wireless

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-overlay#495]
https://sensepost.com/blog/2019/peap-relay-attacks-with-wpa_sycophant/
https://github.com/sensepost/wpa_sycophant

**Comment by linxon** [comment]
SensePost's modified hostapd for wifi attacks: https://github.com/sensepost/hostapd-mana

**Comment by linxon** [comment]
Script for orchestrating mana rogue WiFi Access Points: https://github.com/sensepost/berate_ap

**Comment by blshkv** [comment]
FYI, we used to have "hostapd +mana" patch. But  the separate ebuild is a good idea since you can install both wpe and mana at the same time :+1:

**Comment by blshkv** [comment]
so the initial version is in the tree. I'm closing this issue. We will handle any improvements as it goes.
