### ISSUE TITLE
app-eselect/eselect-metasploit does not work with 17.1 profile

### ISSUE THREAD

**Issue by s-hamann** [pentoo/pentoo-overlay#498]
On 64 bit Gentoo, metasploit is installed into `/usr/lib64/metasploit...`. On modern 17.1 profiles, `/usr/lib` is no longer a symlink to either `/usr/lib32/` or `/usr/lib64/`. eselect-metasploit, however, expects to find metasploit in `/usr/lib/metasploit...`. It is therefore unusable on 17.1 amd64 (or instance).
I hacked around that by replacing every instance of `/usr/lib` with `/usr/lib64` in eselect-metasploit, which works well enough on my system. But this obviously breaks on 32 bit systems.

**Comment by blshkv** [comment]
Please update to ```app-eselect/eselect-metasploit-0.17``` and report back

**Comment by s-hamann** [comment]
Sorry, I forgot to mention that. I was already using `app-eselect/eselect-metasploit-0.17`.

**Comment by blshkv** [comment]
Can you check what is the location of metasploit for you?
```equery f metasploit | more```
It is installed into ```/usr/lib/metasploit4.17``` here.

**Comment by s-hamann** [comment]
Mine goes to `/usr/lib64/metasploit4.17`. I used a custom ebuild, though to get the latest version. Looks like I missed some important changes from the  `::gentoo` version (such as d8b0926).
Sorry, my bad.
