### ISSUE TITLE
Maltego unmasking

### ISSUE THREAD

**Issue by edlovesiraq** [pentoo/pentoo-overlay#499]
Complete noob to gentoo, but I like the wifi tools better then kali. Really nice work. I tried to 
"sudo emerge -a maltego"
and got told there were two masked packages
I then looked at the gentoo page for unmasking
https://wiki.gentoo.org/wiki/Knowledge_Base:Unmasking_a_package
Tried all three recomended unmasking techniqus all with no dice...
Any help is appreciated. I just need maltego on this distro.

**Comment by linxon** [comment]
make `package.accept_keywords` directory in `/etc/portage/` and run this commands:
```bash
~$ emaint sync -r pentoo
~$ echo "app-forensics/maltego ~amd64" > /etc/portage/package.accept_keywords/maltego
~$ emerge -a maltego
```

more: https://wiki.gentoo.org/wiki/ACCEPT_KEYWORDS

**Comment by edlovesiraq** [comment]
Thank you! That was a quick response!

**Comment by blshkv** [comment]
@linxon it's about the license here:
```
The following license changes are necessary to proceed:
 (see "package.license" in the portage(5) man page for more details)
# required by maltego (argument)
>=app-forensics/maltego-4.2.6.12502 all-rights-reserved
```

**Comment by blshkv** [comment]
@linxon I failed to fix it ;-) I'm out for now (it's Friday, 10pm here), please feel free to fix it properly.

**Comment by linxon** [comment]
@edlovesiraq this issue is still relevant?

**Comment by blshkv** [comment]
Well, i have fixed keywords, but not the license.

Apparently, users need to unmask (agree with) the license locally. We can't do it in the profile and there is nothing else we can do here.

**Comment by edlovesiraq** [comment]
@linxon
No unfortunately those isntructions did not work. So how do users unmask license locally? is that the instructions I already followed?  Sorry to keep bugging you and genuinely amazed at the response time. Right now I'm dragging my data from Pento to Kali to do my analysis there. I want to stick with pentoo cause your wireless support is awesome but I have to produce a product at the end that has pretty pictures cause pretty pictures sell.. Please let me know what else I can do to help fix this and I'll continue to dig on my own. appreciate you all,
Ed

**Comment by ZeroChaos-** [comment]
Unmasking a license is well documented.  please try searching google at least a tiny bit before spending 4x as long getting no answers here

**Comment by blshkv** [comment]
Guys, on second thoughts I have realised that this software is not opensource.
I'm very against a freeware, especially in forensic area.

I think that any freeware is a trojan horse potentially or adware at least. Оtherwise, why would someone release it for free? In both cases you should avoid using it.

What is so unique about it? Is any alternative open source software?

**Comment by blshkv** [comment]
https://docs.maltego.com/support/solutions/articles/15000011921-if-maltego-is-open-source-where-can-i-get-the-source-code-
```Maltego is an Open Source Intelligence (OSINT) tool, not to be confused with an open source project```

**Comment by linxon** [comment]
@edlovesiraq 
> how do users unmask license

in the Gentoo based distros have a few methods for accepting licenses.
For example adding manually `category/package <License-Name>` to `/etc/portage/packages.licenses/*` like:
```bash
~$ cat /etc/portage/package.license/maltego
app-forensics/maltego Paterva-EULA
```
implies that you have read the Paterva-EULA license and accepted it. After that you can try to install non-free `category/package`
```
~$ sudo emerge -a app-forensics/maltego
...
```

Please turn your attention to commands in this video: https://asciinema.org/a/8VdGtxJtlA8XjZvU5BKgFGMyp

Links:
https://wiki.gentoo.org/wiki//etc/portage/package.license
https://wiki.gentoo.org/wiki//etc/portage/make.conf#ACCEPT_LICENSE
https://wiki.gentoo.org/wiki/License_groups
https://wiki.gentoo.org/wiki//var/db/repos/gentoo/licenses
