### ISSUE TITLE
udp2raw-tunnel: iptables is an optional dependency

### ISSUE THREAD

**Issue by Hello71** [pentoo/pentoo-overlay#500]
it is only required if option "--auto-rule" is provided, and is not needed if you use nftables or other firewall.

**Comment by linxon** [comment]
done. 

Please report any problem here or close it

**Comment by Hello71** [comment]
ah, sorry. I didn't notice it was used because I'm on systemd. I don't need the unit though, just removing the dependency is fine for me. thanks!
