### ISSUE TITLE
rtl8812au_aircrack-ng building against (gentoo-sources) kernel 5.3.X but not working

### ISSUE THREAD

**Issue by Elleni57** [pentoo/pentoo-overlay#508]
lsmod shows module loaded but it does still not work. 

dmesg with failed 5.3 kernel: 
http://dpaste.com/1W1FKZJ
dmesg with working 5.2 kernel: 
http://dpaste.com/24SRKTH

Anon-E-moose posted in gentoo forum https://github.com/aircrack-ng/rtl8812au/issues/394 with a link about 5.3 support https://github.com/aircrack-ng/rtl8812au/commit/c2fd51ad82af369529c9c3960f7d56c6f949793a

May this solve the problem? Thanks for your help

**Comment by linxon** [comment]
>with a link about 5.3 support aircrack-ng/rtl8812au@c2fd51a

Thank you! I just added this version via https://github.com/pentoo/pentoo-overlay/commit/a21761940fd63992375841b62de0ad6bec6102f7

Now for installing you need sync repo (`emaint sync -r pentoo`) before and unmask this version by adding some lines to `/etc/portage/package.accept_keywords/net-wireless`

```
# Test rtl8812au_aircrack-ng (https://github.com/pentoo/pentoo-overlay/issues/508)
=net-wireless/rtl8812au_aircrack-ng-5.6.4.1_p20190817 **
```




 Please report any problem here or close it

**Comment by linxon** [comment]
@Elleni57 i think it will be better if i add `5.6.4.1_p20190929` version patched by latest commits

Please check also https://github.com/pentoo/pentoo-overlay/commit/95aa4e0e6ab321e0c6e6d7b73e22994c123d9671

**Comment by Elleni57** [comment]
Thank you! Tested rtl8812au_aircrack-ng-5.6.4.1_p20190817 and it works. Will now test patched version with latest commits. Thanks again, much apreciated!

**Comment by Elleni57** [comment]
Compiled  5.6.4.1_p20190929 which works fine too. Thank you very much

**Comment by blshkv** [comment]
@ZeroChaos- you have asked not to bump due to some tests are failing. Could you run again?

**Comment by ZeroChaos-** [comment]
Yes, I will test and add keywords as soon as I have time.

**Comment by Elleni57** [comment]
I see this in dmesg, although connectivity is there: 

Call Trace: rtw_cfg80211_ch_switch_notify+0xd5/0x134 [88XXau] rtw_chk_start_clnt_join+0x66/0x95 [88XXau] join_cmd_hdl+0x276/0x384 [88XXau] ? rtw_chk_start_clnt_join+0x95/0x95 [88XXau] rtw_cmd_thread+0x261/0x3bc [88XXau] ? rtw_stop_cmd_thread+0x34/0x34 [88XXau] kthread+0x113/0x130 ? kthread_park+0x80/0x80 ret_from_fork+0x22/0x40 ---[ end trace b69a0943f723e7b9 ]--- 

uname -a
Linux gentoo1 5.3.7-gentoo #1 SMP PREEMPT Fri Oct 18 21:00:31 CEST 2019 x86_64 AMD Ryzen 5 1600 Six-Core Processor AuthenticAMD GNU/Linux

So there might still be a problem?

**Comment by ZeroChaos-** [comment]
I would say use 9999, but it is broken too. This is upstream's problem, not ours.

**Comment by Elleni57** [comment]
Understood. Thanks for checking anyways

**Comment by blshkv** [comment]
@Elleni57 could you please file a proper bug report to the upstream and link this bug to it. We would like to know what kernel/driver combination work the best.
