### ISSUE TITLE
BloodHound: missing nodes modules for 2.2.1

### ISSUE THREAD

**Issue by s-hamann** [pentoo/pentoo-overlay#509]
`=www-apps/BloodHound-2.2.1` references `https://dev.pentoo.ch/~blshkv/distfiles/${P}-node_modules.tar.gz` as a SRC_URI. However, the file does not exist for version 2.2.1, but only for 2.2.0 and older version.

**Comment by blshkv** [comment]
That's because I was no longer able to compile it and forgot to mask it. The solution seems is upgrade nodejs.

**Comment by blshkv** [comment]
ok, both bugs should be fixed.  but it still fails to compile in sandbox, the error:
```
getaddrinfo EAI_AGAIN github.com
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
