### ISSUE TITLE
BloodHound: hardcoded lib dir

### ISSUE THREAD

**Issue by s-hamann** [pentoo/pentoo-overlay#510]
The ebuilds for BloodHound provide a wrapper script (`/usr/bin/BloodHound`) to start BloodHound. This wrapper script contains a hardcoded path to the lib directory, which may be inconsistent with the actual installation directory. On my 17.1 amd64 profile, I get BloodHound in `/usr/lib64/BloodHound` and the wrapper script tries using `/usr/lib/BloodHound`.

The ebuild should probably use `$(get_libdir)` consistently.

**Comment by blshkv** [comment]
ok, I'll push it shortly, together with https://github.com/pentoo/pentoo-overlay/issues/509
