### ISSUE TITLE
Responder: hardcoded lib dir

### ISSUE THREAD

**Issue by s-hamann** [pentoo/pentoo-overlay#511]
The ebuilds for responder provide a wrapper script (`/usr/sbin/responder`) to start responder. This wrapper script contains a hardcoded path to the lib directory, which may be inconsistent with the actual installation directory. On my 17.1 amd64 profile, I get responder in `/usr/lib64/responder` and the wrapper script tries using `/usr/lib/responder`.

The ebuild should probably use `$(get_libdir)` consistently.

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/issues/510

**Comment by blshkv** [comment]
my bad, I read it from a mobile and thought it is a duplicate. It is not! Why you didn't correct me?

**Comment by blshkv** [comment]
Thanks! Please let me know you have any other suggestions.

**Comment by s-hamann** [comment]
Thank you. I was unsure how you prefer handling these very similar issues. I would have commented on this issue if you had not noticed yourself.
