### ISSUE TITLE
dirsearch: Breaks if ~/.dirsearch/ does not exist

### ISSUE THREAD

**Issue by s-hamann** [pentoo/pentoo-overlay#512]
When starting dirsearch, e.g. as `dirsearch --help`, it throws the following Exception:

```
Traceback (most recent call last):
  File "/usr/share/dirsearch/dirsearch.py", line 38, in <module>
    main = Program()
  File "/usr/share/dirsearch/dirsearch.py", line 32, in __init__
    self.arguments = ArgumentParser(self.script_path)
  File "/usr/share/dirsearch/lib/core/ArgumentParser.py", line 33, in __init__
    self.parseConfig()
  File "/usr/share/dirsearch/lib/core/ArgumentParser.py", line 144, in parseConfig
    shutil.copyfile(FileUtils.buildPath(self.script_path, 'default.conf'), configPath)
  File "/usr/lib64/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '~/.dirsearch/dirsearch.conf'
```

This is cause by the attempt to copy the default config file to the home directory and works once `~/.dirsearch/` is manually created. However, this is not exactly obvious from the trace.
I would be good to instruct the user to create the directory or simply have dirsearch create it.

Note: This is an issue caused by `add_homedir_support.patch`, not an upstream issue.
Apart from that, I really like the patch :)

**Comment by blshkv** [comment]
@linxon could you improve it please?

@s-hamann now, it *is* the upstream problem ;-)

**Comment by linxon** [comment]
@blshkv please update link to patch on [Issue](https://github.com/maurosoria/dirsearch/issues/176)
from https://github.com/pentoo/pentoo-overlay/blob/master/net-analyzer/dirsearch/files/add_homedir_support.patch 
to https://github.com/pentoo/pentoo-overlay/blob/master/net-analyzer/dirsearch/files/add_homedir_support-r1.patch
