### ISSUE TITLE
[oldstable] net-analyzer/maketh: source code/binary is unavailable

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#515]
https://github.com/pentoo/pentoo-overlay/blob/684197110f2d451162e29c4d056644eba861a540/net-analyzer/maketh/maketh-0.2.0.ebuild#L8-L9

https://simpp-kode.tuxfamily.org/maketh/index.html — 404 not found
http://packetstorm.wowhacker.com/UNIX/scanners/ — 403 error

**Comment by blshkv** [comment]
the tool is dead, but here we go
