### ISSUE TITLE
Using pentoo on raspberry pi

### ISSUE THREAD

**Issue by drforbin** [pentoo/pentoo-overlay#526]
I'd like to do an install on raspberry pi. I know it uses ARM. Any suggestions on how to install?

**Comment by blshkv** [comment]
Get gentoo arm iso, add pentoo overlay, run update. Profit.

**Comment by necrose99** [comment]
@drforbin I have already ben researching this on the side. 
@blshkv 
https://github.com/sakaki-/gentoo-on-rpi-64bit 
this will run on arm64 rpi3 or 4 

note this should be a remote pentoo , ie a recon augment.  ie Battery ETC , with 5G or https://www.cbrsalliance.org/ a 5G varrinat , WIFI with Miles in range ..... 
https://pastebin.com/3x3uyWC7 , or some other perssitnt cloud ssh and a recon augment ..
NOT for mainline pentoo , use, but can be used to automate a Micro-Pentoo... to do recon or other redteam tasks. 

note UPSTREAM support for some...  Packages ARM64 has been REFUSED by authors less someone else in community adds a patch.. 
https://github.com/nabla-c0d3/nassl/issues/39 


trying to open a binhost until of late was a cost prohibitive measure ...
Downsizing is never fun , and for a time my house hold internet had the shi----tiest DSL or 4G connection posible APT complex is bifurcated 1/2 blessed cable 1/2 in the ATT&T "Fiber-Optic" DSL zone you sniffle and the truck role to fix 2 weeks later ..... 

also soon done , I'll have genric Arm64 /RPI.x and Pine/ROCK64 on repo. 

unmasking lots of packages for arm64 can be done...   @sakaki- repos for a tip.. on how .. **READ'EM**

Rock64pro etc has a Chromeos  DEV build , wich has  most of gentoo etc inside.. 
however will need to read-add pentoo repo 

however I'm hopping to launch an alpha repo of soorts for more meddlesome tinkerers soon ish..

**Comment by necrose99** [comment]
https://github.com/ayufan-rock64/chromiumos-build/releases
https://github.com/psychedup/gentoo-pine64 , kernels/ could use the gentoo experamental/pentoo patches panfrost-sources ayufan-sources
