### ISSUE TITLE
net-proxy/zaproxy: jdk8 is also work.

### ISSUE THREAD

**Issue by OwenChia** [pentoo/pentoo-overlay#53]
Maybe we can using jdk8 instead of jdk7?

**Comment by ZeroChaos-** [comment]
have you tested zaproxy for actual use with jdk8?

**Comment by blshkv** [comment]
We want a stable version from portage so that no other packages would break.
Also, we are trying to avoid proprietary products and use Icedtea java for now. Unfortunately, there is no version 8 available. 

What is the reason of this request?

**Comment by OwenChia** [comment]
@ZeroChaos- 
I using java8 to run this for a while, it's work for me.

@blshkv 
Version 7 is ok. And I agreed with the action trying to avoid proprietary products. I just want to request a choice, let user can decide which version to use. Seems like we can only using version 7 for now, but it's ok, version 8 is not a necessity. 
```
virtual/jre:1.7 virtual/jdk:1.7
```

**Comment by blshkv** [comment]
our intention was to block java6 since zaproxy require java7 and above. I've adjusted it in the commit above. Thank a lot for reising it.
