### ISSUE TITLE
kamene package status

### ISSUE THREAD

**Issue by gpotter2** [pentoo/pentoo-overlay#535]
Hi,

I noticed you are still packaging [kamene](https://github.com/pentoo/pentoo-overlay/tree/9b99e5f919e8536b3711267d8e4c9d7e9de4e31d/dev-python/kamene).

If you have a look at the project, it's pretty dead. It's a fork of Scapy (which also exists in pentoo-overlay) that is getting severely outdated (still contains tons of bugs that ended up being fixed on Scapy), and should probably be considered for removal. 

While it made sense at the time where Scapy didn't support Python 3, it's pretty redundant nowadays to have both. No libraries depend on it.

I thought you might want to clean up outdated projects from what I've seen in https://github.com/pentoo/pentoo-overlay/issues/525. In any case feel free to close this issue.

Thanks for your time & have a good day

**Comment by gpotter2** [comment]
I see you've decided to keep it band upgrade it.
That works too, have a good day

**Comment by blshkv** [comment]
@linxon what's the point of keeping it? I mean the tool is not that old, some tools in our tree haven't been updated for years. But still, scapy merged all improvements and it should be used instead

**Comment by linxon** [comment]
@blshkv I absolutely don't care about fate of this package

**Comment by blshkv** [comment]
gone! ;-)
