### ISSUE TITLE
app-crypt/pinentry +gnome-keyring

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#536]
I had to add `app-crypt/pinentry gnome-keyring` to my `/etc/portage/package.use` for my system to update again. However, I noticed the same line in [profiles/pentoo/base/package.use/app-crypt](https://github.com/pentoo/pentoo-overlay/blob/master/profiles/pentoo/base/package.use/app-crypt), although only commented-out, with an interesting comment directly above it.

Did you guys notice the same? How should we properly fix this issue?

**Comment by blshkv** [comment]
yeah, I made gnome-keyring optional in case if you don't want to install it. For example, I use KDE and don't want to run both wallets. It also confuses browsers (chrome) because it can support both.

Can you remove that use flag and post the full ```emerge -DNua --tree world``` output?

**Comment by ZeroChaos-** [comment]
I fixed this already. There was a new gnome-keyring we needed to fork.

**Comment by gkroon** [comment]
Thanks a lot!
