### ISSUE TITLE
jgraphx fails size check

### ISSUE THREAD

**Issue by alokan** [pentoo/pentoo-overlay#538]
!!! Fetched file: jgraphx-4.0.3.zip VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      211468
!!! Expected: 4851209

Syncing the over didn't fix it.
Rebuilding the manifest didn't either.

**Comment by blshkv** [comment]
yeah, they have moved to github, but their webserver doesn't respond with the proper 404 error message.
