### ISSUE TITLE
bettercap ebuild

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#54]
https://github.com/necrose99/necromancy-overlay/blob/master/dev-ruby/bettercap/bettercap-1.1.7.ebuild
I used the fake gem ebuild skeleton 
CCNA Exam prep testbank prep till /drool out of side of mouth.  and a shower ...before I leave for class 
so no testing of ebuild till this evening perhaps.  
ZC is right Cisco exams are sado maso.... well torture... /grumbles :-(

<knoppers> is the menu issue fixed?
* Appleman1234 has quit (Ping timeout: 256 seconds)
<knoppers> Zero_Chaos: I will use pentoo if some important tools will added
<knoppers> weevely3 and bettercap
<knoppers> and maybe ZIB
<knoppers> links:
<knoppers> https://github.com/evilsocket/bettercap

**Comment by lugarius** [comment]
Thanks for the pull request
   (knoppers)

**Comment by lugarius** [comment]
I am a bettercap fan, its like the updated ettercap...

**Comment by blshkv** [comment]
Thanks for the ebuild, I've added missed deps and committed it.

**Comment by ZeroChaos-** [comment]
any justification for adding to the livecd?

**Comment by blshkv** [comment]
I dont see why not. It's newer, command line, more stable (as the author claims) and does not take much space

**Comment by ZeroChaos-** [comment]
added

**Comment by lugarius** [comment]
Thank you
