### ISSUE TITLE
EAPI=2 non supported anymore...

### ISSUE THREAD

**Issue by iadegesso** [pentoo/pentoo-overlay#543]
Please update the packages in the sys-kernel subtree that still use the version 2 of EAPI...

Thanks,

Iade Gesso, PhD in Computer Science

**Comment by blshkv** [comment]
chromeos-sources-9999.ebuild
odroid-sources-9999.ebuild
odroidxu-sources-9999.ebuild

**Comment by blshkv** [comment]
ok, fixed, but I'm not sure which branch is the latest. Feel free to suggest if you use it
