### ISSUE TITLE
hak5  c2-2.1.2  rough ebuild 

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#544]
```
# Copyright 2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

DESCRIPTION="Statically linked Binaries for HAK5.org C2 Cloud Comannd and control Services"

HOMEPAGE="https://c2.hak5.org/"
SRC_URI="https://storage.googleapis.com/cloudc2/c2-2.1.2_community.zip"
LICENSE="Freeeware,Commercial"
SLOT="0"
KEYWORDS="~amd64 ~x86 ~armv7 armv6 armv5 arm64 darwin64"

# RDEPEND="app-arch/zip || virtual/szip " sha256 

S=${WORKDIR}

src_unpack() {
S=${WORKDIR}
}

#src_prepare() {
# test bin-packages in zip 
sha256sum -c sha256sums || die "sha256sums are bad!"

}

src_install() {
	dodir /opt/hak5/c2/bin/
	copy c2_community* /opt/hak5/c2/bin/
	fixperms r+x  /opt/hak5/c2/bin/c2_community-$ARC/opt/hak5/c2/bin/c2_community-$ARCH 
	dosym /opt/hak5/c2/bin/c2_community-$ARCH /opt/hak5/c2/bin/hak5c2 
	dosym /opt/hak5/c2/bin/c2_community-$ARCH /usr/bin/hak5c2 
	#make_desktop_entry ${PN} hak5c2 ## make less paint to Exe.. via shells 

		dobin /opt/hak5/c2/bin/c2_community-$ARCH # do system arch 

```
## fix me to rig the symlink/s  insted.  sha256sums to test file/s integ. 
ARCH="
    x86?   ( c2_community-linux-32 ) ## meh who cares but for an embeded Ardiono Micro-pentoo instance to link to your main pentoo... 
    AMD64? ( c2_community-linux-64)
	ARMv5?  (c2_community-linux-armv5)
	ARMv6?  (c2_community-linux-armv6)
	ARMv7?  (c2_community-linux-armv7)
	ARM64?  (c2_community-linux-armv8)
	DARWIN64? ( c2_community-darwin-64)"
	
`    ## dodir /opt/hak5/c2/bin/  ## put alt bins hear too. dosym /opt/hak5/c2/bin/ && /usr/bin for active platform ie `
}	
	
	post_install () {
	ewarn "you need a Freeware community Licience key/ or paid options from hak5.org store" 
	einfo " can buy the Community Edition for 0$ or the more pro options " 
	einfo " the Ebuild hasn't fetch restrictions , however licinece etc dirs may need be setup. /opt/hak5/c2/ manually for now" 
	einfo "package includes Windows/Linux/ or MacOs bins , symlink/s is set only for System specific Architecture  " 
## adds c2 bins for Various hak5 embeded devices and or if anyone ifs brave enough to put pentoo on rpi4 etc via sakakki-s  rpi Gentoo image... etc..  however needs to be modded for grub2-efi etc for making pentoo kern.. images less hell... 
	}
```

**Comment by necrose99** [comment]
[hak5-c2-bin.ebuild.txt](https://github.com/pentoo/pentoo-overlay/files/4022419/hak5-c2-bin.ebuild.txt)

**Comment by necrose99** [comment]
https://github.com/GoVanguard/c2_cloud

**Comment by blshkv** [comment]
Not willing to support their propraritary hardware and ship a demo version

**Comment by necrose99** [comment]
Was more or less looking to use on open hardware ie rpi.. etc.  But likewise test cloud services.. 
But noted,  point of porting Pentoo on arm64 is to replace thier 50 devices to a few rpi loaded up to do the same.

**Comment by necrose99** [comment]
If the c2 sources were more open source and bit flexible,  be more a fan. 
However,  open source hardware,  likewise more a preference,  can reuse the gear in the same manner,  or reconfigure to repurpose latter.  
Rpi4/rpi3  or etc ie andino infinitely more flexible..  than the per hak5 shop gear. But ill happily (ab)use thier connection toy on open hardware if its a possibility.

**Comment by blshkv** [comment]
The pineapple wireless software is not open source either
