### ISSUE TITLE
dev-ruby/em-http-request-1.1.5 download/emerge fails

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#546]
A couple of problems to report.
Current metasploit from fresh github pull requires ruby >= 2.5. So, I'm working with that, locally.
First, I needed to mask:
=dev-ruby/cookiejar-0.3.3::pentoo
=dev-ruby/em-http-request-1.1.5::pentoo

I added ruby25 to USE_RUBY for my local copies of those ebuilds. While cookiejar built (I may have had it in distfiles already), em-http-request wouldn't download with this line as written:
SRC_URI="mirror://rubygems/${P}.gem"

Changing that to this allowed me to complete the emerge:
SRC_URI="https://rubygems.org/downloads/${P}.gem"

Did I totally screw up my end, or are there changes that need to be applied throughout?

**Comment by blshkv** [comment]
these two were outdated. Should work now
