### ISSUE TITLE
Cannot update world

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#549]
Hi all,

I noticed something that may need require fixing, but I'm not sure how yet:

```
sudo emerge --deep --update --newuse -kb --changed-use --changed-deps --newrepo @world
 
These are the packages that would be merged, in reverse order:

Calculating dependencies... done!

emerge: there are no ebuilds built with USE flags to satisfy ">=dev-ruby/did_you_mean-1.2.0:2.5[ruby_targets_ruby25]".
!!! One of the following packages is required to complete your request:
- dev-ruby/did_you_mean-1.2.1::gentoo (Change USE: +ruby_targets_ruby25)
(dependency required by "dev-lang/ruby-2.5.7::gentoo" [ebuild])
(dependency required by "media-gfx/graphviz-2.42.3::gentoo[ruby]" [installed])
(dependency required by "dev-python/pydot-1.4.1::gentoo" [installed])
(dependency required by "dev-util/androguard-3.3.5::pentoo" [installed])
(dependency required by "pentoo/pentoo-mobile-2020.1-r1::pentoo[android,pentoo-full]" [installed])
(dependency required by "pentoo/pentoo-2015.1::pentoo[mobile]" [installed])
(dependency required by "@selected" [set])
(dependency required by "@world" [argument])
```

Stable dev-lang/ruby-2.4.9 depends on stable dev-ruby/did_you_mean-1.2.1.
However, dev-ruby/did_you_mean-1.2.1 only has ruby25 as target
I noticed we still block ruby25 (see profiles/pentoo/base/make.defaults:65), probably because our old Metasploit still requires ruby24, right?

This blocks me from updating world and I was wondering if you guys have similar issues?

**Comment by blshkv** [comment]
Do you use pentoo profile?

**Comment by gkroon** [comment]
Technically yes, let me explain: I use [my own overlay](https://gitlab.com/0bs1d1an/0bs1d1an-overlay) which is depending on the pentoo overlay, and I use my own profile, which is depending on the `pentoo:pentoo/hardened/linux/amd64` profile.

In my overlay:

```
$ cat metadata/layout.conf 
# Slave repository rather than stand-alone
masters = gentoo pentoo
profile-formats = portage-2
```

```
$ cat profiles/0bs1d1an/hardened/linux/amd64/parent 
pentoo:pentoo/hardened/linux/amd64
0bs1d1an:0bs1d1an/base
```

**Comment by blshkv** [comment]
Ok, great. It sounds that Gentoo is moving to ruby25, we need to fix metasploit

**Comment by ZeroChaos-** [comment]
Updating to ruby25 is on my short list. Stand by.

**Comment by blshkv** [comment]
Just out of curiosity, I forked all rails packages to resolve it properly.
See the following for more details:
https://bugs.gentoo.org/708768
