### ISSUE TITLE
I need Bleachbit for some programs I want to write

### ISSUE THREAD

**Issue by lugarius** [pentoo/pentoo-overlay#55]
And its a nice wipe and privacy tool
http://bleachbit.sourceforge.net/

**Comment by ostree** [comment]
This is already available: http://gpo.zugaina.org/sys-apps/bleachbit
(btw to find this ebuild took me 10s)

Kind Regards

**Comment by blshkv** [comment]
The tool is in Gentoo tree already, under sys-apps/bleachbit

**Comment by ZeroChaos-** [comment]
this bug is about adding it to the livecd.  perhaps @lugarius would care to provide some reasoning why he needs it?

**Comment by lugarius** [comment]
I didn't found it on the toollist,

**Comment by lugarius** [comment]
I need it for the program I am making, its only a bashfile so its hard to make a cleanup manually.
I think some users want some security in cache and ram things, I am thinking about an ramcleaner too

**Comment by lugarius** [comment]
Well, I think it wouldn't be the last time I contact you for such things, I am developing gtkdialog based scripts to make simple guis for terminal programmers like wget, httrack, tor, I2p, torshammer and mktorrent

**Comment by blshkv** [comment]
@ZeroChaos- This software is designed to clean a home directory. There is no point to have on a livecd

**Comment by ZeroChaos-** [comment]
agreed.  users can install this if they like.
