### ISSUE TITLE
app-antivirus/veil: needs a working version of metasploit for testing

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#552]
https://bugs.gentoo.org/678962
https://bugs.gentoo.org/701410

**Comment by blshkv** [comment]
Use pentoo. It works in Pentoo overlay

**Comment by blshkv** [comment]
I don't understand what is the issue. I can't reproduce bugs, there is dev-ruby/pg-0.21.0 in the tree.
