### ISSUE TITLE
net-misc/corstest: drop/upgrade to py3/replace

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#553]
https://github.com/RUB-NDS/CORStest
Latest commit: Jul 4, 2019

**Comment by blshkv** [comment]
@grimmlin feel free to revert it if you care

**Comment by blshkv** [comment]
https://github.com/RUB-NDS/CORStest/issues/8

**Comment by blshkv** [comment]
I think it was a mistake to push this package in the first place. It has 7 commits and no updates since then. The project is dead. I'm removing it
