### ISSUE TITLE
dev-python/responder ebuilds include deprecated PYTHON_USEDEP

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#558]
Suggest replacing PYTHON_USEDEP by PYTHON_SINGLE_USEDEP, or possibly no mention of USEDEP at all...?
Also, responder-3.0.0.0 currently has PYTHON_COMPAT=( python2_7 ). This version of responder supports python3. Suggest updating to this or some such:
PYTHON_COMPAT=( python{2_7,3_{6,7,8}} )

**Comment by blshkv** [comment]
The upstream is working on it:
https://github.com/lgandx/Responder/issues/104

**Comment by blshkv** [comment]
you are right, it supports python3. Fixed, thanks!
