### ISSUE TITLE
net-wireless/op25: drop/upgrade to py3/replace

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#559]
python3: https://github.com/boatbod/op25/issues/29

**Comment by ZeroChaos-** [comment]
The SDR stuff is special and has to all be upgraded together. It's in my
to-do list.

**Comment by jkldgoefgkljefogeg** [comment]
3.8.1.0-rc1~gnuradio~bionic-1 is python3 only. op25 won't run at all.
