### ISSUE TITLE
NetworkManager not running; 

### ISSUE THREAD

**Issue by lugarius** [pentoo/pentoo-overlay#56]
i will write a programm what fixes this and include it in my programm

rc-update add NetworkManager 
/etc/init.d/NetworkManager restart

**Comment by ostree** [comment]
Hello,
this is not a bug - this is a feature, nothing here to fix

r3

**Comment by lugarius** [comment]
Ok understand, here again, all are saying that pentoo is only a pentest os, but its so much more!
That's why I use it.

**Comment by blshkv** [comment]
Yeah, it is intentionally disabled livecd for forensics and even pentest guys. But feel free to install pentoo (it can be installed even on a usb drive) and customize it as you want.

**Comment by ZeroChaos-** [comment]
@lugarius Please learn to read, your life will be much better if you do.  The motd shows when you log in and tells you how to enable network manager.  Just in case that isn't enough, there is also a shortcut on the desktop

**Comment by lugarius** [comment]
The shortcut is on the root dir....
There its something wrong withe the system, the installer is not doing well
