### ISSUE TITLE
app-forensics/stegdetect: drop or replace

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#562]
Homepage: http://www.outguess.org/ (link is dead)
https://github.com/pentoo/pentoo-overlay/blob/de7a8ac49d6a3d96f563d2797783991e30948886/app-forensics/stegdetect/stegdetect-0.6-r1.ebuild#L12-L13

**Comment by blshkv** [comment]
replace with https://github.com/rokkuran/stegasawus? something to investigate

**Comment by linxon** [comment]
I found these:
https://github.com/zed-0xff/zsteg — is a ruby project
https://github.com/bannsec/stegoVeritas — python3

**Comment by linxon** [comment]
`zsteg` looks as fresh... I can try to write ebuild for it 

@blshkv what do you think? :)
maybe we need to add both of them?

**Comment by blshkv** [comment]
both tools have recent commits actually. Looking at the language choose I would say python is better, Looking at the size, zsteg is bigger. But zsteg was on idle since 2014 until recently.

So the best way, would be to get samples, run both tools and compare ;-)

**Comment by blshkv** [comment]
https://pypi.org/project/stegoveritas-binwalk/ binwalk supports stegoveritas

**Comment by necrose99** [comment]
https://github.com/teovoinea/steganography 
cargo-ebuild and done.
