### ISSUE TITLE
dev-libs/qbdi: drop/upgrade to py3/replace

### ISSUE THREAD

**Issue by linxon** [pentoo/pentoo-overlay#563]
PR: https://github.com/QBDI/QBDI/pull/121

**Comment by gkroon** [comment]
Does this mean that 0.7.0 can be removed then?

**Comment by blshkv** [comment]
do we need this tool?

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/commit/55ec66212ce1073cde176cbcf0825977d2fffac9
