### ISSUE TITLE
net-misc/rdesktop-brute-1.5.0 fails with multiple errors

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#564]
From the build log:
secure.c:307:9: error: storage size of 'mod' isn't known
secure.c:307:14: error: storage size of 'exp' isn't known
secure.c:307:19: error: storage size of 'x' isn't known
secure.c:307:22: error: storage size of 'y' isn't known
secure.c:539:22: error: dereferencing pointer to incomplete type 'X509' {aka 'struct x509_st'}
secure.c:552:50: error: dereferencing pointer to incomplete type 'EVP_PKEY' {aka 'struct evp_pkey_st'}

[build.log.txt](https://github.com/pentoo/pentoo-overlay/files/4207015/build.log.txt)
[emerge-info.txt](https://github.com/pentoo/pentoo-overlay/files/4207016/emerge-info.txt)
[emerge-pqv.txt](https://github.com/pentoo/pentoo-overlay/files/4207017/emerge-pqv.txt)
[environment.txt](https://github.com/pentoo/pentoo-overlay/files/4207018/environment.txt)

**Comment by blshkv** [comment]
well, I ported that patch long time ago but there is no reason of using it today. We keep it for historical reasons. I'll just mask it.

medusa/hydra/ncrack does a better job (multithreading etc)
https://hackertarget.com/brute-forcing-passwords-with-ncrack-hydra-and-medusa/
https://security.stackexchange.com/questions/186347/simple-hydra-test-with-windows-rdp
