### ISSUE TITLE
Webcrawler HTTrack 

### ISSUE THREAD

**Issue by lugarius** [pentoo/pentoo-overlay#57]
https://raw.githubusercontent.com/gentoo/gentoo/a8eb7d7fa7bb9ceaec76cdb7c536434141160edf/www-client/httrack/httrack-3.48.21-r1.ebuild

**Comment by blshkv** [comment]
Please provide a short description in your bugreports so we would know what do you want to fix/improve

This tool is in the Gentoo already already. run ```emerge www-client/httrack``` and install it. This is not a security tool and should not be on a livecd by default.
