### ISSUE TITLE
app-crypt/cuda-rarcrypt: drop?

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#574]
I propose to remove app-crypt/cuda-rarcrypt as it's no longer in active development, cannot currently be merged due to depending on outdated CUDA versions, and I think hashcat and john are already great substitutes.

**Comment by necrose99** [comment]
http://www.crark.net/download/crark55-linux.rar **BUMP**
@gkroon

**Comment by gkroon** [comment]
@necrose99 that is a pre-compiled version. I was not able to find its source code. Perhaps I overlooked, but I don't think they offer it anymore, hence is why I proposed to drop this tool.

**Comment by necrose99** [comment]
https://github.com/gentoo-mirror/menelkir/blob/master/app-crypt/cuda-rarcrypt/cuda-rarcrypt-3.2-r1.ebuild

Bit stale but perhaps can dig for sources 
This link has active src.

**Comment by necrose99** [comment]
https://sourceforge.net/projects/cracx/

One tool to break them all zip rar etc. And newer.

**Comment by gkroon** [comment]
> https://sourceforge.net/projects/cracx/
> 
> One tool to break them all zip rar etc. And newer.

That seems like a single jar file, but what's wrong with hashcat / john?

**Comment by blshkv** [comment]
so the project is dead. crark-55 is a new version but it is proprietary binary. Le'ts remove it
