### ISSUE TITLE
gtkdialog or zenity 

### ISSUE THREAD

**Issue by lugarius** [pentoo/pentoo-overlay#58]
i need one of them for my toolkit that i want to make for Pentoo. /join #lugaverse
i thought it was installed...
What should I use,  what is easier for you to push on the live iso

PS: if i annoy you please say

**Comment by blshkv** [comment]
@lugarius You are trying to customise liveCD for your needs and requested to install few new packages (such as issue #57), but not related to security field.  We will likely reject such requests unless it is required and/or better (better than xdialog, for example). 

Please consider liveCD as a demo or use it in some urgent cases. As the main line, you should install it and customise it as you want: disable unused software, remove unnecessary features (via USE flag) and install what you need. This is where Pentoo/Gentoo rocks.

**Comment by lugarius** [comment]
Ok understood! :)
