### ISSUE TITLE
www-apps/beef needs update in package.accept_keywords to reflect current version

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#595]
package.accept_keywords currently references 0.4.4.5, but current version in the tree is 0.5.0.0. Also, adding a line for it in my own file with ~amd64 didn't work, so I went full on '**' , which worked for my local installation. Maybe KEYWORDS should not be commented out?

**Comment by ZeroChaos-** [comment]
it's a work in progress. thanks for testing.

**Comment by bill-e-ghote** [comment]
Appreciate the support, as always. Thanks.
