### ISSUE TITLE
create setup.py and support system wide installation

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-overlay#596]
This is a common problem that many tools which we want to distribute do not support system wide installation. Many of these tools provide their own "install.sh" or "setup.sh" instead of a proper setup.py.

This bug report will be a reference point for such bug reports.

https://github.com/derv82/wifite2/issues/102

**Comment by AmericanY** [comment]
1. You need to add `wheel` to the requirement as well.
```
pip install wheel
```

2. You need to install `dev` according to your `Python` version. (etc 3.8)
```
sudo apt install python3.8-dev
```

3. You need to install `gcc` (etc. for Ubuntu)

```
sudo apt install build-essential
```

Then you can apply the following to have the latest versions of the required packages.

```
pip install requests bs4 psutil
```

And Finally:

```
python setup.py install
```

**Comment by AmericanY** [comment]
`wheel` need to be install at 1st place. because psutil and bs4 will fail if wheel is not installed.

**Comment by blshkv** [comment]
We don't use pip and don't have apt. Wrong bug report?

**Comment by blshkv** [comment]
And you should not never run '''pip install requests bs4 psutil''' your pip should install it automatically
