### ISSUE TITLE
[Tool Request] - lulzbuster

### ISSUE THREAD

**Issue by noptrix** [pentoo/pentoo-overlay#601]
homepage: www.nullsecurity.net
tool page: https://nullsecurity.net/tools/scanner.html
repo link: https://github.com/nullsecuritynet/tools
direct link: https://github.com/nullsecuritynet/tools/raw/master/scanner/lulzbuster/release/lulzbuster-1.3.2.tar.xz

**Comment by blshkv** [comment]
"A very fast and smart web-dir/file enumeration tool written in C for the lulz"

We have few tools of such: net-analyzer/dirb net-analyzer/dirble-bin may be others
