### ISSUE TITLE
[Tool Request] - dnsspider

### ISSUE THREAD

**Issue by noptrix** [pentoo/pentoo-overlay#602]
homepage: www.nullsecurity.net
tool page: https://nullsecurity.net/tools/scanner.html
repo link: https://github.com/nullsecuritynet/tools
direct link: https://github.com/nullsecuritynet/tools/raw/master/scanner/dnsspider/release/dnsspider.py

**Comment by blshkv** [comment]
Why it is better than amass ?

**Comment by noptrix** [comment]
> Why it is better than amass ?

Who told you that this is better than $tool? Do we have to compare each tool with all public tools out there before submitting a request?

**Comment by blshkv** [comment]
You can ask someone who is using a tool, and he will tell. Yes, we have to compare, especially dns recon tools. There is something crazy going on in this category, look at https://github.com/pentoo/pentoo-overlay/issues/273.
There are dozens of such tools exist today. Some tools written on different languages, but other is just "one day" scripts with lesser functionally. We do not want to waste our time on such tools.

**Comment by blshkv** [comment]
Right. Thanks for the very cooperative and productive discussion.

**Comment by noptrix** [comment]
Sorry, you really made my day with your comments. And stop creating rumors on public channels :)
