### ISSUE TITLE
[Tool Request] - nullscan

### ISSUE THREAD

**Issue by noptrix** [pentoo/pentoo-overlay#603]
homepage: www.nullsecurity.net
tool page: https://nullsecurity.net/tools/automation.html
repo link: https://github.com/nullsecuritynet/tools
direct link: https://github.com/nullsecuritynet/tools/raw/master/automation/nullscan/release/nullscan-1.0.0.tar.xz

**Comment by blshkv** [comment]
"A modular framework designed to chain and automate security tests."

There are few similar tools:
net-analyzer/owtf
https://github.com/jaeles-project/jaeles
