### ISSUE TITLE
GDA-android-reversing-Tool: GDA(GJoy Dex Analysizer)

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-overlay#605]
https://github.com/charles2gan/GDA-android-reversing-Tool
GDA is a new decompiler written entirely in c++, so it does not rely on the Java platform, which is succinct, portable and fast, and supports APK, DEX, ODEX, oat.

**Comment by blshkv** [comment]
no sources, no go
https://github.com/charles2gan/GDA-android-reversing-Tool/issues/2

**Comment by illnyang** [comment]
he uses VMProtect and he's chinese. it's potential malware.

**Comment by blshkv** [comment]
That's a very racist comment. We all seen leaks from NSA too. Trust no one

**Comment by illnyang** [comment]
It's not about the race, it's about nationality. 5eyes alliance is the second greatest threat to world peace.

**Comment by blshkv** [comment]
Well, may be. After NSA right?
