### ISSUE TITLE
Metasploit is now masked by Gentoo

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#606]
Metasploit has now been masked, since 2020-03-29:

https://github.com/gentoo/gentoo/blob/210c808ab9c6e54419edd69df3fa0965f3a9ab86/profiles/package.mask#L77-L102

The old Metasploit ebuilds in the Gentoo tree [0] are reverse dependencies of the deprecated (and masked) Rails 4.2. There's also an old bug report [1] that asks for a bump. Tbh, I dare not touch it myself, but I noticed @ZeroChaos- maintains this one, correct?

[0]: https://packages.gentoo.org/packages/net-analyzer/metasploit
[1]: https://bugs.gentoo.org/678962

**Comment by blshkv** [comment]
msf is removed from pentoo because rails:4 is EOL.
https://github.com/rapid7/metasploit-framework/issues/13175

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/commit/9e770bba6512d1f4e75a6fba766523446f306b45
