### ISSUE TITLE
app-forensics/eagleeye: cannot be merged due to masked deps in the Gentoo tree

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#607]
`app-forensics/eagleeye` is already in the Pentoo tree but is still WIP. It had some repoman issues which I wanted to fix just now, but I cannot finish the ebuild at this time.

`app-forensics/eagleeye` relies on `dev-python/requests-html`, which relies on the currently masked `dev-python/pyee`: https://github.com/gentoo/gentoo/blob/0a12a4be19e751566109c3649aeb1def6ffec9af/profiles/package.mask#L398-L558

I've already asked for `dev-python/pyee` to remain in the tree: https://bugs.gentoo.org/711808#c67

**Comment by gkroon** [comment]
I've also asked to not remove a few other python packages that some Pentoo ebuilds depend on: https://bugs.gentoo.org/711808#c69

**Comment by blshkv** [comment]
just fork it if it is required.
