### ISSUE TITLE
app-forensics/rekall-core: needs to be fixed

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#608]
I bumped to py3 and fixed some repoman issues in 2853667c0a4977fb1ec4ed4b8d9e7584852496bc, but it seems this package install its 'resources' dir to '/usr/resources'. That must be wrong, and it has done so since before I touched it. Could anyone help me?

**Comment by blshkv** [comment]
I think you should report to the upstream

**Comment by linxon** [comment]
it's pyenv oriented framework and works fine only with this :)

I guess, we need to drop this package or create a new eclass for pyenv installation support

**Comment by blshkv** [comment]
No, should not make any difference

**Comment by blshkv** [comment]
The "resources" directory got some unused stuff, I think. So you can install anywhere you want.
Also, the huge list of deps is missing.
Please fix it ;-)

**Comment by blshkv** [comment]
btw, that setup.py full of workarounds and illegal calls (runs system commands with pip").
Need to be cleanup by upstream.
