### ISSUE TITLE
dsniff -- replace deprecated des_ methods with DES_

### ISSUE THREAD

**Issue by leciacu** [pentoo/pentoo-overlay#61]
dsniff uses deprecated des_* methods from the openssl library.

This becomes an issue, when trying to compile it against libressl, which removed des_ in favor of DES_:
> ./sshcrypto.c:32:2: error: unknown type name ?des_key_schedule?
>  des_key_schedule k1, k2, k3;

Below is a simple patch for dsniff(~2.4_beta1-r5), with trivial changes des_ -> DES_, created using [libressl porting guide](https://wiki.freebsd.org/LibreSSL/PatchingPorts#Deprecated_des__methods)
Patch: [libressl.patch.txt](https://github.com/pentoo/pentoo-overlay/files/80460/libressl.patch.txt)

**Comment by blshkv** [comment]
dsniff was written 2002. Gentoo still supports it for some reason. I will file a bug report in bugzilla too.

**Comment by blshkv** [comment]
In case if you want to monitor it: https://bugs.gentoo.org/show_bug.cgi?id=571138

Thanks for the reporting
