### ISSUE TITLE
media-libs/mesa USE setting: vulkan

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#611]
The following REQUIRED_USE flag constraints are unsatisfied:
    vulkan? ( any-of ( video_cards_i965 video_cards_iris video_cards_radeonsi ) )

Apparently due to:
grep vulkan /var/lib/layman/pentoo/profiles/pentoo/base/package.use/media-libs
media-libs/mesa gbm gles1 gles2 osmesa pic vulkan xa xvmc

As I don't have any of these video cards, does it make sense to have this as a default USE setting?

**Comment by ZeroChaos-** [comment]
the pentoo video_cards do have it as a default, so it makes sense as a default.   That said, it's one of the very few mesa use flags that don't just silently disable when unsupported, so I'll back this out for now and file a gentoo bug.  thanks.
