### ISSUE TITLE
wifiphisher

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#614]
The Rogue Access Point Framework https://wifiphisher.org
 
[wifiphisher-1.4.ebuild.txt](https://github.com/pentoo/pentoo-overlay/files/4650527/wifiphisher-1.4.ebuild.txt)

[roguehostapd-1.0.ebuild.txt](https://github.com/pentoo/pentoo-overlay/files/4650529/roguehostapd-1.0.ebuild.txt)

https://pypi.org/project/PyRIC/  might be a dep.

**Comment by ZeroChaos-** [comment]
Geez, how many different hostapd hacks do we really need?  I vote 1.

**Comment by blshkv** [comment]
The latest release was back in 2018, project is python2 only. Let's pass on it.
We have net-wireless/wifipumpkin3 (wip) as an alternative. Feel free to help with the ebuild (upstream refused to fix few issues)
