### ISSUE TITLE
analyzer/greenbone-security-assistant-9.0.1 failes due to file checksum failure

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#617]
2020-05-23 15:48:39 (4.71 MB/s) - '/usr/portage/distfiles/gsa-node-modules-9.0.1.tar.__download__' saved [44176347/44176347]

!!! Fetched file: gsa-node-modules-9.0.1.tar VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      44176347
!!! Expected: 228392960
Refetching... File renamed to '/usr/portage/distfiles/gsa-node-modules-9.0.1.tar._checksum_failure_.dfrg4yx7'

!!! Couldn't download 'gsa-node-modules-9.0.1.tar'. Aborting.
 * Fetch failed for 'net-analyzer/greenbone-security-assistant-9.0.1'

>>> Failed to emerge net-analyzer/greenbone-security-assistant-9.0.1

**Comment by ZeroChaos-** [comment]
Based on size that looks like you just had an incomplete download.  Does it reliably fail the same way?

**Comment by blshkv** [comment]
I switched from my own tar-ball to a provided by upstream and forgot to update it. Thanks!
