### ISSUE TITLE
dev-lang/powershell-bin: Can it also depend on llvm-libunwind

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-overlay#618]
I tried to emerge `net-im/discord-bin`.
But it fails due to dependency conflict: discord needs `sys-libs/llvm-libunwind` which is blocked by `sys-libs/libunwind`.
`sys-libs/libunwind` is used by `dev-lang/powershell-bin-7.0.1-1:0/0::pentoo`.

**My question:**
Could pentoos 'dev-lang/powershell-bin' also use `sys-libs/llvm-libunwind`?

**Comment by blshkv** [comment]
Can you try and report back?

**Comment by blshkv** [comment]
ok, so from /usr/portage/sys-libs/libcxxabi/libcxxabi-9.0.1.ebuild:
```
        libunwind? (
                || (
                        >=sys-libs/libunwind-1.0.1-r1[static-libs?,${MULTILIB_USEDEP}]
                        >=sys-libs/llvm-libunwind-3.9.0-r1[static-libs?,${MULTILIB_USEDEP}]
                )
```

That mains it's compatibly, but it also means that you should not even see this error because libcxx* should pick up the another lib

**Comment by Wuodan** [comment]
But `net-im/discord-bin` depends on `sys-libs/libcxx`, not on `libcxxabi` and thus I see this error. Just try to emerge discord-bin and I think you would see it yourself.

I just tried it, powershell-bin can build and start with `sys-libs/llvm-libunwind`, was about to prepare pull-request. Your choice, I don't need powershell-bin.

**Comment by Wuodan** [comment]
Tnx a lot for your fix!

**Comment by blshkv** [comment]
I think the roof the problem is both packages are compiled (-bin). I just change the dep to libcxx to make it simpler, no idea if it's really required but it works ;-)
