### ISSUE TITLE
LiveUSB forces password change after flushchanges

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-overlay#619]
I'm using an usb-stick with the iso on it. `flushchanges` lets me save my changes across reboot, which is quite handy.
But I'm still forced to change my password (or set a new one) during each new boot of that usb-stick.
My feeling is that this does not make sense or is even insecure, since you don't need to enter my previous password to set a new one.

I tried to find out what's happening so maybe I could fix it:

**pentoo-overlay/pentoo/pentoo-livecd/files/livecd-setpass-r1**
Script for the password reset. It checks if the password is unset with:
`sudo grep -q "pentoo:!" /etc/shadow`
then the script removes itself from ~/.bashrc.
Nice!

**/mnt/cdrom/modules/zz_changes-00.lzm**
SquashFS file where flushchanges stores changes. Contains an /etc/shadow with a set password for user pentoo. The above check with grep works as intended.

**~/.bashrc**
livecd-setpass is not in there.

This is where I gave up. Don't see why I'm still forced to reset password.
Thought maybe the squashfs overlay is not up and running when password-reset happens, but the nvidia driver check comes before that and it only builds the nvidia driver at first boot and uses that built driver on subsequent boots. So the squash fs overlay seems to be up when password reset is forced.

**Comment by blshkv** [comment]
could you copy-paste this issue and file it again under https://github.com/pentoo/pentoo-livecd/issues please?
