### ISSUE TITLE
Pentoo RC2.6 Installer Fails

### ISSUE THREAD

**Issue by DaKahuna** [pentoo/pentoo-overlay#62]
After going through all of the steps to install Pentoo in a VMware Workstation virtual machine (60GB Hard drive, 4 GB RAM, 1 processor core) all of the steps complete and when I go to exit the main install window I get an error message saying an error was encountered.  I go back to the main install window and select exit again and it exits back to the screen from which I ran the install tool (same issue occurs in both the GUI and from the command line).  When I rebooth the VM, grub fails to run and all I get is a black screen. 

Attached is the /tmp/pentoo-installer.log for reference as requested on IRC by Zero_Chaos. (renamed to pentoo-installer.txt since .log is unsupported for attachments). 

[pentoo-installer.txt](https://github.com/pentoo/pentoo-overlay/files/80706/pentoo-installer.txt)

**Comment by DaKahuna** [comment]
At blshkv's request I tried installing Pentoo RC4.6 on my Windows 10 Host using VirtualBox instead of VMware.  Attached is the pentoo-installer.txt file from that effort.  It also failed the same as under VMware.
[pentoo-installer.txt](https://github.com/pentoo/pentoo-overlay/files/83813/pentoo-installer.txt)

**Comment by blshkv** [comment]
see the main bug https://github.com/pentoo/pentoo-installer/issues/8 for workaround
