### ISSUE TITLE
www-servers/tornado: in pentoo, but now offered by gentoo

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#620]
Shall we delete these in our tree then? Just checking before I remove and make someone furious.

**Comment by ZeroChaos-** [comment]
it was forked because gentoo doesn't support python2_7 anymore and we needed it to
```
zero@theprophet tornado % diff -Naur . ~/development/gentoo-x86/www-servers/tornado | grep PYTHON_COMPAT                                                                      (git)-[master] 
-PYTHON_COMPAT=( python2_7 python3_6 )
+PYTHON_COMPAT=( python3_6 )
-PYTHON_COMPAT=( python2_7 python3_{6,7,8} )
+PYTHON_COMPAT=( python3_{6,7,8} )
-PYTHON_COMPAT=( python2_7 python3_{6,7,8} )
-PYTHON_COMPAT=( python2_7 python3_{6,7,8} )
+PYTHON_COMPAT=( python3_{6..9} )
-PYTHON_COMPAT=( python2_7 python3_{6,7,8} )
+PYTHON_COMPAT=( python3_{6..9} )
```

Try not to break the dep tree :-P

It stays.

**Comment by blshkv** [comment]
What package requeries it? Can we fix it?

**Comment by ZeroChaos-** [comment]
Please read the diff, gentoo does NOT offer python 2.7 support.  If you want to know what needs it type "equery d tornado".

**Comment by blshkv** [comment]
That's the thing, I can't find any

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/commit/76fddf829c734b489c399c682f58161e41ae222d
pyzmq: fork including www-servers/tornado to restore python 2.7 support for urh

However, urh does not python2 anymore.

**Comment by ZeroChaos-** [comment]
So the deps are actually wrong in gentoo because reality breaks gentoo.  Urh is compatible with gnuradio 3.7 and needs to use python 3.7 with it.  We can kill that stuff after more testing of gr 3.8
