### ISSUE TITLE
net-analyzer/set: drop / upgrade to py3 / replace

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#626]
This one should be ready for py3 now: https://github.com/trustedsec/social-engineer-toolkit/issues/622, but it's horrible to install. See the setup.py they created: https://github.com/trustedsec/social-engineer-toolkit/blob/master/setup.py

I also noticed our ebuild is still very much a WIP and misses several files in its `${FILESDIR}`. Could someone look into this?

**Comment by blshkv** [comment]
in short, set is not supported because upstream does not understand packaging.
They use hardcoded paths, they call pip3 from setup.py and so on.
Not supported until someone willing to fix the current ebuild
