### ISSUE TITLE
dev-libs/radare2-bindings: drop / upgrade to py3 / replace

### ISSUE THREAD

**Issue by gkroon** [pentoo/pentoo-overlay#628]
I'm guessing this one should be able to build using py3 (see https://github.com/radareorg/radare2-bindings/commit/e4d4a87edc6ccc8cce6f39c3552f43e9fe71e04f), but I can't even build the current version. Also, I'm not really sure what this is for, and it doesn't seem to have any reverse dependencies. Could someone look into this?

**Comment by blshkv** [comment]
it used to be a GUI package written on Python which required it. But let's keep it for bit longer.
