### ISSUE TITLE
Section 'pentoo-overlay' in repos.conf has location attribute set to nonexistent directory

### ISSUE THREAD

**Issue by ostree** [pentoo/pentoo-overlay#643]
I try to add an overlay to the list of system overlays and use pentoo-overlay but:

	emerge app-eselect/eselect-repository
	eselect repository add pentoo-overlay git https://github.com/pentoo/pentoo-overlay.git
	source /etc/profile
	eselect repository list -i
	Available repositories:
  	[158] gentoo # (https://gentoo.org/)
  	[285] pentoo-overlay @

	eselect profile list
(no expected pento0 profiles on the list of profiles)

	emerge pentoo -s
	!!! Section 'pentoo-overlay' in repos.conf has location attribute set to nonexistent directory: '/var/db/repos/pentoo-overlay'
	WARNING: One or more repositories have missing repo_name entries:

	/var/db/repos/pentoo-overlay/profiles/repo_name

	NOTE: Each repo_name entry should be a plain text file containing a
	unique name for the repository on the first line.

How easy would be to fix this?

**Comment by ZeroChaos-** [comment]
This was fixed ELEVEN years ago from the loom of the current tree.  https://github.com/pentoo/pentoo-overlay/blob/master/profiles/repo_name

**Comment by blshkv** [comment]
Don't run "add pentoo_overlay git". Pentoo is in the list, so just refresh it

**Comment by ostree** [comment]
Thank you, working on a lxc container this is what I did:

lxc launch images:gentoo/current/amd64 releng-gentoo
lxc exec releng-gentoo /bin/bash
emerge catalyst eselect-repository
emerge dev-vcs/git -va
eselect repository list | grep pentoo
mkdir -p /etc/portage/repos.conf
nano -w /etc/eselect/repository.conf
eselect repository list | grep pentoo
eselect repository list -i
eselect repository enable pentoo
emerge --sync

btw also realized that there was no git installed by default. 

regards

**Comment by blshkv** [comment]
It's just :
Eselect repository add pentoo
One line
