### ISSUE TITLE
sys-apps/razercfg missing file

### ISSUE THREAD

**Issue by Anonymous1157** [pentoo/pentoo-overlay#647]
The ebuild for razercfg in this overlay contains `newinitd "${FILESDIR}"/razerd.init.d-r2 razerd ` in `src_install`, but there is no files directory so the build fails in the install phase. The missing directory and file exists for the version in the main Gentoo overlay, but not in this overlay.

I'm kind of surprised the version has been bumped recently and regularly yet no one has noticed this.

**Comment by blshkv** [comment]
fixed, thanks. My intention was to clean old patches and cleaned init.d script by accident.
