### ISSUE TITLE
Aircrack-ng failed to compile

### ISSUE THREAD

**Issue by GrbavaCigla** [pentoo/pentoo-overlay#658]
[info.txt](https://github.com/pentoo/pentoo-overlay/files/4952745/info.txt)
[pqv.txt](https://github.com/pentoo/pentoo-overlay/files/4952746/pqv.txt)
[build.txt](https://github.com/pentoo/pentoo-overlay/files/4952753/build.txt)

**Comment by ZeroChaos-** [comment]
Aircrack-ng isn't compatible with GCC 10 yet.  Once upstream fixes it I will pull the fix into Gentoo.
