### ISSUE TITLE
app-crypt/hashcat-6.0.0-r1: No OpenCL-compatible or CUDA-compatible platform found.

### ISSUE THREAD

**Issue by Wuodan** [pentoo/pentoo-overlay#661]
### Hashcat failure with Nvidia
Hashcat does not work on my hardware, both after installation and on USB with vanilla ISO pentoo-full-amd64-hardened-2020.0_p20200716.iso.
[hashcat.output.txt](https://github.com/pentoo/pentoo-overlay/files/4955860/hashcat.output.txt)
```
hashcat (v6.0.0) starting...

cuInit(): forward compatibility was attempted on non supported HW

clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

ATTENTION! No OpenCL-compatible or CUDA-compatible platform found.

You are probably missing the OpenCL or CUDA runtime installation.

* AMD GPUs on Linux require this driver:
  "RadeonOpenCompute (ROCm)" Software Platform (3.1 or later)
* Intel CPUs require this runtime:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* NVIDIA GPUs require this runtime and/or driver (both):
  "NVIDIA Driver" (440.64 or later)
  "CUDA Toolkit" (9.0 or later)
```

I installed anything named '*cuda*' without success.

### nvidia-smi fails too
It outputs: `Failed to initialize NVML: Driver/library version mismatch`

### lspci -v
Output is attached.
[lspci-v.txt](https://github.com/pentoo/pentoo-overlay/files/4955861/lspci-v.txt)

### How to install nvidia-cuda-toolkit
If you want to install nvidia-cuda-toolkit, then there's a file collision that you have to workaround, see:
- Gentoo bug: https://bugs.gentoo.org/733458
- Working ebuild: https://github.com/Wuodan/gentoo-overlay/tree/master/dev-util/nvidia-cuda-toolkit

**Comment by ZeroChaos-** [comment]
output of "hashcat -I" please?

**Comment by Wuodan** [comment]
```
$ hashcat -I
hashcat (v6.0.0) starting...

clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

ATTENTION! No OpenCL-compatible or CUDA-compatible platform found.

You are probably missing the OpenCL or CUDA runtime installation.

* AMD GPUs on Linux require this driver:
  "RadeonOpenCompute (ROCm)" Software Platform (3.1 or later)
* Intel CPUs require this runtime:
  "OpenCL Runtime for Intel Core and Intel Xeon Processors" (16.1.1 or later)
* NVIDIA GPUs require this runtime and/or driver (both):
  "NVIDIA Driver" (440.64 or later)
  "CUDA Toolkit" (9.0 or later)
```

**Comment by Wuodan** [comment]
nvidia-smi works now. Think there was a mismatch between running kernel and kernel when nvidia-drivers were built (pentoo-updater)
```
$ sudo nvidia-smi 
Wed Jul 22 23:57:19 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 450.57       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   55C    P8     2W /  N/A |      6MiB /  5934MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      7167      G   /usr/bin/X                          4MiB |
+-----------------------------------------------------------------------------+
```

**Comment by ZeroChaos-** [comment]
I presume hashcat now works as well?

**Comment by Wuodan** [comment]
No, it doesn't, that output of `hashcat -I` is fresh. Don't have cuda yet on this new installation, it needs gcc-8 which failed to build.

**Comment by Wuodan** [comment]
Installed `dev-util/nvidia-cuda-toolkit` first, then `dev-util/nvidia-cuda-toolkit`. `hashcat -I` still outputs the same error.

**Comment by ZeroChaos-** [comment]
Is this resolved on your end?  I added pentoo/pentoo-opencl which actually checks that the uvm use flag is turned on, but past that I'm not sure what you need.  Maybe your user doesn't have permission?  I added my user to the video group, that makes it run as a user for me...

**Comment by Wuodan** [comment]
Suddenly it works!
Didn't do any update in 2 weeks and it just worked as root. Adding user to video group also helps.
Can't really say what changed and can't imagine that I never tried as root.
Thanks a lot!
