### ISSUE TITLE
pentoo-core login broken

### ISSUE THREAD

**Issue by ZeroChaos-** [pentoo/pentoo-overlay#666]
public note to self that forced password setting at boot doesn't appear to work on pentoo-core

**Comment by blshkv** [comment]
it were few changes in pentoo-core. Was this bug fixed? Why it happened in the first place?

**Comment by ZeroChaos-** [comment]
Spent all day building isos and making little fixes, I will check the latest result in about an hour.  As for what happened, it was a completely untested iso, made blind for a specific purpose with no time for testing or iterating.  Which is why I am fixing it now.

**Comment by blshkv** [comment]
what is the progress here?

**Comment by ZeroChaos-** [comment]
Closed: worksforme
