### ISSUE TITLE
pefile-1.2.10-139.tar.gz: Filesize does not match recorded size

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#67]
I had this problem at the beginning of the day, and resynched again just now but the problem persists:

!!! Fetched file: pefile-1.2.10-139.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      56819
!!! Expected: 57322

**Comment by blshkv** [comment]
Thanks. Apparently, the upstream modified and broke the tarball (https://github.com/erocarrera/pefile/issues/65) during migration to github. I was using the copy from code.google.com.

Shoud be fixed in a8f8b5cc769634830ea49bba111ff22205bbd8b4
