### ISSUE TITLE
net-mail/davmail-bin[server] should not assume make_desktop_entry is available

### ISSUE THREAD

**Issue by equaeghe** [pentoo/pentoo-overlay#677]
The net-mail/davmail-bin ebuild contains the line

https://github.com/pentoo/pentoo-overlay/blob/8c940e279d4b3d7f1d11bd3a9f7836cedfce92e4/net-mail/davmail-bin/davmail-bin-5.5.1.3299.ebuild#L43

However, on headless servers, `desktop.eclass` is not necessarily available and therefore also not `make_desktop_entry`. I get the following warning in the build log:
```
/var/tmp/portage/net-mail/davmail-bin-5.5.1.3299/temp/environment: line 2250: make_desktop_entry: command not found
```

I think this line should only be active when the `server` use flag is not active.

**Comment by ZeroChaos-** [comment]
An inherit is missing for desktop, but it is always available, even on headless servers.

**Comment by equaeghe** [comment]
> An inherit is missing for desktop, but it is always available, even on headless servers.

Ah, OK. I guess you'll fix it, if you find the time?

**Comment by equaeghe** [comment]
Thanks for fixing.
