### ISSUE TITLE
net-mail/davmail-bin[server]: please add systemd service file

### ISSUE THREAD

**Issue by equaeghe** [pentoo/pentoo-overlay#679]
The RPM and deb file for davmail contain a systemd service file. It would be useful to include and install as well with the ebuild. The RPM one seems immediately compatible; I've installed it locally, and it works. I attach it here (extra `.txt` to allow upload).

[davmail.service.txt](https://github.com/pentoo/pentoo-overlay/files/5274267/davmail.service.txt)

**Comment by blshkv** [comment]
no idea if it's a proper way. Please create a pull request if you care

**Comment by equaeghe** [comment]
See https://github.com/pentoo/pentoo-overlay/pull/681

**Comment by blshkv** [comment]
Have you seen my comment or just overwrote it with your variant? Will it work on systems without systemd?

**Comment by equaeghe** [comment]
> Have you seen my comment or just overwrote it with your variant? Will it work on systems without systemd?

I'm not exactly clear what comment you mean. If you refer to the systemd use flag that I removed: yes it should work on all systems. See for example the [mlocate ebuild](https://github.com/gentoo/gentoo/blob/master/sys-apps/mlocate/mlocate-0.26-r3.ebuild).

N.B.: Your version was not correct in terms of how it installed the systemd unit file.

**Comment by blshkv** [comment]
Ok, done. Thanks

**Comment by blshkv** [comment]
Ok, done. Thanks
