### ISSUE TITLE
dev-util/jd-cmd: new tool

### ISSUE THREAD

**Issue by oxr463** [pentoo/pentoo-overlay#680]
See: https://github.com/kwart/jd-cmd

**Comment by oxr463** [comment]
This is very useful in conjunction with `dev-util/dex2jar` and `dev-util/apktool`.

**Comment by blshkv** [comment]
Ok I tried to build a proper ebuild and gave up. Basically, this CLI tools requires more dependencies than GUI.
One of them, logback, requires recent slf4j which is not in Gentoo yet and I'm not willing to for it.

So the best bet would be to create a '-bin' ebuild which would pull a jar provided by the upstream.

**Comment by X-method** [comment]
Hello, forgive the ignorance but why not just run the Maven build (declared in pom.xml)? ebuild could download a maven bin and run the build that way, I guess.

**Comment by blshkv** [comment]
Because portage is like Maven but different packet manager. It has it's own dependencies, it downloads all packages in sandbox so other software like Maven will be in jail

**Comment by blshkv** [comment]
FYI, https://github.com/kwart/jd-cmd/issues/40
