### ISSUE TITLE
net-analyzer/wpscan: dependency conflict

### ISSUE THREAD

**Issue by Kruezenberg** [pentoo/pentoo-overlay#682]
When emerging net-analyzer/wpscan-3.8.7-r1, emerge fails with this error : 
```ruby
Bundler couldr not find compatible versions for gem "public_suffix":
  In Gemfile:
    wpscan was resolved to 3.8.7, which depends on
      cms_scanner (~> 0.12.1) was resolved to 0.12.1, which depends on
        opt_parse_validator (~> 1.9.2) was resolved to 1.9.2, which depends on
          addressable (>= 2.5, < 2.8) was resolved to 2.6.0, which depends on
            public_suffix (>= 2.0.2, < 4.0)

    wpscan was resolved to 3.8.7, which depends on
      cms_scanner (~> 0.12.1) was resolved to 0.12.1, which depends on
        public_suffix (~> 4.0.3)
```

**Comment by blshkv** [comment]
@ZeroChaos- don't be shy, fix it

**Comment by ZeroChaos-** [comment]
I don't see a resolvable solution to those deps, I don't know how to fix it.  I'm not shy about fixing bugs, this one I don't know how to fix

**Comment by blshkv** [comment]
@Kruezenberg use our profile. You need dev-ruby/addressable 2.7.0 and may be more

**Comment by ZeroChaos-** [comment]
how about we set the deps in the ebuild correctly instead of whining about our profile?

**Comment by blshkv** [comment]
wpscan deps are correct, and according to to upstream. Open Gentoo bug if you care

**Comment by blshkv** [comment]
there are probably two packages with conflicting dependencies. The only way to fix it is to adjust keywords, i.e. use our profile

**Comment by Kruezenberg** [comment]
Adding ~amd64 keyword to `dev-ruby/addressable` (version 2.7.0) works. No need for more.

**Comment by blshkv** [comment]
yes, you might face other issues with other tools.  You can also link keywords if changing profile is too much, see https://github.com/pentoo/pentoo-overlay/wiki/Set-up
