### ISSUE TITLE
asleap fixes & improvements

### ISSUE THREAD

**Issue by chinarulezzz** [pentoo/pentoo-overlay#683]
Hello Pentoo team,

I improved a little bit asleap:
- fixed bruteforce patch to brute both leap & pptp
- added "custom charset" cmdline argument
- added the possibility to crack pptp from command-line arguments "Username/Challenge/Response" _(same as LEAP's Challenge/Response arguments behavior)_

Here are the patches: https://github.com/chinarulezzz/asleap.

BTW, Sorry for not filing the issue with a pull request. I just used your patches myself and wanted to share some fixes and improvements.

Kind Regards,
A.

**Comment by blshkv** [comment]
The tool is dead, i was wondering if we can drop it. What would be an alternative?

**Comment by ZeroChaos-** [comment]
hashcat and john have some overlap but sadly not complete overlap.  as such, it hasn't been dropped yet

**Comment by blshkv** [comment]
ok, let's keep it for a bit longer since it takes 1 min to apply these patches ;-)

@chinarulezzz it would be also helpful if you could port it to the libxcrypt-4.x

Thanks!
