### ISSUE TITLE
redasm unbuildable

### ISSUE THREAD

**Issue by RayOfLight1** [pentoo/pentoo-overlay#686]
Hey, redasm-2.1.1 ebuild can't be built because of QPainterPath QT5 change, also it seems that the source code in github is quite old and abandoned, so I don't know what to propose here.

Maybe trying adding this patch?

https://gitlab.fechner.net/mfechner/Gitlab/-/blob/master/devel/redasm/files/patch-widgets_disassemblerlistingview_disassemblercolumnview.cpp

Regards,

**Comment by RayOfLight1** [comment]
```
--- redasm-2.1.1/widgets/disassemblerlistingview/disassemblercolumnview.cpp.orig        2020-05-21 11:13:41 UTC
+++ redasm-2.1.1/widgets/disassemblerlistingview/disassemblercolumnview.cpp
@@ -1,6 +1,7 @@
 #include "disassemblercolumnview.h"
 #include "../../themeprovider.h"
 #include <QPainter>
+#include <QPainterPath>

 DisassemblerColumnView::DisassemblerColumnView(QWidget *parent) : QWidget(parent), m_disassembler(nullptr), m_first(-1), m_last(-1)
 {
```

confirmed working on my end :)

**Comment by Dax89** [comment]
@RayOfLight1 REDasm is not abandoned.
The branches are just rotated (master <-> noplugin) because I'm restructuring the source code which may break packages

(I'm the developer)
