### ISSUE TITLE
gnuradio mask

### ISSUE THREAD

**Issue by latot** [pentoo/pentoo-overlay#69]
hi, please mask net-wireless/gnuradio-3.7.9 actually fails in gentoo 64:
```
>>> Failed to emerge net-wireless/gnuradio-3.7.9, Log file:
>>>  '/var/tmp/portage/net-wireless/gnuradio-3.7.9/temp/build.log'
```

**Comment by blshkv** [comment]
It doesn't fail here. Please open a bug report at upstream and provide the buildlog

**Comment by blshkv** [comment]
There is an open bug report which might affects you:
https://bugs.gentoo.org/show_bug.cgi?id=571334

**Comment by blshkv** [comment]
No responce from the reporter. Also, the upstream bug  is closed. See the same link for details
