### ISSUE TITLE
app-forensics/volatility: no compatible distorm64

### ISSUE THREAD

**Issue by Plexvola** [pentoo/pentoo-overlay#692]
I know `app-forensics/volatility` is legacy, and volatility3 is in the overlay anyway, but fyi the Gentoo repositories don't provide `dev-libs/distorm64` with python2.7 compatibility (which is a dependency of `app-forensics/volatility`)

**Comment by blshkv** [comment]
Agree, it's time to migrate for everyone. Thanks!
