### ISSUE TITLE
pentoo-installer failes to rsync '/mnt/gentoo/root/'

### ISSUE THREAD

**Issue by KjetilOO** [pentoo/pentoo-overlay#695]
Hi!

When I run pentoo-installer to install from the bootable USB-stick to my harddrive I get the following error:

Failed to rsync
'/mnt/gentoo/root/'. See the log
output for more information

And the log says:
pentoo@pentoo /tmp $ cat pentoo-installer-callbacks.log
sending incremental file list
rsync: [sender] link_stat "/root/*" failed: No such file or directory (2)

sent 19 bytes  received 12 bytes  62.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=3.2.3]
pentoo@pentoo /tmp $

I run the ready built ISO (full, hardened, x86) from December 15th 2020.

Thanks!

Best regards,
Kjetil

PS: Thanks for a great tool!

**Comment by blshkv** [comment]
it was a bug which is already fixed, please try steps below and file a bug at https://github.com/pentoo/pentoo-installer if it won't help:

```
[discord] <Claes> Please excuse a real newbie question: Pentoo/USB is *very* fast on my machine (GFX TU-116 and CPU Ryzen 3900X) when run from the USB stick. But when I try to install it on an SSD of its own, installation bombs with the msg "... failed to rsync /mnt/gentoo/root. See log..." So far I have not been able to locate that log :frowning: Any pointers, please?
[discord] <Zero_Chaos> @Claes yeah, it's a known bug that's already fixed, except new isos haven't been made yet.  you can update the installer with "emerge --sync && emerge -1 pentoo-installer" and then it will work fine
[discord] <Claes> :-))) Thanks awfully! Hopefully it is Danke vielmals, Gnädige Herr in your language?
irc-bridgeadmin
[irc] <Frogbarf> pentoo-bridge I found a solution to that was to create a directory in /root/ called "*" before running the installer.     #sudo mkdir /root/*
[irc] <Zero_Chaos> Frogbarf: yeah, don't do that
[irc] <Frogbarf> too late
[irc] <Zero_Chaos> doesn't ever make a file or directory called *
[irc] <Frogbarf> i deleted it right away. Did I break something?
[irc] <Zero_Chaos> nope, it's just super bad practice
[irc] <Zero_Chaos> literally ANY file name would fix it
[irc] <Zero_Chaos> touch /root/this_will_also_work
```
