### ISSUE TITLE
88XXau module from rtl8812au_aircrack-ng

### ISSUE THREAD

**Issue by Elleni57** [pentoo/pentoo-overlay#696]
[My usb wifi](https://www.asus.com/ch-de/Networking/USB-AC68/) stopped working with recent gentoo-sources-5.10.x kernels. Last working version is gentoo-sources-5.9.8 with the ebuilds from your overlay. Is there a newer version of this driver, or am I supposed to use another package to get my usb working with recent >=gentoo-sources-5.10.x kernels? 

Thanks for providing ebuilds that support my usb-wifi anyway, really appreciate :)

**Comment by ZeroChaos-** [comment]
This driver sucks.  You can try using the 9999 ebuilds but if it doesn't work it's upstream's problem.

**Comment by Elleni57** [comment]
The 9999 ebuild compiles, but does not load with gentoo-sources-5.10.x kernel. Thanks for your quick response. :+1:

**Comment by blshkv** [comment]
The driver does not suck, but it does break with the latest and greatest kernel once in a while. All we can do is to restrict a kernel version, but it might start working with a next version again. So yeah,  please report  to upstream, provide more details. Write a more specific subject, and show what's expected and you got in your report too.

**Comment by Elleni57** [comment]
I opened an [issue](https://github.com/aircrack-ng/rtl8812au/issues/809) upstream. Thanks for providing ebuilds for gentoo guys enabling me using that hardware on my gentoo box.

**Comment by blshkv** [comment]
I suggested to provide more details, but you did not. "stopped working" is not something what developers can reproduce and fixed.
https://wiki.gentoo.org/wiki/Bugzilla/Bug_report_guide

**Comment by Elleni57** [comment]
I just did not know what to provide more as there is not much to find in dmesg or war log messages. 

In the ladder I only see: 
kernel: 88XXau: loading out-of-tree module taints kernel.
kernel: usbcore: registered new interface driver rtl88XXau

In gentoo forum someone posted a possible fix, in my opened [thread](https://forums.gentoo.org/viewtopic-t-1127689-start-0-postdays-0-postorder-asc-highlight-.html) but I was not able to try yet. And I did not have a problem to compile 9999 version, it just does not load uppon starting with 5.10.x kernel in contrary to 5.9.x and earlier kernels.

**Comment by Elleni57** [comment]
I tried to compile the [latest ebuild](https://github.com/pentoo/pentoo-overlay/blob/master/net-wireless/rtl8812au_aircrack-ng/rtl8812au_aircrack-ng-5.6.4.2_p20200118.ebuild) against gentoo-sources-5.10.12, but it failed. That's the [build.log](/var/tmp/portage/net-wireless/rtl8812au_aircrack-ng-5.6.4.2_p20200816/temp/build.log) I got.

**Comment by blshkv** [comment]
Use stable, not the latest please.

**Comment by Elleni57** [comment]
Only 9999 ebuild compiles, but it does not work anymore with kernel >5.9.8

**Comment by ZeroChaos-** [comment]
The stable ebuilds works for me on 5.10.11

**Comment by Elleni57** [comment]
Which ebuild do you mean when you say stable? In zugaina and in https://github.com/pentoo/pentoo-overlay/tree/master/net-wireless/rtl8812au_aircrack-ng I now only see the mentioned rtl8812au_aircrack-ng/rtl8812au_aircrack-ng-5.6.4.2_p20200118.ebuild

In my local overlay I also still have: 
rtl8812au_aircrack-ng-5.2.20_p20190107.ebuild
rtl8812au_aircrack-ng-5.2.20_p20190301.ebuild
rtl8812au_aircrack-ng-5.3.4_p20190511-r1.ebuild
rtl8812au_aircrack-ng-5.3.4_p20190622.ebuild
rtl8812au_aircrack-ng-5.3.4_p20191030.ebuild
rtl8812au_aircrack-ng-5.6.4.1_p20190817.ebuild
rtl8812au_aircrack-ng-5.6.4.1_p20190929.ebuild

**Comment by ZeroChaos-** [comment]
If you can't keep up to date, please don't file bugs
