### ISSUE TITLE
app-crypt/yubioath-desktop: qmake-utils_find_pro_file is banned in EAPI 7 and later

### ISSUE THREAD

**Issue by dallenwilson** [pentoo/pentoo-overlay#698]
Both ebuilds for app-crypt/yubioath-desktop are marked as EAPI=7, but src_prepare () is calling qmake-utils_find_pro_file, which was [marked as banned](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=76f21956945605bdb1d87153285e9d4ffdc4b11e) for EAPI 7 on 2020-12-26.

Existing installations unaffected, new installs or re-merges fail, spitting out the error in the title.

**Comment by blshkv** [comment]
thanks, should be fixed
