### ISSUE TITLE
net-analyzer/dsniff-2.4-r11 fails to build

### ISSUE THREAD

**Issue by drunkard** [pentoo/pentoo-overlay#700]
dsniff fails to build on my Gentoo system, looks like conflicts with net-libs/libpcap-1.10.0

Here's failure messages:

``
In file included from /usr/include/pcap.h:43,
                 from ./arpspoof.c:25:
/usr/include/pcap/pcap.h:394:16: note: declared here
  394 | PCAP_API char *pcap_lookupdev(char *)
      |                ^~~~~~~~~~~~~~
In file included from ./dnsspoof.c:29:
./pcaputil.h:14:9: error: conflicting types for ‘pcap_init’
   14 | pcap_t *pcap_init(char *intf, char *filter, int snaplen);
      |         ^~~~~~~~~
In file included from /usr/include/pcap.h:43,
                 from ./dnsspoof.c:27:
/usr/include/pcap/pcap.h:386:14: note: previous declaration of ‘pcap_init’ was here
  386 | PCAP_API int pcap_init(unsigned int, char *);
      |              ^~~~~~~~~
``

Here's emerge info:
>emerge --info net-analyzer/dsniff
> Portage 3.0.14 (python 3.8.7-final-0, default/linux/amd64/17.1/desktop/gnome/systemd, gcc-10.2.0, glibc-2.32-r7, 5.9.8-gentoo x86_64)
> =================================================================
>                          System Settings
> =================================================================
> System uname: Linux-5.9.8-gentoo-x86_64-Intel-R-_Core-TM-_i7-6700HQ_CPU_@_2.60GHz-with-glibc2.2.5
> KiB Mem:    24480804 total,    417168 free
> KiB Swap:    8388604 total,   8149676 free
> Head commit of repository gentoo: 7d3d9c4c298ee4d0790a8b4405c7f20b2b2c92cf
> 
> sh bash 5.1_p4
> ld GNU ld (Gentoo 2.35.1 p2) 2.35.1
> app-shells/bash:          5.1_p4::gentoo
> dev-java/java-config:     2.3.1::gentoo
> dev-lang/perl:            5.32.0-r1::gentoo
> dev-lang/python:          3.8.7-r1::gentoo, 3.9.1-r1::gentoo, 3.10.0_alpha4::gentoo
> dev-util/cmake:           3.19.4::gentoo
> dev-util/pkgconfig:       0.29.2::gentoo
> sys-apps/baselayout:      2.7-r1::gentoo
> sys-apps/sandbox:         2.20::gentoo
> sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r5::gentoo
> sys-devel/automake:       1.15.1-r2::gentoo, 1.16.3-r1::gentoo
> sys-devel/binutils:       2.35.1-r1::gentoo
> sys-devel/gcc:            10.2.0-r5::gentoo
> sys-devel/gcc-config:     2.3.3::gentoo
> sys-devel/libtool:        2.4.6-r6::gentoo
> sys-devel/make:           4.3::gentoo
> sys-kernel/linux-headers: 5.10::gentoo (virtual/os-headers)
> sys-libs/glibc:           2.32-r7::gentoo
> Repositories:
> 
> anyc
>     location: /var/lib/layman/anyc
>     masters: gentoo
>     priority: 50
> 
> pentoo
>     location: /var/lib/layman/pentoo
>     masters: gentoo
>     priority: 50
> 
> tlp
>     location: /var/lib/layman/tlp
>     masters: gentoo
>     priority: 60
> 
> drunkard
>     location: /var/lib/layman/drunkard
>     masters: gentoo
>     priority: 80
> 
> gentoo
>     location: /usr/portage
>     sync-type: git
>     sync-uri: git://anongit.gentoo.org/repo/gentoo.git
>     priority: 9999
> 
> ACCEPT_KEYWORDS="amd64 ~amd64"
> ACCEPT_LICENSE="*"
> CBUILD="x86_64-pc-linux-gnu"
> CFLAGS="-O2 -march=haswell -pipe"
> CHOST="x86_64-pc-linux-gnu"
> CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/gnupg/qualified.txt /var/bind"
> CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
> CXXFLAGS="-O2 -march=haswell -pipe"
> DISTDIR="/usr/portage/distfiles"
> ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
> FCFLAGS="-O2 -pipe"
> FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks downgrade-backup ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news nodoc noinfo parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
> FFLAGS="-O2 -pipe"
> GENTOO_MIRRORS="http://mirrors.ustc.edu.cn/gentoo/ http://mirrors.aliyun.com/gentoo/ http://mirrors.sohu.com/gentoo/ http://mirrors.kernel.org/gentoo/ "
> LANG="en_US.utf8"
> LC_ALL="en_US.utf8"
> LDFLAGS="-Wl,-O1 -Wl,--as-needed"
> LINGUAS="zh zh-CN zh-HK zh-TW zh_CN zh_HK zh_TW en ru de bo ug"
> MAKEOPTS="-j9"
> PKGDIR="/usr/portage/packages"
> PORTAGE_CONFIGROOT="/"
> PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
> PORTAGE_TMPDIR="/var/tmp"
> USE="X a52 aac aalib accessibility acl acpi aio alsa amd64 amr amrenc ao ap apm audit bash-completion berkdb bluetooth bluray branding broadway bzip2 cairo caps cdda cjk cleartype cli colord cracklib crypt cups dbus dga djvu dri dri3 drm dts dvd dvdr eds egl emboss encode epoll evo exif ffmpeg flac flite fontconfig fortran gallium gconf gdbm gegl geoip gif gimp glamor gles gles2 gnome gnome-keyring gnome-online-accounts gpm gstreamer gtk gtk3 gui hidpi http2 iconv icu idn imagemagick inotify introspection ipv6 jack jit jpeg jpeg2k kdbus kms lcms libass libbluray libglvnd libinput libnotify libsecret libtirpc linguas_bo linguas_de linguas_en linguas_ru linguas_ug linguas_zh linguas_zh_CN linguas_zh_HK linguas_zh_TW lto lz4 lzma lzo mad mime minizip mmap mng mp3 mp4 mpeg mtp multilib natspec nautilus ncurses networkmanager nls nptl ogg openal opencc opencl openexr opengl openmp opus pam pango pcre pdf png policykit postgres postscript ppds pulseaudio raw readline realtime sdl seccomp sftp smp split-usr ssh ssl startup-notification svg systemd theora threads tiff tracker truetype udev udisks unicode upower urandom usb usbredir v4l v4l2 vaapi vdpau vim-syntax vorbis vpx vulkan wayland webp wifi wxwidgets x264 x265 xattr xcb xinerama xkb xml xmp xpm xps xrandr xv xvid xvmc zlib" ABI_X86="64" ADA_TARGET="gnat_2018" ALSA_CARDS="hda-intel" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3" CURL_SSL="openssl" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64 pc" INPUT_DEVICES="evdev keyboard libinput mouse" KERNEL="linux" L10N="zh zh-CN zh-HK zh-TW zh_CN zh_HK zh_TW en ru de bo ug" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-3 php7-4" POSTGRES_TARGETS="postgres10 postgres11" PYTHON_SINGLE_TARGET="python3_8" PYTHON_TARGETS="python3_8" QEMU_SOFTMMU_TARGETS="i386 x86_64" QEMU_USER_TARGETS="i386 x86_64" RUBY_TARGETS="ruby26 ruby27" SANE_BACKENDS="hp hp3500" USERLAND="GNU" VIDEO_CARDS="nouveau intel i965 v4l" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
> Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS
> 
> =================================================================
>                         Package Settings
> =================================================================
> 
> net-analyzer/dsniff-2.4-r11::pentoo was built with the following:
> USE="X (-libressl)" ABI_X86="(64)"
> FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks downgrade-backup ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news nodoc noinfo parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"

**Comment by blshkv** [comment]
dsniff was released 21 years ago and it were no updates since then. Let's just drop it. 
There are multiple alternatives up there including https://github.com/pentoo/pentoo-overlay/issues/694.

**Comment by ZeroChaos-** [comment]
If it fails to build for you @blshkv then feel free to drop it

**Comment by blshkv** [comment]
I found 3 packages which depends on it. Still not willing to support the abandoned software 21 years ago. There are 26 patches in Debian, feel free to review each of them and create pull request.

**Comment by ZeroChaos-** [comment]
Nice, thanks @blshkv
