### ISSUE TITLE
[Tool request] haiti

### ISSUE THREAD

**Issue by noraj** [pentoo/pentoo-overlay#701]
[Name] Haiti
[Version] v1.0.1 (https://github.com/noraj/haiti/releases/tag/v1.0.1 3)
[Homepage] https://noraj.github.io/haiti/ 2
[Download] https://github.com/noraj/haiti/archive/v1.0.1.tar.gz - https://rubygems.org/downloads/haiti-hash-1.0.1.gem 1
[Author] noraj (Alexandre ZANNI) https://pwn.by/noraj/
[Licence] MIT - https://github.com/noraj/haiti/blob/master/LICENSE.txt
[Description] A CLI tool to identify the hash type of a given hash.
[Dependencies] ‘ruby’ ‘ruby-paint’ ‘ruby-docopt’
[Similar tools] hashid, hash-identifier, dagon, findmyhash see the diff https://noraj.github.io/haiti/#/why
[Activity] Start 16/10/2019, actively maintained
[How to install] As any classic ruby package, see package made for BlackArch: https://github.com/BlackArch/blackarch/blob/master/packages/haiti/PKGBUILD
[How to use]
Quick start https://noraj.github.io/haiti/#/pages/quick-start 1
Usage: https://noraj.github.io/haiti/#/pages/usage
[Packaged] No for debian yet, see package for BlackArch: https://github.com/BlackArch/blackarch/blob/master/packages/haiti/PKGBUILD

Is the tool useful/functional in a Penetration Testing environment?
Yes whenever you find hashes in a database or config files.

Does the tool overlap functionality of other existing tools?
Yes, hashID, findmyhash & hash-identifier.

Does the licensing of the tool allow for free redistribution?
Yes MIT.

How much resources does the tool require? Will it work in a “standard” environment?
Very few, any computer could run it.

Current source repository: https://github.com/noraj/haiti/ 1
old source repository: https://github.com/Orange-Cyberdefense/haiti

I’m the author in both cases, it’s just that the old repo is hosted on my old company organization and they won’t maintain it anymore as I leaved and was the maintainer. So I forked it on my personal account to continue maintain it.

**Comment by blshkv** [comment]
is this s.required_ruby_version = '~> 2.7' version really required? Our current stable version is 2.6 so it could be a short stopper

**Comment by noraj** [comment]
2.7 is not really required. it is that as is because I provide only support for 2.7 and to keep the same version as in rubocop rules.
ruby 2.7 works for sure.

The use of `match?()` make the code incompatible with ruby < 2.4, but 2.4 <= 2.7 should be ok.

**Comment by blshkv** [comment]
done, thanks. Great tool

**Comment by noraj** [comment]
Thanks nice & quick job.

**Comment by noraj** [comment]
What's the recommended way to install it on Pentoo? `emerge -DNu app-crypt/haiti-hash`?

**Comment by ZeroChaos-** [comment]
that should install it, yup

**Comment by blshkv** [comment]
emerge app-crypt/haiti-hash will do it
