### ISSUE TITLE
EAPI 4 dependencies break eix-sync of Pentoo tree

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#714]
Not all these are triggering errors, but should be weeded out at any rate.

/var/lib/layman/pentoo/net-misc/faifa/faifa-9999.ebuild:EAPI=4
/var/lib/layman/pentoo/net-wireless/virtualradar-bin/virtualradar-bin-2.3.1.ebuild:EAPI=4
/var/lib/layman/pentoo/media-sound/g72x++/g72x++-1.ebuild:EAPI=4
/var/lib/layman/pentoo/net-analyzer/ucsniff/ucsniff-3.20-r1.ebuild:EAPI="4"
/var/lib/layman/pentoo/net-analyzer/ucsniff/ucsniff-3.20.ebuild:EAPI="4"

**Comment by ZeroChaos-** [comment]
most of the things you mentioned were already removed, and I've removed the rest now
