### ISSUE TITLE
pentoo-packageset: add/remove packages chromium, tor, privoxy

### ISSUE THREAD

**Issue by ostree** [pentoo/pentoo-overlay#717]
Hi,

could we remove chromium in the default package set for pentoo "std" (firefox is already there) and replace this with privoxy and tor? I know that this save a compilation time but..

Why?

1. There is already one browser which is the one supporting most of expected features,
2. In most of cases I will not connect without tor with privoxy set as a http proxy (port 8118) and traffic routed over tor with anonsurf,
3. Privoxy because it saved my time when connecting over ssh tunnel to work with ESXi  and vCenter (I could use native client in this setup to get console directly on the node),
4. There is the torbrowser in the overlay so we can emerge it and use it in case if we need one public (set to browse) and one private (set to work) instance of the browser (not too many ppl use pentoo for media-related things - we have ubuntu to watch p0rn :)

**Comment by blshkv** [comment]
I don't understand how a browser can be replaced by a proxy. Anyway, all mentioned packages are part of pentoo-full and installed by default. So just run what you need. Or do I miss something?

**Comment by blshkv** [comment]
See 28b8bbd001babb62310deae87a50f3ffb2969413, I moved chrome* under "full". I did not understand that request fully and it was no follow up. So closing it, until you can explain it again

**Comment by ZeroChaos-** [comment]
also of note, privoxy and tor are both on the full iso already.  I don't specifically ship torbrowser right now because it's not hard to just configure a browser to use tor...
