### ISSUE TITLE
pentoo-overlay wiki: problem with editing

### ISSUE THREAD

**Issue by ostree** [pentoo/pentoo-overlay#718]
Hi,

I really enjoy github but I have a problem with editing wiki for the pentoo-overlay repo.
If I try to fork this repository I can't see wiki in my fork (https://github.com/pentoo/pentoo-overlay/wiki) which renders me unable to edit the content and push to main branch.
Another thing is that I try to get readthedocs to work with github wiki so we could get something like this: https://docs.pentoo.info/en/latest/ generated directly from the wiki repository.

Any suggestions how to approach this?

**Comment by ostree** [comment]
Why?

From the engineering point of view the reference point is necessary.  The wiki is a good point - we can explain and document each feature so when attempting work on this project there are already some guidance.

**Comment by blshkv** [comment]
@ZeroChaos- for your action please.

**Comment by ZeroChaos-** [comment]
this is a known issue with the way wikis work in github.  I'll push a new repo with the wiki content but I'll have to manually sync it every time so be a pal and don't make it a lot of work :-)

**Comment by blshkv** [comment]
FYI, I like readthedocs idea, you can point to a github repository to generate docs. However, it looks like an overkill at this point because we do not have that many contributors.
