### ISSUE TITLE
sys-devel/gef: removed from tree. Why?

### ISSUE THREAD

**Issue by SpeedJack** [pentoo/pentoo-overlay#722]
Commit https://github.com/pentoo/pentoo-overlay/commit/1d21e70cb9f0749ce383774f397c649343d22839 deleted gef. Why?

@blshkv

**Comment by SpeedJack** [comment]
But i see that the two stable versions are just symlinks to the live ebuild: https://github.com/pentoo/pentoo-overlay/tree/master/sys-devel/gef

**Comment by blshkv** [comment]
not sure what happened. Thanks, fixed
