### ISSUE TITLE
Burpsuite-pro: burpsuite-pro-2021.6_pre.ebuild broken symlink

### ISSUE THREAD

**Issue by YetiBarBar** [pentoo/pentoo-overlay#728]
Commit #abfaaa2cd478b3458a22c5c0c83a99f8e2117a9b introduces an absolute symlink for ebuild to /pentoo/...

```
pentoo/net-proxy/burpsuite-pro/burpsuite-pro-2021.6_pre.ebuild -> /pentoo/net-proxy/burpsuite/burpsuite-2021.6.ebuild
```

This symlink is broken and should be relative to pentoo-overlay root.

**Comment by blshkv** [comment]
yeap, both links were actually wrong, after I created teamplate. Thanks!
