### ISSUE TITLE
minimodem -f (--file) option fails

### ISSUE THREAD

**Issue by rotebaron** [pentoo/pentoo-overlay#73]
I installed minimodem by running pentoo-updater. When running minimodem with the -f option to save output to a file, an error is returned.

```
user@pentoo ~ $ echo "This is a sentence testing minimodem." | minimodem -t -f test.wav -8 1200
E: This build of minimodem was configured without sndfile,
E:   so the --file flag is not supported.
```

Eix showed that minimodem had been installed with the "sndfile" use flag disabled. 

```
user@pentoo ~ $ eix -v minimodem
* net-dialup/minimodem [1]
     Available versions:  (~)0.22.1-r1{tbz2}
     IUSE (all versions): alsa pulseaudio sndfile
     Installed versions:  Version:   0.22.1-r1{tbz2}
                          Date:      12:19:33 AM 02/08/2016
                          USE:       alsa pulseaudio -sndfile
                          DEPEND:    ${RDEPEND}
                          RDEPEND:   sci-libs/fftw:3.0 media-libs/alsa-lib media-sound/pulseaudio
     Best versions/slot:  (~)0.22.1-r1{tbz2}
     Homepage:            https://github.com/kamalmostafa/minimodem
     Description:         General-purpose software audio FSK modem.
     License:             GPL-3+
```

Adding the "sndfile" use flag for minimodem to /etc/portage/package.use and reinstalling minimodem with the command "emerge --ask --changed-use --oneshot net-dialup/minimodem" fixed the problem on my machine. I would recommend adding the "sndfile" use flag by default.

**Comment by ZeroChaos-** [comment]
there isn't a bug here, the program properly told you that it was built without file support

that said, file support seems pretty basic so I'll make it default.

**Comment by blshkv** [comment]
Good suggestion, thank you
