### ISSUE TITLE
missing applications

### ISSUE THREAD

**Issue by richardredditch** [pentoo/pentoo-overlay#736]
Hi,

I am following classes at tryhackme.com and I just found that there are some applications/programs missing which are expected to be used to complete a class. I would like to ask your oppinion on this and about possibility to include missing parts in the release,

apps/progrms:
dirbuster
impacket (looks like it is already on my copy of the release but I can't call it from the terminal - will have to look in to this:

dev-python/impacket
      Latest version available: 9999
      Latest version installed: 9999
      Size of files: 0 KiB
      Homepage:      https://github.com/SecureAuthCorp/impacket
      Description:   A collection of Python classes focused on providing access to network packets
      License:       Apache-2.0
)

Many thanks,

emerge --info: https://pastebin.com/2mbEMaH4

ori / # uname -a 
Linux ori 5.12.13-pentoo #1 SMP Thu Jul 8 22:02:27 UTC 2021 x86_64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz GenuineIntel GNU/Linux

ori / # eselect profile list
Available profile symlink targets:
[45]  pentoo:pentoo/hardened/linux/amd64_r1/bleeding_edge (dev) *

**Comment by blshkv** [comment]
Dirbuster old and no longer supported, see https://github.com/pentoo/pentoo-overlay/issues/320. Use a better alternative and tell your class too.

There is no "impact" binary, because it is a set of small tools
```equery f impacket | grep bin```

**Comment by blshkv** [comment]
```dirsearch
dirble-bin
dirb
dirhunt
dirsearch
```

and few more probably
