### ISSUE TITLE
jd-gui ebuild fails when attempting to run with gradle 7.1.1

### ISSUE THREAD

**Issue by jblandrum** [pentoo/pentoo-overlay#737]
https://github.com/pentoo/pentoo-overlay/blob/master/dev-util/jd-gui/jd-gui-1.6.6-r3.ebuild

jd-gui ebuild fails when attempting to build with gradle version 7.1.1
this seems to have to do with removal of deprecated methods in gradle 7+
https://github.com/gradle/gradle/issues/8585

the runtime and compile methods have been deprecated in favor of runtimeOnly implementation and compileOnly
also configurations.runtime and configurations.compile have been deprecated in favor of configurations.runtimeClasspath and configurations.compileClasspath

the attached patch for the ebuild checks grade version and updates the appropriate methods

[jd-gui-1.6.6-r3.ebuild.patch.txt](https://github.com/pentoo/pentoo-overlay/files/6984656/jd-gui-1.6.6-r3.ebuild.patch.txt)

**Comment by ZeroChaos-** [comment]
@blshkv I don't want to break anything, so can you please look at this?

**Comment by blshkv** [comment]
Please report tp upstream

**Comment by blshkv** [comment]
the patch seems tricky, especially removing OsxApp.java part. I would rather wait for the upstream while we can still use 6.1
