### ISSUE TITLE
app-admin/opensnitch: install systemd service file

### ISSUE THREAD

**Issue by telans** [pentoo/pentoo-overlay#738]
Hi, it would be great if the below could be installed with the `systemd` use flag or some sort.

https://github.com/pentoo/pentoo-overlay/blob/bb5ae0d5541d1bd182a1885f34472cb7a457e686/app-admin/opensnitch/opensnitch-1.3.6.ebuild#L74

Thanks.

---

On a side note, it looks like 1.4.0 has been marked yet not tagged in git. https://github.com/evilsocket/opensnitch/commit/041cf456dc121e7871955b767f5adbf2191bf855

**Comment by blshkv** [comment]
So the thing with ```systemd``` is that we don't support it. I don't have a setup to check. So please create and test required files and raise a pull request.

I subscribed to the "release" event and will be notified when it is released.

**Comment by telans** [comment]
Fair enough, cheers.
