### ISSUE TITLE
cross-i686-pc-mingw32/gcc-5.3.0::pentoo failed (compile phase)

### ISSUE THREAD

**Issue by bill-e-ghote** [pentoo/pentoo-overlay#74]
I'm following the guidance here:
https://wiki.gentoo.org/wiki/Mingw
1. emerge --ask sys-devel/crossdev
2. crossdev -t i686-pc-mingw32

I would have thought this should have loaded non-Pentoo stuff, but it consistently craps out here.
Makefile:5490: recipe for target 'chmod.lo' failed
make[3]: *** [chmod.lo] Error 1
...and then cascades from there. 

See attachments for details. Should this properly go to Gentoo bug support, or...?
Thanks.

[files.zip](https://github.com/pentoo/pentoo-overlay/files/131799/files.zip)

**Comment by blshkv** [comment]
Yes, please file an upstream report. We will not fork a none security related ebuilds

**Comment by bill-e-ghote** [comment]
I opened the ticket here because this is the ebuild that is failing, and it is already forked into Pentoo:

cross-i686-pc-mingw32/gcc

So, why is that there?

**Comment by blshkv** [comment]
nop, can't confirm that. It is normally getting copied to your local /usr/local/portage.
That's how crossdev works

**Comment by blshkv** [comment]
As a quick note you might want to stay on stable. Or you can try to disable -fortran USE flag if really need it since the error seems fortran related
