### ISSUE TITLE
  net-analyzer/wpscan-3.8.* build error.

### ISSUE THREAD

**Issue by Jacekalex** [pentoo/pentoo-overlay#742]
Hi

My os:
`Linux version 5.10.68-g1 (root@localhost) (gcc (Gentoo Hardened 10.3.0-r2 p3) 10.3.0, GNU ld (Gentoo 2.35.2 p1) 2.35.2) #1 SMP PREEMPT Fri Sep 24 02:22:30 CEST 2021`

I'm trying to install wpscan, but on both available versions (3.8.15; 3.8.18) I have this error:

`
Resolving dependencies...
Bundler could not find compatible versions for gem "addressable":
  In Gemfile:
    wpscan was resolved to 3.8.18, which depends on
      cms_scanner (~> 0.13.5) was resolved to 0.13.5, which depends on
        opt_parse_validator (~> 1.9.4) was resolved to 1.9.4, which depends on
          addressable (>= 2.5, < 2.8)

Could not find gem 'addressable (>= 2.5, < 2.8)', which is required by gem 'opt_parse_validator (~> 1.9.4)', in rubygems repository
https://rubygems.org/ or installed locally.[0m
 * ERROR: net-analyzer/wpscan-3.8.18::pentoo failed (prepare phase):
 *   (no error message)
`
 The only available version of dev-ruby/addressable in portage is dev-ruby/addressable-2.8.0

Cheers

**Comment by blshkv** [comment]
thanks fixed 5cf010d20044c83b287db066a887bc5b87e614c0
