### ISSUE TITLE
dev-util/retdec-4.0: fails to compile

### ISSUE THREAD

**Issue by gerion0** [pentoo/pentoo-overlay#747]
See attached [build.log](https://github.com/pentoo/pentoo-overlay/files/7398167/build.log). The changelog says, retdec-4.0 is compatible with LLVM 8 that is not in the tree anymore.
.

**Comment by blshkv** [comment]
agreed, there is no point trying to fix a tool which is not actively maintained. Use a better alternative such cutter or ghidra.
The ebuild is masked, it's good enough.
