### ISSUE TITLE
tool request - libmpsse

### ISSUE THREAD

**Issue by rotebaron** [pentoo/pentoo-overlay#75]
libmpsse - Open source library for SPI/I2C control via FTDI chips

https://github.com/devttys0/libmpsse

**Comment by blshkv** [comment]
I suggest to redirect it to gentoo. It has nothing to do with security

**Comment by rotebaron** [comment]
I can submit the request to Gentoo if need be. I would say that the package is security related. One of the examples included in the package (and the functionality that I am most interested in) reads from and writes to SPI flash chips, which is really useful for reverse engineering embedded devices such as wireless routers. I have seen that the dev-embedded/libftdi package is available in Gentoo- it is a dependency for libmpsse.

**Comment by blshkv** [comment]
ok, in the tree. You will need to emerge it with "examples" use flag to install examples as well. Python is an option as well.
