### ISSUE TITLE
Ghidra {BROKEN Dependencies}

### ISSUE THREAD

**Issue by Ganome** [pentoo/pentoo-overlay#753]
>>> Downloading 'https://www.eclipse.org/downloads/download.php?r=1&protocol=https&file=/tools/cdt/releases/8.6/cdt-8.6.0.zip'
--2021-11-07 11:24:27--  https://www.eclipse.org/downloads/download.php?r=1&protocol=https&file=/tools/cdt/releases/8.6/cdt-8.6.0.zip
Resolving www.eclipse.org... 198.41.30.198
Connecting to www.eclipse.org|198.41.30.198|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://eclipse.mirror.rafal.ca/tools/cdt/releases/8.6/cdt-8.6.0.zip [following]
--2021-11-07 11:24:28--  https://eclipse.mirror.rafal.ca/tools/cdt/releases/8.6/cdt-8.6.0.zip
Resolving eclipse.mirror.rafal.ca... 2604:1500:f001:0:216:3eff:fe3f:746b, 207.210.46.249
Connecting to eclipse.mirror.rafal.ca|2604:1500:f001:0:216:3eff:fe3f:746b|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-11-07 11:24:28 ERROR 404: Not Found.

!!! Couldn't download 'cdt-8.6.0.zip'. Aborting.
 * Fetch failed for 'dev-util/ghidra-10.0.4', Log file:
 *  '/var/tmp/portage/dev-util/ghidra-10.0.4/temp/build.log'

**Comment by blshkv** [comment]
done, thanks
