### ISSUE TITLE
EAPI of qtserialport too new for stable

### ISSUE THREAD

**Issue by bseibold** [pentoo/pentoo-overlay#754]
Either the EAPI should be decreased to a value that is suitable for Gentoo stable, or the package should be keyword-masked.

**Comment by ZeroChaos-** [comment]
it's stable in gentoo as well, maybe update your portage once in a while.

**Comment by bseibold** [comment]
You're right, it's in stable. No idea where that warning came from, system is up to date. Anyway, thanks for the ~~friendly~~ response.

**Comment by ZeroChaos-** [comment]
Any time, we always appreciate a ~~friendly~~ bug report.

**Comment by blshkv** [comment]
4c40553fbce2bc9b318e100b58e7fd784fe60a13 may be not related, but I pushed that patch just in case. The ebuild is exactly the same with Gentoo (+build patch) now.
