### ISSUE TITLE
app-antivirus/lkrg-0.9.1_p20210913 fails to compile: p_lkrg_main.h:391:3: error: #error "LKRG requires CONFIG_KALLSYMS_ALL" 

### ISSUE THREAD

**Issue by asarubbo** [pentoo/pentoo-overlay#756]
https://blogs.gentoo.org/ago/2020/07/04/gentoo-tinderbox/

Issue: app-antivirus/lkrg-0.9.1_p20210913 fails to compile.
Discovered on: amd64 (internal ref: pentoo_tinderbox)

At the time of writing, github-cli does not support attachments. I'm using gists but they can be deleted at a certain point. If you want to save them, please create attachments on your own.

build log: https://gist.github.com/55b3f175d2008e6b298419cd6f51eab7

**Comment by blshkv** [comment]
Read the error and do what it says

**Comment by ZeroChaos-** [comment]
We should add a fatal check to the ebuild not close it like it's invalid

**Comment by blshkv** [comment]
It is fatal and it is invalid

**Comment by asarubbo** [comment]
> It is fatal and it is invalid

I don't guess so, you should use CONFIG_CHECK from linux-info.eclass

**Comment by ZeroChaos-** [comment]
There is not a single call to config check in this ebuild.  There should be.  I realize some of this is new to you @blshkv but please stop shitting on people who are trying to help us improve.

**Comment by blshkv** [comment]
I will probably unsubscribe from this tracker completely because majority of our ebuilds are not tested on all these Gentoo QA. It will be hundreds if such my reports and i simple don't have time for it

**Comment by ZeroChaos-** [comment]
Whatever you need to do.  Just don't be surprised when your ebuilds are fixed.

**Comment by blshkv** [comment]
The fix to silent that stupid tool. There are more complex checked missing, see ```src/p_lkrg_main.h```

**Comment by blshkv** [comment]
> There is not a single call to config check in this ebuild. There should be. I realize some of this is new to you @blshkv but please stop shitting on people who are trying to help us improve.

not true. See the ebuild, a single config check call was there.

**Comment by ZeroChaos-** [comment]
Sorry, I did read it wrong.  I usually individually call the checks so I can put custom error messages in.  Thanks for the fix.
