### ISSUE TITLE
arachni unbuildable

### ISSUE THREAD

**Issue by ZeroChaos-** [pentoo/pentoo-overlay#79]
emerge: there are no ebuilds to satisfy "=dev-ruby/awesome_print-1.2*[ruby_targets_ruby21]".
(dependency required by "www-apps/arachni-1.3.2-r2::pentoo" [binary])

looks like gentoo pulled old versions of awesome_print

**Comment by blshkv** [comment]
Feel free to fork it for now.

**Comment by blshkv** [comment]
Done, see 57449462065fb85ccef571a3502dfc694f6b31b9
