### ISSUE TITLE
emerging zaproxy fails to download selenium-release-3.zap

### ISSUE THREAD

**Issue by rotebaron** [pentoo/pentoo-overlay#80]
When trying to emerge net-proxy/zaproxy-2.4.3 downloading the file 'https://github.com/zaproxy/zap-extensions/releases/download/2.4/selenium-release-3.zap' fails with a 404: Not Found error.

The zaproxy 2.4 release in the GitHub repo ( https://github.com/zaproxy/zap-extensions/releases ) lists selenium-release-4.zap and selenium-release-5.zap, but not selenium-release-3.zap.

**Comment by blshkv** [comment]
171406736cb6df0ea7fd31fdbe7418a7ce1affb2 bump few other plugins as well. Thanks!
