### ISSUE TITLE
more veil stuff 

### ISSUE THREAD

**Issue by necrose99** [pentoo/pentoo-overlay#81]
net-analyzer/veil for Meta package template.... 
https://github.com/necrose99/necromancy-overlay/blob/master/net-analyzer/veil-ordnance/veil-ordnance-9999.ebuild

https://github.com/necrose99/necromancy-overlay/blob/master/net-analyzer/veil-catapult/veil-catapult-9999.ebuild

https://github.com/necrose99/necromancy-overlay/blob/master/net-analyzer/veil-ordnance/veil-ordnance-9999.ebuild 

https://github.com/necrose99/necromancy-overlay/tree/master/app-emulation/veil-wine 
all the crap for wine & veil 
 , much to do to get it to work  just haven't had much time doing Cert prep for CCNA/CISSP/COMPTIA SEC+ 

Some tentative things for Veil  , based on existing veil-evasion ebuild  (Yours @blshkv) 

if you take them I can clean them. from overlay/s (trying to de-crufft) 
 however I will try to clean up the Wine templates to match the upstream wine prefix  install  , and add in packages for wget etc.  
least some of my  mentions upsteam has them converting to user installs instead of root and a wine prefix instead of /root/.wine 
and by suggestion ability to shred/nuke the wine prefix  (debian) mine has to be cleanup from prior. 
installs and or completed pentests.... 
anyhow i hopefully can get to them so that it will build wine prefix for veil use as a simple shell script 
and a kill folder or shred it from users veil-wine prefix can also be done. 

also tying to make a simple setup.py for veil-frame work items to further simplify life or 9999 installs. 
and less work for everyone in the future.

**Comment by blshkv** [comment]
Yeah, veil need more love. Your ebuilds looks half-broken. For example, veil-catapult ebuild has veil-ordnance as a source. You probably spent 5 minutes to copy my ebuild and never tested it. Please make sure that all basics settings are in place and ebuild works before submitting it...

**Comment by necrose99** [comment]
https://raw.githubusercontent.com/necrose99/necromancy-overlay/master/dev-python/impacket/
for now I've bumped it , so far Pentoo VM sucks at work , proxy is borking much...  xml error from layman , had to move to Houston for a gig for now..  just need a HDD for laptop or  Server .. for home. 

I havent had much a chance to test but i did Avail your templates to test to see if I can get them to install the other veil parts. hopefully,....... of late have a backlog.

**Comment by blshkv** [comment]
bumped in https://github.com/pentoo/pentoo-overlay/commit/86361265ed757f6843ff53d1b6822594c46d9535

**Comment by necrose99** [comment]
veil 3.x is out. 
catapult i think is DOA... 
others are still supported....

**Comment by blshkv** [comment]
I'll close this bug since you open a new one for veil 3

**Comment by necrose99** [comment]
yeap veil catapult is now integrated...   so i can also prune from necromancy 
need to fix veil-wine , as it can use winetricks or kill users ./veil-wine on time to clean/rebuild ...
