### ISSUE TITLE
new tool: WiFi-Pumpkin

### ISSUE THREAD

**Issue by blshkv** [pentoo/pentoo-overlay#93]
https://github.com/P0cL4bs/WiFi-Pumpkin/blob/master/README.md

**Comment by ostree** [comment]
well done - thx

**Comment by ostree** [comment]
two issues:
===
arrakis me # wifi-pumpkin 
which: no hostapd-wpe in (/sbin:/bin:/usr/sbin:/usr/bin)
[✘] hostapd is not installed.
Loading GUI...
which: no driftnet in (/sbin:/bin:/usr/sbin:/usr/bin)
WiFi-Pumpkin Running!
===

1) looks like we need a symlink: ln -s hostapd hostapd-wpe in: /usr/sbin (the wpe flag is enabled)
2) looks like we have a hidden dep:  net-analyzer/driftnet

Kind Regards

**Comment by blshkv** [comment]
that was a workaround for a newer hostapd, fixed in 5e89ca7c95acd8ba1aa02d417deefd68a4489846

**Comment by blshkv** [comment]
Bad news. 
I'm trying to port the latest version and facing a problem with mitmproxy (which I have just bumped).
Apparently, the latest version does not support python2 anymore (which make sense), however, wifi-pumking developers insist that the project went too far and it will be too hard to support Python3 (FML, LOL?). See the following for more details:
https://github.com/P0cL4bs/WiFi-Pumpkin/issues/174
So I'm moving mimtproxy tool under plugins flag (which is not enabled by default) and will forget about this tool for now. I can't waste my time with a dead end project.

**Comment by blshkv** [comment]
Oh, and mitmproxy.models is no longer optional. Isn't it great?..
