### ISSUE TITLE
www-apps/arachni depends on dev-ruby/kramdown-1.4.1, which is not in tree

### ISSUE THREAD

**Issue by willard-dawson-nyl** [pentoo/pentoo-overlay#94]
>>> Emerging (2 of 2) www-apps/arachni-1.4::pentoo
 * arachni-1.4.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...               [ ok ]
>>> Unpacking source...
>>> Unpacking arachni-1.4.tar.gz to /mnt/disk-image4/portage/www-apps/arachni-1.4/work/all
>>> Source unpacked in /mnt/disk-image4/portage/www-apps/arachni-1.4/work
>>> Preparing source in /mnt/disk-image4/portage/www-apps/arachni-1.4/work ...
 * Running prepare phase for all ...
 * Running source copy phase for ruby21 ...
 * Running prepare phase for ruby21 ...
 * Applying 1.4-config.patch ...
 [ ok ]
 * Applying 1.4-easierdep.patch ...
 [ ok ]
Resolving dependencies...
Bundler could not find compatible versions for gem "kramdown":
  In Gemfile:
    arachni was resolved to 1.4, which depends on
      kramdown (~> 1.4.1)

Could not find gem 'kramdown (~> 1.4.1)', which is required by gem 'arachni', in
any of the sources.ESC[0m
 * ERROR: www-apps/arachni-1.4::pentoo failed (prepare phase):
 *   (no error message)
 * 
 ...

**Comment by blshkv** [comment]
we do have dev-ruby/kramdown-1.4.2
```
emerge -pv arachni

These are the packages that would be merged, in reverse order:

Calculating dependencies... done!
[ebuild   R   ~] www-apps/arachni-1.4::pentoo  USE="{-test}" RUBY_TARGETS="ruby21" 0 KiB
[ebuild  N    ~]  dev-ruby/kramdown-1.4.2::gentoo  USE="-doc -latex {-test}" RUBY_TARGETS="ruby20 ruby21" 222 KiB
```

**Comment by willard-dawson-nyl** [comment]
Yes, but did you look at the full error message?  The install fails 
because it checks the Gem and requires 1.4.1.  So...?



Willard Dawson
CORPORATE VICE PRESIDENT • ENTERPRISE TECHNOLOGY

NEW YORK LIFE INSURANCE COMPANY
5965 Cabot Parkway, Alpharetta, GA 30005
* Willard_Dawson@newyorklife.com ( (770) 406-4294 Alt (770) 557-8395
 facebook.com/newyorklife |  twitter.com/newyorklife

**Comment by blshkv** [comment]
'~> 1.4.1' means 1.4.x. which should work. Why do you see the error?

**Comment by willard-dawson-nyl** [comment]
Maybe this helps...



Not sure why I'm seeing this error. This is a Gentoo + Pentoo from overlay 
instance running as a  VirtualBox guest on a Win7 Pro host.  I have had a 
mess on this one from manually tweaked ebuilds and playing with setting 
RUBY_TARGETS to various single instances (presently it's simply 
RUBY_TARGETS="ruby21").  So, it's conceivable that I screwed something up 
somewhere.  I ripped out ruby and every gem everywhere (properly, with 
emerge -C), and rebuilt it all up to this point.  I'm about ->this<- close 
to starting over again from scratch and only bringing /home with me to the 
new system.

This is what I do see:



From the top:





Willard Dawson
CORPORATE VICE PRESIDENT • ENTERPRISE TECHNOLOGY

NEW YORK LIFE INSURANCE COMPANY
5965 Cabot Parkway, Alpharetta, GA 30005
* Willard_Dawson@newyorklife.com ( (770) 406-4294 Alt (770) 557-8395
 facebook.com/newyorklife |  twitter.com/newyorklife

**Comment by blshkv** [comment]
what I really like about Gentoo is that starting from scratch does not help ;-) You need to find the problem and fix it. And there is always a way to remove your custom settings and rebuild the system.
I don't understand why you had to customise ebuilds. This is wrong. 

"this is what I see" is empty in your post. Please post the error again.

**Comment by willard-dawson-nyl** [comment]
iWhy? Because I wanted metasploit-9999 to work with the latest, greatest. 
And, that really seems to have been abandoned. So, I created my own local 
ebuilds for dev-ruby things that are totally missing.  That worked for a 
while, but it got ugly.

Rather than replying by email, it  seems I may need to go back to the 
github portal to upload "this is what I see" screenshots. OK, I will do 
that.



Willard Dawson
CORPORATE VICE PRESIDENT • ENTERPRISE TECHNOLOGY

NEW YORK LIFE INSURANCE COMPANY
5965 Cabot Parkway, Alpharetta, GA 30005
* Willard_Dawson@newyorklife.com ( (770) 406-4294 Alt (770) 557-8395
 facebook.com/newyorklife |  twitter.com/newyorklife

**Comment by blshkv** [comment]
It is totally to drop few missed deps to your local overlay. That should not mess up the rest of the system .. So the issue still reminds unclear.

**Comment by blshkv** [comment]
ok, closing for now.
btw, the latest msf is in the tree:
https://github.com/pentoo/pentoo-overlay/commit/af60ba0d5c54408e7be2a2594069d56c229e6ca2
