### ISSUE TITLE
net-analyzer/ppscan 404 not found

### ISSUE THREAD

**Issue by VZIKL** [pentoo/pentoo-overlay#95]
>>> Downloading 'http://mirrors.163.com/gentoo/distfiles/ppscan-0.3.tar.gz'
--2016-06-04 01:39:30--  http://mirrors.163.com/gentoo/distfiles/ppscan-0.3.tar.gz
Resolving mirrors.163.com... 123.58.173.185, 123.58.173.186
Connecting to mirrors.163.com|123.58.173.185|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-06-04 01:39:30 ERROR 404: Not Found.

>>> Downloading 'http://packetstorm.wowhacker.com/UNIX/scanners/ppscan-0.3.tar.gz'
--2016-06-04 01:39:30--  http://packetstorm.wowhacker.com/UNIX/scanners/ppscan-0.3.tar.gz
Resolving packetstorm.wowhacker.com... 40.78.101.254
Connecting to packetstorm.wowhacker.com|40.78.101.254|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://wowhacker.org/UNIX/scanners/ppscan-0.3.tar.gz [following]
--2016-06-04 01:39:31--  https://wowhacker.org/UNIX/scanners/ppscan-0.3.tar.gz
Resolving wowhacker.org... 40.78.101.254
Connecting to wowhacker.org|40.78.101.254|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-06-04 01:39:32 ERROR 404: Not Found.

**Comment by blshkv** [comment]
Done. Thanks!
