### ISSUE TITLE
net-analyzer/inguma-0.4-r1 cant't to download

### ISSUE THREAD

**Issue by VZIKL** [pentoo/pentoo-overlay#96]
>>> Downloading 'http://inguma.eu/attachments/download/105/inguma-0.4.tar.gz'
--2016-06-04 20:41:31--  http://inguma.eu/attachments/download/105/inguma-0.4.tar.gz
Resolving inguma.eu... 92.243.18.42, 2001:4b98:dc0:43:216:3eff:fe98:fc15
Connecting to inguma.eu|92.243.18.42|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://inguma.eu/attachments/download/105/inguma-0.4.tar.gz [following]
--2016-06-04 20:41:31--  https://inguma.eu/attachments/download/105/inguma-0.4.tar.gz
Connecting to inguma.eu|92.243.18.42|:443... connected.
ERROR: cannot verify inguma.eu's certificate, issued by ‘CN=Gandi Standard SSL CA 2,O=Gandi,L=Paris,ST=Paris,C=FR’:
  Issued certificate has expired.
To connect to inguma.eu insecurely, use `--no-check-certificate'.
!!! Couldn't download 'inguma-0.4.tar.gz'. Aborting.

**Comment by VZIKL** [comment]
>>> Downloading 'http://packetstorm.wowhacker.com/fuzzer/ohrwurm-0.1.tar.bz2'
--2016-06-04 20:53:03--  http://packetstorm.wowhacker.com/fuzzer/ohrwurm-0.1.tar.bz2
Resolving packetstorm.wowhacker.com... 40.78.101.254
Connecting to packetstorm.wowhacker.com|40.78.101.254|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://wowhacker.org/fuzzer/ohrwurm-0.1.tar.bz2 [following]
--2016-06-04 20:53:04--  https://wowhacker.org/fuzzer/ohrwurm-0.1.tar.bz2
Resolving wowhacker.org... 40.78.101.254
Connecting to wowhacker.org|40.78.101.254|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-06-04 20:53:05 ERROR 404: Not Found.

!!! Couldn't download 'ohrwurm-0.1.tar.bz2'. Aborting.

**Comment by blshkv** [comment]
The second issue is fixed, and there is nothing we can do with the first one:
https://github.com/inguma/bokken/issues/26

Feel free to contact upstream

**Comment by blshkv** [comment]
got a positive feedback from the bug above

**Comment by Jo-Con-El** [comment]
inguma.eu is reachable again through HTTPS.

**Comment by bill-e-ghote** [comment]
inguma.eu cert expired over six months ago. Additionally, I cannot download https://inguma.eu/attachments/download/105/inguma-0.4.tar.gz due to "network errors"... which I seriously doubt are on my end, though anything is possible.
