### ISSUE TITLE
Fetch failed for 'sys-kernel/pentoo-sources-4.0.8' - genpatches-4.0-9.base.tar.xz not found

### ISSUE THREAD

**Issue by willard-dawson-nyl** [pentoo/pentoo-overlay#97]
This is a brand-new instance installed from 2015.0 RC4.6.  See build log for details.

[build.zip](https://github.com/pentoo/pentoo-overlay/files/298928/build.zip)

**Comment by blshkv** [comment]
yeah, 4.0.8 is old. You can either download the missing patch manualy (https://dev.gentoo.org/~mpagano/genpatches/tarballs/) and drop it into /usr/portage/distfiles
or unmask a newer one (4.4.2)
