### ISSUE TITLE
Pentoo binhost errors

### ISSUE THREAD

**Issue by willard-dawson-nyl** [pentoo/pentoo-overlay#98]
I opened this a while back but did not see any response:
https://github.com/pentoo/pentoo-installer/issues/11

The errors propagate into my instance installed from the "latest" Pentoo LiveCD/installer (running as a Virtualbox guest), so it's also an issue within the overlay, I think.  If I don't modify the BINHOST configured in the overlay tree, I see the following error whenever I try to update world (manually copied, please excuse any typos):

!!! Error fetching binhost package info from 'http://pentoo.east.us.mirror.inerail.net/Packages/amd64-hardened/'
!!! HTTP Error 522: Origin Connection Time-out

I tried setting PORTAGE_BINHOST in my make.conf to the US Pentoo mirror, but that also does not work.  The site is available for the LiveCD images, but apparently not as a binhost mirror?

Probably what I need to do is re-emerge all without binpkg support?  That will literally take forever?

**Comment by blshkv** [comment]
I will let @ZeroChaos- to reply on this. Both Inerail mirrors are down. 
You can use http://mirror.switch.ch/ftp/mirror/pentoo/*  for now

**Comment by willard-dawson-nyl** [comment]
Thanks for the update.

When I do configure my PORTAGE_BINHOST to point to that host, I get 
another error:

!!! Binhost package index version is not supported: 'None'



Willard Dawson
CORPORATE VICE PRESIDENT • ENTERPRISE TECHNOLOGY

NEW YORK LIFE INSURANCE COMPANY
5965 Cabot Parkway, Alpharetta, GA 30005
* Willard_Dawson@newyorklife.com ( (770) 406-4294 Alt (770) 557-8395
 facebook.com/newyorklife |  twitter.com/newyorklife

**Comment by blshkv** [comment]
You  need to point it to the same directly, I.e. amd64-hardened in your case

**Comment by willard-dawson-nyl** [comment]
*sigh*

Sorry, now I just feel stupid, as that was a rather obvious error...

Thanks.



Willard Dawson
CORPORATE VICE PRESIDENT • ENTERPRISE TECHNOLOGY

NEW YORK LIFE INSURANCE COMPANY
5965 Cabot Parkway, Alpharetta, GA 30005
* Willard_Dawson@newyorklife.com ( (770) 406-4294 Alt (770) 557-8395
 facebook.com/newyorklife |  twitter.com/newyorklife

**Comment by blshkv** [comment]
0ad150ce53ad5bba7244ac8117a7ef9141b5ac43
